import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  createTheme,
  generateBreakpointCustomMedia,
  generateTailwindThemeCss,
} from '@mui/material/styles';
import { customBreakpoints } from '../src/theme';

const dirname = path.dirname(fileURLToPath(import.meta.url));
const srcRoot = path.resolve(dirname, '../src');
const theme = createTheme({ breakpoints: customBreakpoints });

await writeFile(
  path.join(srcRoot, 'mui.css'),
  [
    '/* Generated by scripts/buildMuiCss.mts. */',
    '@layer theme, base, mui, components, utilities;',
    '',
    "@import 'tailwindcss/theme.css' layer(theme);",
    "@import 'tailwindcss/utilities.css' layer(utilities);",
    "@import '@mui/material/styles-source.css';",
    "@import './tailwind-theme.css';",
    '',
    generateBreakpointCustomMedia(theme),
    '',
  ].join('\n'),
);

await writeFile(
  path.join(srcRoot, 'tailwind-theme.css'),
  ['/* Generated by scripts/buildMuiCss.mts. */', generateTailwindThemeCss(theme), ''].join('\n\n'),
);
