packages:
  - packages/*
  - packages/mui-envinfo/test
  - packages-internal/*
  - docs
  - demo
  - test
  - test/*

patchedDependencies:
  styled-components: patches/styled-components.patch

onlyBuiltDependencies:
  - '@vvago/vale'

engineStrict: true
