packages:
  - benchmark
  - packages/*
  - packages/mui-envinfo/test
  - packages-internal/*
  - docs
  - test
  - test/moduleResolution
  - apps/*
  - scripts/sizeSnapshot
onlyBuiltDependencies:
  - esbuild
  - msw
  - nx
