packages:
  - packages/*
  - packages/mui-envinfo/test
  - packages-internal/*
  - docs
  - test
  - test/*

engineStrict: true

onlyBuiltDependencies:
  - '@mui/x-telemetry'
  - '@vvago/vale'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - nx
  - sharp
  - unrs-resolver

patchedDependencies:
  styled-components: patches/styled-components.patch
