const ROUTES = {
  home: '/branding/',
  productCore: '/branding/products/core/',
  productAdvanced: '/branding/products/advanced/',
  productTemplates: '/branding/products/templates/',
  productDesignKits: '/branding/products/design-kits/',
  materialIcons: '/components/material-icons/',
  freeTemplates: '/getting-started/templates/',
  components: '/branding/resources/components/',
  customization: '/branding/resources/customization/',
  styling: '/branding/resources/styling/',
  documentation: '/branding/documentation/',
  pricing: '/branding/pricing/',
  blog: '/blog/',
  showcase: '/discover-more/showcase',
  roadmap: '/discover-more/roadmap',
  languages: '/discover-more/languages',
  about: '/branding/about/',
  vision: '/branding/vision/',
  careers: '/branding/careers/',
  support: '/branding/support/',
  contactUs: '/branding/contact-us/',
};

export default ROUTES;
