const ROUTES = {
  home: '/branding/',
  productCore: '/branding/core/',
  productAdvanced: '/branding/advanced/',
  productTemplates: '/branding/templates/',
  productDesignKits: '/branding/design-kits/',
  materialIcons: '/components/material-icons/',
  freeTemplates: '/getting-started/templates/',
  components: '/branding/resources/components/',
  customization: '/branding/resources/customization/',
  styling: '/branding/resources/styling/',
  documentation: '/branding/documentation/',
  pricing: '/branding/pricing/',
  blog: '/blog/',
  showcase: '/discover-more/showcase',
  roadmap: '/discover-more/roadmap',
  languages: '/discover-more/languages',
  about: '/branding/about/',
  vision: '/discover-more/vision/',
  careers: '/company/careers/',
  support: '/getting-started/support/#professional-support-premium',
  contactUs: '/branding/contact-us/',
  storeFigma: 'https://material-ui.com/store/items/figma-react/',
  storeSketch: 'https://material-ui.com/store/items/sketch-react/',
  storeXD: 'https://material-ui.com/store/items/adobe-xd-react/',
  storeTemplateMaterialApp: 'https://material-ui.com/store/items/material-app/',
  storeTemplateBarza: 'https://material-ui.com/store/items/bazar-pro-react-ecommerce-template/',
  storeTemplateMinimalFree: 'https://material-ui.com/store/items/minimal-dashboard-free/',
  storeTemplateMinimalDashboard: 'https://material-ui.com/store/items/minimal-dashboard/',
  storeTemplateBerry: 'https://material-ui.com/store/items/berry-react-material-admin/',
  storeTemplateWebbee: 'https://material-ui.com/store/items/webbee-landing-page/',
  storeTheFront: 'https://material-ui.com/store/items/the-front-landing-page/',
  storeFlexy: 'https://material-ui.com/store/items/flexy-react-admin-dashboard/',
};

export default ROUTES;
