// flow-typed signature: 38e26ff988b219279c86cfbe174dcca7
// flow-typed version: <<STUB>>/@types/enzyme_v^3.1.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
