// flow-typed signature: 4373a7a64277658ce2b3eb3f3c6cdd46
// flow-typed version: <<STUB>>/@types/enzyme_v^2.8.6/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
