// flow-typed signature: 5297e6bcf48dbbdf72036cf4f0e74a89
// flow-typed version: <<STUB>>/@types/enzyme_v^2.8.6/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
