// flow-typed signature: b959e537a8829a43b278d18dd432d5a9
// flow-typed version: <<STUB>>/@types/react_v16.0.19/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
