import Typography from '@mui/material/Typography';
import { Typography as MyTypography } from '@mui/material';

<Typography />;
<MyTypography />;
<Typography className="my-class" />;
<MyTypography className="my-class" />;
<Typography paragraph />;
<MyTypography paragraph />;
<Typography paragraph className="my-class" />;
<MyTypography paragraph className="my-class" />;
<Typography paragraph={false} className="my-class" />;
<MyTypography paragraph={false} className="my-class" />;
<Typography paragraph={paragraph} className="my-class" />;
<MyTypography paragraph={paragraph} className="my-class" />;
<Typography paragraph sx={{ marginBottom: "32px" }} />;
<MyTypography paragraph sx={{ marginBottom: "32px" }} />;
<Typography paragraph sx={{ mb: "32px" }} />;
<MyTypography paragraph sx={{ mb: "32px" }} />;
<Typography paragraph sx={{ color: "black" }} />;
<MyTypography paragraph sx={{ color: "black" }} />;
