// Pure serializer: per-preset payload (baseline emit ⊕ user edits) → a
// self-contained `density.ts` source string. The generated file imports ONLY
// stable public API (`createTheme`) — the unreleased enhance*Density logic is
// baked in as data — so it can preview density in a production sandbox without
// upgrading @mui/material. It REQUIRES <CssBaseline /> in the consuming app:
// that's what materialises the `--mui-density-*` vars the overrides reference.

export interface ExportPresetPayload {
  name: 'compact' | 'normal' | 'comfort';
  /** the :root block — { '--mui-density-xxs': '2px', … } */
  scale: Record<string, string>;
  /** baseline ⊕ THIS preset's edits, flat-array slots, MuiCssBaseline excluded (scale is separate) */
  components: Record<string, { styleOverrides: Record<string, unknown> }>;
  /** the preset's own type reflow ⊕ this preset's user typography edits; {} when none */
  typography: Record<string, Record<string, string | number>>;
  /** this preset's user shape edits (borderRadius); {} when none */
  shape: Record<string, string | number>;
}

export interface ExportInput {
  presets: ExportPresetPayload[];
}

const IDENT = /^[A-Za-z_$][\w$]*$/;

const quote = (s: string) =>
  `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

const printKey = (k: string) => (IDENT.test(k) ? k : quote(k));

function printValue(value: unknown, indent: string): string {
  if (typeof value === 'function') {
    // fn matchers print verbatim — self-contained arrows reading ownerState only
    return value.toString();
  }
  if (typeof value === 'string') {
    return quote(value);
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value)) {
    // layered slots may carry an undefined preset layer — skip, same semantics
    const items = value.filter((v) => v !== undefined && v !== null);
    if (items.length === 0) {
      return '[]';
    }
    const inner = `${indent}  `;
    return `[\n${items.map((v) => `${inner}${printValue(v, inner)}`).join(',\n')},\n${indent}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) {
      return '{}';
    }
    const inner = `${indent}  `;
    return `{\n${entries
      .map(([k, v]) => `${inner}${printKey(k)}: ${printValue(v, inner)}`)
      .join(',\n')},\n${indent}}`;
  }
  return 'undefined';
}

export function buildExportSource(input: ExportInput): string {
  const presetConsts = input.presets
    .map(
      (p) =>
        `const ${p.name} = {\n` +
        `  scale: ${printValue(p.scale, '  ')},\n` +
        `  components: ${printValue(p.components, '  ')},\n` +
        `  typography: ${printValue(p.typography, '  ')},\n` +
        `  shape: ${printValue(p.shape, '  ')},\n` +
        `};`,
    )
    .join('\n\n');

  return `// density.ts — generated by the density playground.
// Preview MUI density WITHOUT upgrading @mui/material — the unreleased preset
// logic is inlined as data; only stable public API is imported.
//
// REQUIRES <CssBaseline /> in the consuming app — it materialises the
// --mui-density-* vars these overrides reference. Without it the refs resolve
// to nothing and density silently does not apply.
//
// Usage:
//   const theme = compactDensity(createTheme({ /* your options */ }));
//   <ThemeProvider theme={theme}><CssBaseline />…</ThemeProvider>
import { createTheme } from '@mui/material/styles';
import type { Theme } from '@mui/material/styles';

type AnyRecord = Record<string, any>;

// Per-preset payload, baked at export time — each preset carries ITS OWN
// playground edits (the playground keeps one override workspace per preset):
//   scale      → :root { --mui-density-*: <px> } (via MuiCssBaseline)
//   components → preset baseline emissions ⊕ that preset's edits (flat-array slots)
//   typography → the preset's own type reflow ⊕ that preset's typography edits
//   shape      → that preset's shape edits (borderRadius)
${presetConsts}

function mergeTypography(base: AnyRecord, patch: AnyRecord): AnyRecord {
  const out: AnyRecord = { ...base };
  for (const [variant, styles] of Object.entries(patch)) {
    out[variant] = { ...(out[variant] as AnyRecord), ...(styles as AnyRecord) };
  }
  return out;
}

function enhance(
  theme: Theme,
  p: {
    scale: Record<string, string>;
    components: AnyRecord;
    typography: AnyRecord;
    shape: AnyRecord;
  },
): Theme {
  const components: AnyRecord = { ...(theme.components as AnyRecord) };

  // 1) scale → :root via MuiCssBaseline (needs <CssBaseline/>), layer-preserving
  const baseline = components.MuiCssBaseline?.styleOverrides;
  const baselineObj: AnyRecord = baseline && typeof baseline === 'object' ? baseline : {};
  components.MuiCssBaseline = {
    ...components.MuiCssBaseline,
    styleOverrides: {
      ...baselineObj,
      ':root': { ...(baselineObj[':root'] as AnyRecord), ...p.scale },
    },
  };

  // 2) component overrides — flat array-form slot merge (density wins by order,
  //    the app's own styleOverrides/variants are kept as the leading layer).
  //    NEVER deepmerge here: createTheme(theme, {components}) would replace the
  //    preset's variants arrays.
  for (const [name, def] of Object.entries(p.components)) {
    const prev: AnyRecord = components[name] ?? {};
    const slots: AnyRecord = { ...prev.styleOverrides };
    for (const [slot, layer] of Object.entries((def as AnyRecord).styleOverrides)) {
      const layers = Array.isArray(layer) ? layer : [layer];
      slots[slot] = [prev.styleOverrides?.[slot], ...layers].filter(Boolean);
    }
    components[name] = { ...prev, styleOverrides: slots };
  }

  return createTheme({
    ...theme,
    typography: mergeTypography(theme.typography as AnyRecord, p.typography),
    shape: { ...theme.shape, ...p.shape },
    components,
  } as AnyRecord);
}

export const compactDensity = (theme: Theme) => enhance(theme, compact);
export const normalDensity = (theme: Theme) => enhance(theme, normal);
export const comfortDensity = (theme: Theme) => enhance(theme, comfort);
`;
}
