// Pure serializer: per-preset payload (baseline emit ⊕ user edits) → a
// self-contained `density.ts` source string. The generated file imports ONLY
// stable public API (`createTheme`) — the unreleased enhance*Density logic is
// baked in as data — so it can preview density in a production sandbox without
// upgrading @mui/material. The baked overrides reference `--mui-density-*`
// vars; a CSS-vars theme materialises them through its own stylesheet channel
// (ThemeProvider renders `generateStyleSheets`), a static theme needs
// <CssBaseline /> for the MuiCssBaseline fallback.

export interface ExportPresetPayload {
  name: 'compact' | 'normal' | 'comfort';
  /** the :root block — { '--mui-density-xxs': '2px', … } */
  scale: Record<string, string>;
  /** baseline ⊕ THIS preset's edits, flat-array slots, MuiCssBaseline excluded (scale is separate) */
  components: Record<string, { styleOverrides: Record<string, unknown> }>;
  /** the preset's own type reflow ⊕ this preset's user typography edits; {} when none */
  typography: Record<string, Record<string, unknown>>;
  /** this preset's user shape edits (borderRadius); {} when none */
  shape: Record<string, unknown>;
}

export interface ExportInput {
  presets: ExportPresetPayload[];
}

// Serialization markers set by exportPayload so the generated file can annotate
// which parts came from playground edits (vs the preset baseline). Both are
// STRIPPED/UNWRAPPED at print time — they never reach the generated output as data.
/** marks an appended slot LAYER as user edits → wrapped in begin/end comments */
export const USER_LAYER_KEY = '__densityUserOverrideLayer';
/** wraps a user-edited LEAF value → printed with a trailing `// playground edit` */
export const USER_VALUE_KEY = '__densityUserOverrideValue';

const isUserLayer = (v: unknown): v is Record<string, unknown> =>
  Boolean(v) && typeof v === 'object' && (v as Record<string, unknown>)[USER_LAYER_KEY] === true;

const asUserValue = (v: unknown): unknown =>
  v && typeof v === 'object' && USER_VALUE_KEY in (v as Record<string, unknown>)
    ? (v as Record<string, unknown>)[USER_VALUE_KEY]
    : undefined;

const IDENT = /^[A-Za-z_$][\w$]*$/;

const quote = (s: string) =>
  `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

const printKey = (k: string) => (IDENT.test(k) ? k : quote(k));

function printValue(value: unknown, indent: string): string {
  if (typeof value === 'function') {
    // fn matchers print verbatim — self-contained arrows reading ownerState only
    return value.toString();
  }
  if (typeof value === 'string') {
    return quote(value);
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value)) {
    // layered slots may carry an undefined preset layer — skip, same semantics
    const items = value.filter((v) => v !== undefined && v !== null);
    if (items.length === 0) {
      return '[]';
    }
    const inner = `${indent}  `;
    const lines = items.map((v) => {
      if (isUserLayer(v)) {
        return (
          `${inner}// ─── user overrides (playground edits) — appended layer, wins by order ───\n` +
          `${inner}${printValue(v, inner)},\n` +
          `${inner}// ─── end user overrides ───`
        );
      }
      return `${inner}${printValue(v, inner)},`;
    });
    return `[\n${lines.join('\n')}\n${indent}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([k, v]) => v !== undefined && k !== USER_LAYER_KEY,
    );
    if (entries.length === 0) {
      return '{}';
    }
    const inner = `${indent}  `;
    const lines = entries.map(([k, v]) => {
      const userValue = asUserValue(v);
      if (userValue !== undefined) {
        return `${inner}${printKey(k)}: ${printValue(userValue, inner)}, // playground edit`;
      }
      return `${inner}${printKey(k)}: ${printValue(v, inner)},`;
    });
    return `{\n${lines.join('\n')}\n${indent}}`;
  }
  return 'undefined';
}

export function buildExportSource(input: ExportInput): string {
  const presetConsts = input.presets
    .map(
      (p) =>
        `const ${p.name} = {\n` +
        `  scale: ${printValue(p.scale, '  ')},\n` +
        `  components: ${printValue(p.components, '  ')},\n` +
        `  typography: ${printValue(p.typography, '  ')},\n` +
        `  shape: ${printValue(p.shape, '  ')},\n` +
        `};`,
    )
    .join('\n\n');

  return `// density.ts — generated by the density playground.
// Preview MUI density WITHOUT upgrading @mui/material — the unreleased preset
// logic is inlined as data; only stable public API is imported.
//
// The overrides reference --mui-density-* vars. With a CSS-vars theme
// (createTheme({ cssVariables: true })) they ship on the theme's own stylesheet
// channel — ThemeProvider alone is enough. With a static theme they fall back
// to MuiCssBaseline, so <CssBaseline /> is REQUIRED there; without it the refs
// resolve to nothing and density silently does not apply.
//
// Usage:
//   const theme = enhanceCompactDensity(createTheme({ /* your options */ }));
//   <ThemeProvider theme={theme}>…</ThemeProvider>
import { createTheme } from '@mui/material/styles';
import type { Theme } from '@mui/material/styles';

type AnyRecord = Record<string, any>;

// Per-preset payload, baked at export time — each preset carries ITS OWN
// playground edits (the playground keeps one override workspace per preset):
//   scale      → :root { --mui-density-*: <px> } (theme stylesheet channel, or
//                MuiCssBaseline fallback for static themes)
//   components → preset baseline emissions ⊕ that preset's edits (flat-array slots)
//   typography → the preset's own type reflow ⊕ that preset's typography edits
//   shape      → that preset's shape edits (borderRadius)
// Playground edits are marked inline: appended slot layers sit between
// "user overrides" comments; edited token leaves carry a "playground edit" tag.
${presetConsts}

function mergeTypography(base: AnyRecord, patch: AnyRecord): AnyRecord {
  const out: AnyRecord = { ...base };
  for (const [variant, styles] of Object.entries(patch)) {
    out[variant] = { ...(out[variant] as AnyRecord), ...(styles as AnyRecord) };
  }
  return out;
}

function enhance(
  theme: Theme,
  p: {
    scale: Record<string, string>;
    components: AnyRecord;
    typography: AnyRecord;
    shape: AnyRecord;
  },
): Theme {
  const components: AnyRecord = { ...(theme.components as AnyRecord) };

  // 1) scale → :root. Static theme: MuiCssBaseline fallback (needs <CssBaseline/>),
  //    layer-preserving. CSS-vars theme: appended onto the theme's own stylesheet
  //    channel after createTheme (below) — no CssBaseline involved.
  if (!(theme as AnyRecord).vars) {
    const baseline = components.MuiCssBaseline?.styleOverrides;
    const baselineObj: AnyRecord = baseline && typeof baseline === 'object' ? baseline : {};
    components.MuiCssBaseline = {
      ...components.MuiCssBaseline,
      styleOverrides: {
        ...baselineObj,
        ':root': { ...(baselineObj[':root'] as AnyRecord), ...p.scale },
      },
    };
  }

  // 2) component overrides — flat array-form slot merge (density wins by order,
  //    the app's own styleOverrides/variants are kept as the leading layer).
  //    NEVER deepmerge here: createTheme(theme, {components}) would replace the
  //    preset's variants arrays.
  for (const [name, def] of Object.entries(p.components)) {
    const prev: AnyRecord = components[name] ?? {};
    const slots: AnyRecord = { ...prev.styleOverrides };
    for (const [slot, layer] of Object.entries((def as AnyRecord).styleOverrides)) {
      const layers = Array.isArray(layer) ? layer : [layer];
      slots[slot] = [prev.styleOverrides?.[slot], ...layers].filter(Boolean);
    }
    components[name] = { ...prev, styleOverrides: slots };
  }

  const result = createTheme({
    ...theme,
    typography: mergeTypography(theme.typography as AnyRecord, p.typography),
    shape: { ...theme.shape, ...p.shape },
    components,
  } as AnyRecord) as AnyRecord;

  // 3) CSS-vars theme: ride the theme's own vars channel — ThemeProvider renders
  //    generateStyleSheets, same as the palette vars. Wrap generateThemeVars too:
  //    the provider rebuilds theme.vars from it and would drop vars.density.
  if (result.vars) {
    const refs = Object.fromEntries(
      Object.keys(p.scale).map((name) => [name.split('-density-')[1], 'var(' + name + ')']),
    );
    result.vars = { ...result.vars, density: refs };
    const prevThemeVars = result.generateThemeVars;
    result.generateThemeVars = () => ({
      ...(prevThemeVars ? prevThemeVars() : {}),
      density: refs,
    });
    const prevStyleSheets = result.generateStyleSheets;
    result.generateStyleSheets = () => [
      ...(prevStyleSheets ? prevStyleSheets() : []),
      { [result.rootSelector || ':root']: p.scale },
    ];
  }

  return result as Theme;
}

export function enhanceCompactDensity(theme: Theme): Theme {
  return enhance(theme, compact);
}
export function enhanceNormalDensity(theme: Theme): Theme {
  return enhance(theme, normal);
}
export function enhanceComfortDensity(theme: Theme): Theme {
  return enhance(theme, comfort);
}
`;
}
