// flow-typed signature: 1aac9de71c8bf1030f23ade51f2a2573
// flow-typed version: <<STUB>>/babel-plugin-preval_v^1.4.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-preval'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-preval' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-preval/dist/get-replacement' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/dist/macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/dist/object-to-ast' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/macro' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-preval/dist/get-replacement.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/get-replacement'>;
}
declare module 'babel-plugin-preval/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/index'>;
}
declare module 'babel-plugin-preval/dist/macro.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/macro'>;
}
declare module 'babel-plugin-preval/dist/object-to-ast.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/object-to-ast'>;
}
declare module 'babel-plugin-preval/macro.js' {
  declare module.exports: $Exports<'babel-plugin-preval/macro'>;
}
