// flow-typed signature: e112f9bf71fad028ed266ca19670a1e4
// flow-typed version: <<STUB>>/babel-loader_v^7.1.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-loader/lib/fs-cache' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/index' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/resolve-rc' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/utils/exists' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/utils/read' {
  declare module.exports: any;
}

declare module 'babel-loader/lib/utils/relative' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-loader/lib/fs-cache.js' {
  declare module.exports: $Exports<'babel-loader/lib/fs-cache'>;
}
declare module 'babel-loader/lib/index.js' {
  declare module.exports: $Exports<'babel-loader/lib/index'>;
}
declare module 'babel-loader/lib/resolve-rc.js' {
  declare module.exports: $Exports<'babel-loader/lib/resolve-rc'>;
}
declare module 'babel-loader/lib/utils/exists.js' {
  declare module.exports: $Exports<'babel-loader/lib/utils/exists'>;
}
declare module 'babel-loader/lib/utils/read.js' {
  declare module.exports: $Exports<'babel-loader/lib/utils/read'>;
}
declare module 'babel-loader/lib/utils/relative.js' {
  declare module.exports: $Exports<'babel-loader/lib/utils/relative'>;
}
