// flow-typed signature: 6ba3e6412434a21f3739aa6771f9285d
// flow-typed version: <<STUB>>/babel-plugin-react-remove-properties_v^0.2.5/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-remove-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-remove-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-remove-properties/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-remove-properties/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-remove-properties/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-remove-properties/lib/index'>;
}
declare module 'babel-plugin-react-remove-properties/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-remove-properties/src/index'>;
}
