// flow-typed signature: e0c2fbfd0aafe714c19058869ad4d85d
// flow-typed version: <<STUB>>/babel-plugin-transform-object-assign_v^6.22.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-object-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-object-assign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-object-assign/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-object-assign/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-object-assign/lib/index'>;
}
