// flow-typed signature: b6942c11ea7d084bdff334df0924c0c4
// flow-typed version: <<STUB>>/babel-plugin-transform-react-remove-prop-types_v^0.4.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-remove-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-remove-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-remove-prop-types/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-remove-prop-types/lib/isAnnotatedForRemoval' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-remove-prop-types/lib/isStatelessComponent' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-remove-prop-types/lib/remove' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-remove-prop-types/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-remove-prop-types/src/isAnnotatedForRemoval' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-remove-prop-types/src/isStatelessComponent' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-react-remove-prop-types/src/remove' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-remove-prop-types/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/lib/index'>;
}
declare module 'babel-plugin-transform-react-remove-prop-types/lib/isAnnotatedForRemoval.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/lib/isAnnotatedForRemoval'>;
}
declare module 'babel-plugin-transform-react-remove-prop-types/lib/isStatelessComponent.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/lib/isStatelessComponent'>;
}
declare module 'babel-plugin-transform-react-remove-prop-types/lib/remove.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/lib/remove'>;
}
declare module 'babel-plugin-transform-react-remove-prop-types/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/src/index'>;
}
declare module 'babel-plugin-transform-react-remove-prop-types/src/isAnnotatedForRemoval.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/src/isAnnotatedForRemoval'>;
}
declare module 'babel-plugin-transform-react-remove-prop-types/src/isStatelessComponent.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/src/isStatelessComponent'>;
}
declare module 'babel-plugin-transform-react-remove-prop-types/src/remove.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-remove-prop-types/src/remove'>;
}
