// flow-typed signature: bf1b389c8c545a6aa1dfcebb35bdf68b
// flow-typed version: <<STUB>>/doctrine_v^2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'doctrine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'doctrine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'doctrine/lib/doctrine' {
  declare module.exports: any;
}

declare module 'doctrine/lib/typed' {
  declare module.exports: any;
}

declare module 'doctrine/lib/utility' {
  declare module.exports: any;
}

// Filename aliases
declare module 'doctrine/lib/doctrine.js' {
  declare module.exports: $Exports<'doctrine/lib/doctrine'>;
}
declare module 'doctrine/lib/typed.js' {
  declare module.exports: $Exports<'doctrine/lib/typed'>;
}
declare module 'doctrine/lib/utility.js' {
  declare module.exports: $Exports<'doctrine/lib/utility'>;
}
