// flow-typed signature: 03a0ec6ab7f8100e49be3b9f7c76388d
// flow-typed version: <<STUB>>/eslint-plugin-material-ui_vfile:packages/eslint-plugin-material-ui/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-material-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-material-ui/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-material-ui/lib/rules/docgen-ignore-before-comment' {
  declare module.exports: any;
}

declare module 'eslint-plugin-material-ui/tests/lib/rules/docgen-ignore-before-comment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-material-ui/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-material-ui/lib/index'>;
}
declare module 'eslint-plugin-material-ui/lib/rules/docgen-ignore-before-comment.js' {
  declare module.exports: $Exports<'eslint-plugin-material-ui/lib/rules/docgen-ignore-before-comment'>;
}
declare module 'eslint-plugin-material-ui/tests/lib/rules/docgen-ignore-before-comment.js' {
  declare module.exports: $Exports<'eslint-plugin-material-ui/tests/lib/rules/docgen-ignore-before-comment'>;
}
