// flow-typed signature: 056a7db6243ffea1f3e9261563b92a66
// flow-typed version: <<STUB>>/fs-extra_v^4.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-extra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-extra/lib/copy-sync/copy-file-sync' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/copy-sync/copy-sync' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/copy-sync/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/copy/copy' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/copy/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/copy/ncp' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/empty/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/ensure/file' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/ensure/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/ensure/link' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/ensure/symlink-paths' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/ensure/symlink-type' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/ensure/symlink' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/fs/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/json/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/json/jsonfile' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/json/output-json-sync' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/json/output-json' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/mkdirs/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/mkdirs/mkdirs-sync' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/mkdirs/mkdirs' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/mkdirs/win32' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/move-sync/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/move/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/output/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/path-exists/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/remove/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/remove/rimraf' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/util/assign' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/util/buffer' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/util/utimes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-extra/lib/copy-sync/copy-file-sync.js' {
  declare module.exports: $Exports<'fs-extra/lib/copy-sync/copy-file-sync'>;
}
declare module 'fs-extra/lib/copy-sync/copy-sync.js' {
  declare module.exports: $Exports<'fs-extra/lib/copy-sync/copy-sync'>;
}
declare module 'fs-extra/lib/copy-sync/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/copy-sync/index'>;
}
declare module 'fs-extra/lib/copy/copy.js' {
  declare module.exports: $Exports<'fs-extra/lib/copy/copy'>;
}
declare module 'fs-extra/lib/copy/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/copy/index'>;
}
declare module 'fs-extra/lib/copy/ncp.js' {
  declare module.exports: $Exports<'fs-extra/lib/copy/ncp'>;
}
declare module 'fs-extra/lib/empty/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/empty/index'>;
}
declare module 'fs-extra/lib/ensure/file.js' {
  declare module.exports: $Exports<'fs-extra/lib/ensure/file'>;
}
declare module 'fs-extra/lib/ensure/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/ensure/index'>;
}
declare module 'fs-extra/lib/ensure/link.js' {
  declare module.exports: $Exports<'fs-extra/lib/ensure/link'>;
}
declare module 'fs-extra/lib/ensure/symlink-paths.js' {
  declare module.exports: $Exports<'fs-extra/lib/ensure/symlink-paths'>;
}
declare module 'fs-extra/lib/ensure/symlink-type.js' {
  declare module.exports: $Exports<'fs-extra/lib/ensure/symlink-type'>;
}
declare module 'fs-extra/lib/ensure/symlink.js' {
  declare module.exports: $Exports<'fs-extra/lib/ensure/symlink'>;
}
declare module 'fs-extra/lib/fs/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/fs/index'>;
}
declare module 'fs-extra/lib/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/index'>;
}
declare module 'fs-extra/lib/json/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/json/index'>;
}
declare module 'fs-extra/lib/json/jsonfile.js' {
  declare module.exports: $Exports<'fs-extra/lib/json/jsonfile'>;
}
declare module 'fs-extra/lib/json/output-json-sync.js' {
  declare module.exports: $Exports<'fs-extra/lib/json/output-json-sync'>;
}
declare module 'fs-extra/lib/json/output-json.js' {
  declare module.exports: $Exports<'fs-extra/lib/json/output-json'>;
}
declare module 'fs-extra/lib/mkdirs/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/mkdirs/index'>;
}
declare module 'fs-extra/lib/mkdirs/mkdirs-sync.js' {
  declare module.exports: $Exports<'fs-extra/lib/mkdirs/mkdirs-sync'>;
}
declare module 'fs-extra/lib/mkdirs/mkdirs.js' {
  declare module.exports: $Exports<'fs-extra/lib/mkdirs/mkdirs'>;
}
declare module 'fs-extra/lib/mkdirs/win32.js' {
  declare module.exports: $Exports<'fs-extra/lib/mkdirs/win32'>;
}
declare module 'fs-extra/lib/move-sync/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/move-sync/index'>;
}
declare module 'fs-extra/lib/move/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/move/index'>;
}
declare module 'fs-extra/lib/output/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/output/index'>;
}
declare module 'fs-extra/lib/path-exists/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/path-exists/index'>;
}
declare module 'fs-extra/lib/remove/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/remove/index'>;
}
declare module 'fs-extra/lib/remove/rimraf.js' {
  declare module.exports: $Exports<'fs-extra/lib/remove/rimraf'>;
}
declare module 'fs-extra/lib/util/assign.js' {
  declare module.exports: $Exports<'fs-extra/lib/util/assign'>;
}
declare module 'fs-extra/lib/util/buffer.js' {
  declare module.exports: $Exports<'fs-extra/lib/util/buffer'>;
}
declare module 'fs-extra/lib/util/utimes.js' {
  declare module.exports: $Exports<'fs-extra/lib/util/utimes'>;
}
