// flow-typed signature: ad39e77e95bf09b310ecfb6b679c33b6
// flow-typed version: <<STUB>>/hoist-non-react-statics_v^1.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hoist-non-react-statics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hoist-non-react-statics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hoist-non-react-statics/index' {
  declare module.exports: $Exports<'hoist-non-react-statics'>;
}
declare module 'hoist-non-react-statics/index.js' {
  declare module.exports: $Exports<'hoist-non-react-statics'>;
}
