// flow-typed signature: 9bd2f5b993607322e7a3be0033c41110
// flow-typed version: <<STUB>>/jss-rtl_v^0.2.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-rtl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-rtl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-rtl/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-rtl/lib/main.js' {
  declare module.exports: $Exports<'jss-rtl/lib/main'>;
}
