// flow-typed signature: a6e58619308bced8b9e9e486b6c55b30
// flow-typed version: <<STUB>>/karma_v^1.7.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma/common/stringify' {
  declare module.exports: any;
}

declare module 'karma/common/util' {
  declare module.exports: any;
}

declare module 'karma/config.tpl' {
  declare module.exports: any;
}

declare module 'karma/context/karma' {
  declare module.exports: any;
}

declare module 'karma/context/main' {
  declare module.exports: any;
}

declare module 'karma/gruntfile' {
  declare module.exports: any;
}

declare module 'karma/lib/browser_collection' {
  declare module.exports: any;
}

declare module 'karma/lib/browser_result' {
  declare module.exports: any;
}

declare module 'karma/lib/browser' {
  declare module.exports: any;
}

declare module 'karma/lib/cli' {
  declare module.exports: any;
}

declare module 'karma/lib/completion' {
  declare module.exports: any;
}

declare module 'karma/lib/config' {
  declare module.exports: any;
}

declare module 'karma/lib/constants' {
  declare module.exports: any;
}

declare module 'karma/lib/detached' {
  declare module.exports: any;
}

declare module 'karma/lib/emitter_wrapper' {
  declare module.exports: any;
}

declare module 'karma/lib/events' {
  declare module.exports: any;
}

declare module 'karma/lib/executor' {
  declare module.exports: any;
}

declare module 'karma/lib/file-list' {
  declare module.exports: any;
}

declare module 'karma/lib/file' {
  declare module.exports: any;
}

declare module 'karma/lib/helper' {
  declare module.exports: any;
}

declare module 'karma/lib/index' {
  declare module.exports: any;
}

declare module 'karma/lib/init' {
  declare module.exports: any;
}

declare module 'karma/lib/init/color_schemes' {
  declare module.exports: any;
}

declare module 'karma/lib/init/formatters' {
  declare module.exports: any;
}

declare module 'karma/lib/init/state_machine' {
  declare module.exports: any;
}

declare module 'karma/lib/launcher' {
  declare module.exports: any;
}

declare module 'karma/lib/launchers/base' {
  declare module.exports: any;
}

declare module 'karma/lib/launchers/capture_timeout' {
  declare module.exports: any;
}

declare module 'karma/lib/launchers/process' {
  declare module.exports: any;
}

declare module 'karma/lib/launchers/retry' {
  declare module.exports: any;
}

declare module 'karma/lib/logger' {
  declare module.exports: any;
}

declare module 'karma/lib/middleware/common' {
  declare module.exports: any;
}

declare module 'karma/lib/middleware/karma' {
  declare module.exports: any;
}

declare module 'karma/lib/middleware/proxy' {
  declare module.exports: any;
}

declare module 'karma/lib/middleware/runner' {
  declare module.exports: any;
}

declare module 'karma/lib/middleware/source_files' {
  declare module.exports: any;
}

declare module 'karma/lib/middleware/stopper' {
  declare module.exports: any;
}

declare module 'karma/lib/middleware/strip_host' {
  declare module.exports: any;
}

declare module 'karma/lib/plugin' {
  declare module.exports: any;
}

declare module 'karma/lib/preprocessor' {
  declare module.exports: any;
}

declare module 'karma/lib/reporter' {
  declare module.exports: any;
}

declare module 'karma/lib/reporters/base_color' {
  declare module.exports: any;
}

declare module 'karma/lib/reporters/base' {
  declare module.exports: any;
}

declare module 'karma/lib/reporters/dots_color' {
  declare module.exports: any;
}

declare module 'karma/lib/reporters/dots' {
  declare module.exports: any;
}

declare module 'karma/lib/reporters/multi' {
  declare module.exports: any;
}

declare module 'karma/lib/reporters/progress_color' {
  declare module.exports: any;
}

declare module 'karma/lib/reporters/progress' {
  declare module.exports: any;
}

declare module 'karma/lib/runner' {
  declare module.exports: any;
}

declare module 'karma/lib/server' {
  declare module.exports: any;
}

declare module 'karma/lib/stopper' {
  declare module.exports: any;
}

declare module 'karma/lib/temp_dir' {
  declare module.exports: any;
}

declare module 'karma/lib/url' {
  declare module.exports: any;
}

declare module 'karma/lib/watcher' {
  declare module.exports: any;
}

declare module 'karma/lib/web-server' {
  declare module.exports: any;
}

declare module 'karma/requirejs.config.tpl' {
  declare module.exports: any;
}

declare module 'karma/static/context' {
  declare module.exports: any;
}

declare module 'karma/static/debug' {
  declare module.exports: any;
}

declare module 'karma/static/karma' {
  declare module.exports: any;
}

declare module 'karma/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma/common/stringify.js' {
  declare module.exports: $Exports<'karma/common/stringify'>;
}
declare module 'karma/common/util.js' {
  declare module.exports: $Exports<'karma/common/util'>;
}
declare module 'karma/config.tpl.js' {
  declare module.exports: $Exports<'karma/config.tpl'>;
}
declare module 'karma/context/karma.js' {
  declare module.exports: $Exports<'karma/context/karma'>;
}
declare module 'karma/context/main.js' {
  declare module.exports: $Exports<'karma/context/main'>;
}
declare module 'karma/gruntfile.js' {
  declare module.exports: $Exports<'karma/gruntfile'>;
}
declare module 'karma/lib/browser_collection.js' {
  declare module.exports: $Exports<'karma/lib/browser_collection'>;
}
declare module 'karma/lib/browser_result.js' {
  declare module.exports: $Exports<'karma/lib/browser_result'>;
}
declare module 'karma/lib/browser.js' {
  declare module.exports: $Exports<'karma/lib/browser'>;
}
declare module 'karma/lib/cli.js' {
  declare module.exports: $Exports<'karma/lib/cli'>;
}
declare module 'karma/lib/completion.js' {
  declare module.exports: $Exports<'karma/lib/completion'>;
}
declare module 'karma/lib/config.js' {
  declare module.exports: $Exports<'karma/lib/config'>;
}
declare module 'karma/lib/constants.js' {
  declare module.exports: $Exports<'karma/lib/constants'>;
}
declare module 'karma/lib/detached.js' {
  declare module.exports: $Exports<'karma/lib/detached'>;
}
declare module 'karma/lib/emitter_wrapper.js' {
  declare module.exports: $Exports<'karma/lib/emitter_wrapper'>;
}
declare module 'karma/lib/events.js' {
  declare module.exports: $Exports<'karma/lib/events'>;
}
declare module 'karma/lib/executor.js' {
  declare module.exports: $Exports<'karma/lib/executor'>;
}
declare module 'karma/lib/file-list.js' {
  declare module.exports: $Exports<'karma/lib/file-list'>;
}
declare module 'karma/lib/file.js' {
  declare module.exports: $Exports<'karma/lib/file'>;
}
declare module 'karma/lib/helper.js' {
  declare module.exports: $Exports<'karma/lib/helper'>;
}
declare module 'karma/lib/index.js' {
  declare module.exports: $Exports<'karma/lib/index'>;
}
declare module 'karma/lib/init.js' {
  declare module.exports: $Exports<'karma/lib/init'>;
}
declare module 'karma/lib/init/color_schemes.js' {
  declare module.exports: $Exports<'karma/lib/init/color_schemes'>;
}
declare module 'karma/lib/init/formatters.js' {
  declare module.exports: $Exports<'karma/lib/init/formatters'>;
}
declare module 'karma/lib/init/state_machine.js' {
  declare module.exports: $Exports<'karma/lib/init/state_machine'>;
}
declare module 'karma/lib/launcher.js' {
  declare module.exports: $Exports<'karma/lib/launcher'>;
}
declare module 'karma/lib/launchers/base.js' {
  declare module.exports: $Exports<'karma/lib/launchers/base'>;
}
declare module 'karma/lib/launchers/capture_timeout.js' {
  declare module.exports: $Exports<'karma/lib/launchers/capture_timeout'>;
}
declare module 'karma/lib/launchers/process.js' {
  declare module.exports: $Exports<'karma/lib/launchers/process'>;
}
declare module 'karma/lib/launchers/retry.js' {
  declare module.exports: $Exports<'karma/lib/launchers/retry'>;
}
declare module 'karma/lib/logger.js' {
  declare module.exports: $Exports<'karma/lib/logger'>;
}
declare module 'karma/lib/middleware/common.js' {
  declare module.exports: $Exports<'karma/lib/middleware/common'>;
}
declare module 'karma/lib/middleware/karma.js' {
  declare module.exports: $Exports<'karma/lib/middleware/karma'>;
}
declare module 'karma/lib/middleware/proxy.js' {
  declare module.exports: $Exports<'karma/lib/middleware/proxy'>;
}
declare module 'karma/lib/middleware/runner.js' {
  declare module.exports: $Exports<'karma/lib/middleware/runner'>;
}
declare module 'karma/lib/middleware/source_files.js' {
  declare module.exports: $Exports<'karma/lib/middleware/source_files'>;
}
declare module 'karma/lib/middleware/stopper.js' {
  declare module.exports: $Exports<'karma/lib/middleware/stopper'>;
}
declare module 'karma/lib/middleware/strip_host.js' {
  declare module.exports: $Exports<'karma/lib/middleware/strip_host'>;
}
declare module 'karma/lib/plugin.js' {
  declare module.exports: $Exports<'karma/lib/plugin'>;
}
declare module 'karma/lib/preprocessor.js' {
  declare module.exports: $Exports<'karma/lib/preprocessor'>;
}
declare module 'karma/lib/reporter.js' {
  declare module.exports: $Exports<'karma/lib/reporter'>;
}
declare module 'karma/lib/reporters/base_color.js' {
  declare module.exports: $Exports<'karma/lib/reporters/base_color'>;
}
declare module 'karma/lib/reporters/base.js' {
  declare module.exports: $Exports<'karma/lib/reporters/base'>;
}
declare module 'karma/lib/reporters/dots_color.js' {
  declare module.exports: $Exports<'karma/lib/reporters/dots_color'>;
}
declare module 'karma/lib/reporters/dots.js' {
  declare module.exports: $Exports<'karma/lib/reporters/dots'>;
}
declare module 'karma/lib/reporters/multi.js' {
  declare module.exports: $Exports<'karma/lib/reporters/multi'>;
}
declare module 'karma/lib/reporters/progress_color.js' {
  declare module.exports: $Exports<'karma/lib/reporters/progress_color'>;
}
declare module 'karma/lib/reporters/progress.js' {
  declare module.exports: $Exports<'karma/lib/reporters/progress'>;
}
declare module 'karma/lib/runner.js' {
  declare module.exports: $Exports<'karma/lib/runner'>;
}
declare module 'karma/lib/server.js' {
  declare module.exports: $Exports<'karma/lib/server'>;
}
declare module 'karma/lib/stopper.js' {
  declare module.exports: $Exports<'karma/lib/stopper'>;
}
declare module 'karma/lib/temp_dir.js' {
  declare module.exports: $Exports<'karma/lib/temp_dir'>;
}
declare module 'karma/lib/url.js' {
  declare module.exports: $Exports<'karma/lib/url'>;
}
declare module 'karma/lib/watcher.js' {
  declare module.exports: $Exports<'karma/lib/watcher'>;
}
declare module 'karma/lib/web-server.js' {
  declare module.exports: $Exports<'karma/lib/web-server'>;
}
declare module 'karma/requirejs.config.tpl.js' {
  declare module.exports: $Exports<'karma/requirejs.config.tpl'>;
}
declare module 'karma/static/context.js' {
  declare module.exports: $Exports<'karma/static/context'>;
}
declare module 'karma/static/debug.js' {
  declare module.exports: $Exports<'karma/static/debug'>;
}
declare module 'karma/static/karma.js' {
  declare module.exports: $Exports<'karma/static/karma'>;
}
declare module 'karma/wallaby.js' {
  declare module.exports: $Exports<'karma/wallaby'>;
}
