// flow-typed signature: bf0bc73aee1f93d6360948db7f83ccc6
// flow-typed version: <<STUB>>/karma-browserstack-launcher_v^1.2.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-browserstack-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-browserstack-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-browserstack-launcher/browserstack-reporter' {
  declare module.exports: any;
}

declare module 'karma-browserstack-launcher/worker-manager' {
  declare module.exports: any;
}

declare module 'karma-browserstack-launcher/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-browserstack-launcher/browserstack-reporter.js' {
  declare module.exports: $Exports<'karma-browserstack-launcher/browserstack-reporter'>;
}
declare module 'karma-browserstack-launcher/index' {
  declare module.exports: $Exports<'karma-browserstack-launcher'>;
}
declare module 'karma-browserstack-launcher/index.js' {
  declare module.exports: $Exports<'karma-browserstack-launcher'>;
}
declare module 'karma-browserstack-launcher/worker-manager.js' {
  declare module.exports: $Exports<'karma-browserstack-launcher/worker-manager'>;
}
declare module 'karma-browserstack-launcher/worker.js' {
  declare module.exports: $Exports<'karma-browserstack-launcher/worker'>;
}
