// flow-typed signature: 6124cf3d1aea4bc0f1403294a2ea64fc
// flow-typed version: <<STUB>>/normalize-scroll-left_v^0.1.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-scroll-left'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-scroll-left' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'normalize-scroll-left/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'normalize-scroll-left/lib/main.js' {
  declare module.exports: $Exports<'normalize-scroll-left/lib/main'>;
}
