// flow-typed signature: b386e48b1853aa664d6343cd41d03a53
// flow-typed version: <<STUB>>/nyc_v^11.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nyc/bin/nyc' {
  declare module.exports: any;
}

declare module 'nyc/bin/wrap' {
  declare module.exports: any;
}

declare module 'nyc/lib/commands/instrument' {
  declare module.exports: any;
}

declare module 'nyc/lib/config-util' {
  declare module.exports: any;
}

declare module 'nyc/lib/hash' {
  declare module.exports: any;
}

declare module 'nyc/lib/instrumenters/istanbul' {
  declare module.exports: any;
}

declare module 'nyc/lib/instrumenters/noop' {
  declare module.exports: any;
}

declare module 'nyc/lib/process-args' {
  declare module.exports: any;
}

declare module 'nyc/lib/process' {
  declare module.exports: any;
}

declare module 'nyc/lib/self-coverage-helper' {
  declare module.exports: any;
}

declare module 'nyc/lib/source-maps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nyc/bin/nyc.js' {
  declare module.exports: $Exports<'nyc/bin/nyc'>;
}
declare module 'nyc/bin/wrap.js' {
  declare module.exports: $Exports<'nyc/bin/wrap'>;
}
declare module 'nyc/index' {
  declare module.exports: $Exports<'nyc'>;
}
declare module 'nyc/index.js' {
  declare module.exports: $Exports<'nyc'>;
}
declare module 'nyc/lib/commands/instrument.js' {
  declare module.exports: $Exports<'nyc/lib/commands/instrument'>;
}
declare module 'nyc/lib/config-util.js' {
  declare module.exports: $Exports<'nyc/lib/config-util'>;
}
declare module 'nyc/lib/hash.js' {
  declare module.exports: $Exports<'nyc/lib/hash'>;
}
declare module 'nyc/lib/instrumenters/istanbul.js' {
  declare module.exports: $Exports<'nyc/lib/instrumenters/istanbul'>;
}
declare module 'nyc/lib/instrumenters/noop.js' {
  declare module.exports: $Exports<'nyc/lib/instrumenters/noop'>;
}
declare module 'nyc/lib/process-args.js' {
  declare module.exports: $Exports<'nyc/lib/process-args'>;
}
declare module 'nyc/lib/process.js' {
  declare module.exports: $Exports<'nyc/lib/process'>;
}
declare module 'nyc/lib/self-coverage-helper.js' {
  declare module.exports: $Exports<'nyc/lib/self-coverage-helper'>;
}
declare module 'nyc/lib/source-maps.js' {
  declare module.exports: $Exports<'nyc/lib/source-maps'>;
}
