// flow-typed signature: 4b3bae0be78991c8635448b8e5673a21
// flow-typed version: <<STUB>>/prismjs_v^1.6.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prismjs/components/prism-abap' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-abap.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-actionscript' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-actionscript.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ada' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ada.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-apacheconf' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-apacheconf.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-apl' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-apl.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-applescript' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-applescript.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-asciidoc' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-asciidoc.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-aspnet' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-aspnet.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-autohotkey' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-autohotkey.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-autoit' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-autoit.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-bash' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-bash.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-basic' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-basic.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-batch' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-batch.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-bison' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-bison.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-brainfuck' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-brainfuck.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-bro' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-bro.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-c' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-c.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-clike' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-clike.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-coffeescript' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-coffeescript.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-core' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-core.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-cpp' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-cpp.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-crystal' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-crystal.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-csharp' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-csharp.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-css-extras' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-css-extras.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-css' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-css.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-d' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-d.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-dart' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-dart.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-diff' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-diff.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-docker' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-docker.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-eiffel' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-eiffel.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-elixir' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-elixir.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-erlang' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-erlang.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-fortran' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-fortran.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-fsharp' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-fsharp.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-gherkin' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-gherkin.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-git' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-git.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-glsl' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-glsl.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-go' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-go.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-graphql' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-graphql.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-groovy' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-groovy.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-haml' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-haml.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-handlebars' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-handlebars.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-haskell' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-haskell.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-haxe' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-haxe.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-http' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-http.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-icon' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-icon.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-inform7' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-inform7.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ini' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ini.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-j' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-j.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-jade' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-jade.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-java' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-java.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-javascript' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-javascript.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-jolie' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-jolie.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-json' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-json.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-jsx' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-jsx.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-julia' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-julia.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-keyman' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-keyman.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-kotlin' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-kotlin.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-latex' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-latex.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-less' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-less.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-livescript' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-livescript.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-lolcode' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-lolcode.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-lua' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-lua.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-makefile' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-makefile.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-markdown' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-markdown.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-markup' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-markup.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-matlab' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-matlab.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-mel' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-mel.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-mizar' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-mizar.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-monkey' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-monkey.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nasm' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nasm.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nginx' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nginx.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nim' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nim.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nix' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nix.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nsis' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-nsis.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-objectivec' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-objectivec.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ocaml' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ocaml.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-oz' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-oz.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-parigp' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-parigp.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-parser' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-parser.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-pascal' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-pascal.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-perl' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-perl.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-php-extras' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-php-extras.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-php' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-php.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-powershell' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-powershell.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-processing' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-processing.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-prolog' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-prolog.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-properties' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-properties.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-protobuf' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-protobuf.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-puppet' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-puppet.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-pure' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-pure.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-python' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-python.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-q' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-q.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-qore' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-qore.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-r' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-r.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-reason' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-reason.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-rest' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-rest.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-rip' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-rip.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-roboconf' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-roboconf.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ruby' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-ruby.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-rust' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-rust.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-sas' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-sas.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-sass' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-sass.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-scala' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-scala.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-scheme' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-scheme.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-scss' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-scss.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-smalltalk' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-smalltalk.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-smarty' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-smarty.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-sql' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-sql.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-stylus' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-stylus.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-swift' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-swift.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-tcl' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-tcl.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-textile' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-textile.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-twig' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-twig.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-typescript' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-typescript.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-verilog' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-verilog.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-vhdl' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-vhdl.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-vim' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-vim.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-wiki' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-wiki.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-xojo' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-xojo.min' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-yaml' {
  declare module.exports: any;
}

declare module 'prismjs/components/prism-yaml.min' {
  declare module.exports: any;
}

declare module 'prismjs/examples' {
  declare module.exports: any;
}

declare module 'prismjs/gulpfile' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/autolinker/prism-autolinker' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/autolinker/prism-autolinker.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/autoloader/prism-autoloader' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/autoloader/prism-autoloader.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/command-line/prism-command-line' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/command-line/prism-command-line.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/custom-class/prism-custom-class' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/custom-class/prism-custom-class.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/file-highlight/prism-file-highlight' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/file-highlight/prism-file-highlight.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/highlight-keywords/prism-highlight-keywords' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/highlight-keywords/prism-highlight-keywords.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/ie8/prism-ie8' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/ie8/prism-ie8.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/jsonp-highlight/prism-jsonp-highlight' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/jsonp-highlight/prism-jsonp-highlight.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/keep-markup/prism-keep-markup' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/keep-markup/prism-keep-markup.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/line-highlight/prism-line-highlight' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/line-highlight/prism-line-highlight.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/line-numbers/prism-line-numbers' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/line-numbers/prism-line-numbers.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-angle/prism-previewer-angle' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-angle/prism-previewer-angle.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-base/prism-previewer-base' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-base/prism-previewer-base.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-color/prism-previewer-color' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-color/prism-previewer-color.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-easing/prism-previewer-easing' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-easing/prism-previewer-easing.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-gradient/prism-previewer-gradient' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-gradient/prism-previewer-gradient.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-time/prism-previewer-time' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/previewer-time/prism-previewer-time.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/remove-initial-line-feed/prism-remove-initial-line-feed' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/show-invisibles/prism-show-invisibles' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/show-invisibles/prism-show-invisibles.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/show-language/prism-show-language' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/show-language/prism-show-language.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/toolbar/prism-toolbar' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/toolbar/prism-toolbar.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/unescaped-markup/prism-unescaped-markup' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/unescaped-markup/prism-unescaped-markup.min' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/wpd/prism-wpd' {
  declare module.exports: any;
}

declare module 'prismjs/plugins/wpd/prism-wpd.min' {
  declare module.exports: any;
}

declare module 'prismjs/prism' {
  declare module.exports: any;
}

declare module 'prismjs/tests/helper/prism-loader' {
  declare module.exports: any;
}

declare module 'prismjs/tests/helper/test-case' {
  declare module.exports: any;
}

declare module 'prismjs/tests/helper/test-discovery' {
  declare module.exports: any;
}

declare module 'prismjs/tests/helper/token-stream-transformer' {
  declare module.exports: any;
}

declare module 'prismjs/tests/languages/asciidoc/entity_feature' {
  declare module.exports: any;
}

declare module 'prismjs/tests/languages/groovy/issue1049' {
  declare module.exports: any;
}

declare module 'prismjs/tests/languages/groovy/string-interpolation_feature' {
  declare module.exports: any;
}

declare module 'prismjs/tests/languages/handlebars/handlebars_in_markup_feature' {
  declare module.exports: any;
}

declare module 'prismjs/tests/languages/markup/entity_feature' {
  declare module.exports: any;
}

declare module 'prismjs/tests/languages/markup+php/php_in_markup_feature' {
  declare module.exports: any;
}

declare module 'prismjs/tests/languages/smarty/smarty_in_markup_feature' {
  declare module.exports: any;
}

declare module 'prismjs/tests/run-child' {
  declare module.exports: any;
}

declare module 'prismjs/tests/run' {
  declare module.exports: any;
}

declare module 'prismjs/tests/testrunner-tests' {
  declare module.exports: any;
}

declare module 'prismjs/vendor/FileSaver.min' {
  declare module.exports: any;
}

declare module 'prismjs/vendor/jszip.min' {
  declare module.exports: any;
}

declare module 'prismjs/vendor/promise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prismjs/components/prism-abap.js' {
  declare module.exports: $Exports<'prismjs/components/prism-abap'>;
}
declare module 'prismjs/components/prism-abap.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-abap.min'>;
}
declare module 'prismjs/components/prism-actionscript.js' {
  declare module.exports: $Exports<'prismjs/components/prism-actionscript'>;
}
declare module 'prismjs/components/prism-actionscript.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-actionscript.min'>;
}
declare module 'prismjs/components/prism-ada.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ada'>;
}
declare module 'prismjs/components/prism-ada.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ada.min'>;
}
declare module 'prismjs/components/prism-apacheconf.js' {
  declare module.exports: $Exports<'prismjs/components/prism-apacheconf'>;
}
declare module 'prismjs/components/prism-apacheconf.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-apacheconf.min'>;
}
declare module 'prismjs/components/prism-apl.js' {
  declare module.exports: $Exports<'prismjs/components/prism-apl'>;
}
declare module 'prismjs/components/prism-apl.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-apl.min'>;
}
declare module 'prismjs/components/prism-applescript.js' {
  declare module.exports: $Exports<'prismjs/components/prism-applescript'>;
}
declare module 'prismjs/components/prism-applescript.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-applescript.min'>;
}
declare module 'prismjs/components/prism-asciidoc.js' {
  declare module.exports: $Exports<'prismjs/components/prism-asciidoc'>;
}
declare module 'prismjs/components/prism-asciidoc.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-asciidoc.min'>;
}
declare module 'prismjs/components/prism-aspnet.js' {
  declare module.exports: $Exports<'prismjs/components/prism-aspnet'>;
}
declare module 'prismjs/components/prism-aspnet.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-aspnet.min'>;
}
declare module 'prismjs/components/prism-autohotkey.js' {
  declare module.exports: $Exports<'prismjs/components/prism-autohotkey'>;
}
declare module 'prismjs/components/prism-autohotkey.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-autohotkey.min'>;
}
declare module 'prismjs/components/prism-autoit.js' {
  declare module.exports: $Exports<'prismjs/components/prism-autoit'>;
}
declare module 'prismjs/components/prism-autoit.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-autoit.min'>;
}
declare module 'prismjs/components/prism-bash.js' {
  declare module.exports: $Exports<'prismjs/components/prism-bash'>;
}
declare module 'prismjs/components/prism-bash.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-bash.min'>;
}
declare module 'prismjs/components/prism-basic.js' {
  declare module.exports: $Exports<'prismjs/components/prism-basic'>;
}
declare module 'prismjs/components/prism-basic.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-basic.min'>;
}
declare module 'prismjs/components/prism-batch.js' {
  declare module.exports: $Exports<'prismjs/components/prism-batch'>;
}
declare module 'prismjs/components/prism-batch.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-batch.min'>;
}
declare module 'prismjs/components/prism-bison.js' {
  declare module.exports: $Exports<'prismjs/components/prism-bison'>;
}
declare module 'prismjs/components/prism-bison.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-bison.min'>;
}
declare module 'prismjs/components/prism-brainfuck.js' {
  declare module.exports: $Exports<'prismjs/components/prism-brainfuck'>;
}
declare module 'prismjs/components/prism-brainfuck.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-brainfuck.min'>;
}
declare module 'prismjs/components/prism-bro.js' {
  declare module.exports: $Exports<'prismjs/components/prism-bro'>;
}
declare module 'prismjs/components/prism-bro.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-bro.min'>;
}
declare module 'prismjs/components/prism-c.js' {
  declare module.exports: $Exports<'prismjs/components/prism-c'>;
}
declare module 'prismjs/components/prism-c.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-c.min'>;
}
declare module 'prismjs/components/prism-clike.js' {
  declare module.exports: $Exports<'prismjs/components/prism-clike'>;
}
declare module 'prismjs/components/prism-clike.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-clike.min'>;
}
declare module 'prismjs/components/prism-coffeescript.js' {
  declare module.exports: $Exports<'prismjs/components/prism-coffeescript'>;
}
declare module 'prismjs/components/prism-coffeescript.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-coffeescript.min'>;
}
declare module 'prismjs/components/prism-core.js' {
  declare module.exports: $Exports<'prismjs/components/prism-core'>;
}
declare module 'prismjs/components/prism-core.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-core.min'>;
}
declare module 'prismjs/components/prism-cpp.js' {
  declare module.exports: $Exports<'prismjs/components/prism-cpp'>;
}
declare module 'prismjs/components/prism-cpp.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-cpp.min'>;
}
declare module 'prismjs/components/prism-crystal.js' {
  declare module.exports: $Exports<'prismjs/components/prism-crystal'>;
}
declare module 'prismjs/components/prism-crystal.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-crystal.min'>;
}
declare module 'prismjs/components/prism-csharp.js' {
  declare module.exports: $Exports<'prismjs/components/prism-csharp'>;
}
declare module 'prismjs/components/prism-csharp.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-csharp.min'>;
}
declare module 'prismjs/components/prism-css-extras.js' {
  declare module.exports: $Exports<'prismjs/components/prism-css-extras'>;
}
declare module 'prismjs/components/prism-css-extras.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-css-extras.min'>;
}
declare module 'prismjs/components/prism-css.js' {
  declare module.exports: $Exports<'prismjs/components/prism-css'>;
}
declare module 'prismjs/components/prism-css.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-css.min'>;
}
declare module 'prismjs/components/prism-d.js' {
  declare module.exports: $Exports<'prismjs/components/prism-d'>;
}
declare module 'prismjs/components/prism-d.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-d.min'>;
}
declare module 'prismjs/components/prism-dart.js' {
  declare module.exports: $Exports<'prismjs/components/prism-dart'>;
}
declare module 'prismjs/components/prism-dart.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-dart.min'>;
}
declare module 'prismjs/components/prism-diff.js' {
  declare module.exports: $Exports<'prismjs/components/prism-diff'>;
}
declare module 'prismjs/components/prism-diff.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-diff.min'>;
}
declare module 'prismjs/components/prism-docker.js' {
  declare module.exports: $Exports<'prismjs/components/prism-docker'>;
}
declare module 'prismjs/components/prism-docker.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-docker.min'>;
}
declare module 'prismjs/components/prism-eiffel.js' {
  declare module.exports: $Exports<'prismjs/components/prism-eiffel'>;
}
declare module 'prismjs/components/prism-eiffel.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-eiffel.min'>;
}
declare module 'prismjs/components/prism-elixir.js' {
  declare module.exports: $Exports<'prismjs/components/prism-elixir'>;
}
declare module 'prismjs/components/prism-elixir.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-elixir.min'>;
}
declare module 'prismjs/components/prism-erlang.js' {
  declare module.exports: $Exports<'prismjs/components/prism-erlang'>;
}
declare module 'prismjs/components/prism-erlang.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-erlang.min'>;
}
declare module 'prismjs/components/prism-fortran.js' {
  declare module.exports: $Exports<'prismjs/components/prism-fortran'>;
}
declare module 'prismjs/components/prism-fortran.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-fortran.min'>;
}
declare module 'prismjs/components/prism-fsharp.js' {
  declare module.exports: $Exports<'prismjs/components/prism-fsharp'>;
}
declare module 'prismjs/components/prism-fsharp.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-fsharp.min'>;
}
declare module 'prismjs/components/prism-gherkin.js' {
  declare module.exports: $Exports<'prismjs/components/prism-gherkin'>;
}
declare module 'prismjs/components/prism-gherkin.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-gherkin.min'>;
}
declare module 'prismjs/components/prism-git.js' {
  declare module.exports: $Exports<'prismjs/components/prism-git'>;
}
declare module 'prismjs/components/prism-git.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-git.min'>;
}
declare module 'prismjs/components/prism-glsl.js' {
  declare module.exports: $Exports<'prismjs/components/prism-glsl'>;
}
declare module 'prismjs/components/prism-glsl.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-glsl.min'>;
}
declare module 'prismjs/components/prism-go.js' {
  declare module.exports: $Exports<'prismjs/components/prism-go'>;
}
declare module 'prismjs/components/prism-go.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-go.min'>;
}
declare module 'prismjs/components/prism-graphql.js' {
  declare module.exports: $Exports<'prismjs/components/prism-graphql'>;
}
declare module 'prismjs/components/prism-graphql.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-graphql.min'>;
}
declare module 'prismjs/components/prism-groovy.js' {
  declare module.exports: $Exports<'prismjs/components/prism-groovy'>;
}
declare module 'prismjs/components/prism-groovy.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-groovy.min'>;
}
declare module 'prismjs/components/prism-haml.js' {
  declare module.exports: $Exports<'prismjs/components/prism-haml'>;
}
declare module 'prismjs/components/prism-haml.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-haml.min'>;
}
declare module 'prismjs/components/prism-handlebars.js' {
  declare module.exports: $Exports<'prismjs/components/prism-handlebars'>;
}
declare module 'prismjs/components/prism-handlebars.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-handlebars.min'>;
}
declare module 'prismjs/components/prism-haskell.js' {
  declare module.exports: $Exports<'prismjs/components/prism-haskell'>;
}
declare module 'prismjs/components/prism-haskell.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-haskell.min'>;
}
declare module 'prismjs/components/prism-haxe.js' {
  declare module.exports: $Exports<'prismjs/components/prism-haxe'>;
}
declare module 'prismjs/components/prism-haxe.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-haxe.min'>;
}
declare module 'prismjs/components/prism-http.js' {
  declare module.exports: $Exports<'prismjs/components/prism-http'>;
}
declare module 'prismjs/components/prism-http.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-http.min'>;
}
declare module 'prismjs/components/prism-icon.js' {
  declare module.exports: $Exports<'prismjs/components/prism-icon'>;
}
declare module 'prismjs/components/prism-icon.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-icon.min'>;
}
declare module 'prismjs/components/prism-inform7.js' {
  declare module.exports: $Exports<'prismjs/components/prism-inform7'>;
}
declare module 'prismjs/components/prism-inform7.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-inform7.min'>;
}
declare module 'prismjs/components/prism-ini.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ini'>;
}
declare module 'prismjs/components/prism-ini.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ini.min'>;
}
declare module 'prismjs/components/prism-j.js' {
  declare module.exports: $Exports<'prismjs/components/prism-j'>;
}
declare module 'prismjs/components/prism-j.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-j.min'>;
}
declare module 'prismjs/components/prism-jade.js' {
  declare module.exports: $Exports<'prismjs/components/prism-jade'>;
}
declare module 'prismjs/components/prism-jade.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-jade.min'>;
}
declare module 'prismjs/components/prism-java.js' {
  declare module.exports: $Exports<'prismjs/components/prism-java'>;
}
declare module 'prismjs/components/prism-java.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-java.min'>;
}
declare module 'prismjs/components/prism-javascript.js' {
  declare module.exports: $Exports<'prismjs/components/prism-javascript'>;
}
declare module 'prismjs/components/prism-javascript.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-javascript.min'>;
}
declare module 'prismjs/components/prism-jolie.js' {
  declare module.exports: $Exports<'prismjs/components/prism-jolie'>;
}
declare module 'prismjs/components/prism-jolie.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-jolie.min'>;
}
declare module 'prismjs/components/prism-json.js' {
  declare module.exports: $Exports<'prismjs/components/prism-json'>;
}
declare module 'prismjs/components/prism-json.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-json.min'>;
}
declare module 'prismjs/components/prism-jsx.js' {
  declare module.exports: $Exports<'prismjs/components/prism-jsx'>;
}
declare module 'prismjs/components/prism-jsx.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-jsx.min'>;
}
declare module 'prismjs/components/prism-julia.js' {
  declare module.exports: $Exports<'prismjs/components/prism-julia'>;
}
declare module 'prismjs/components/prism-julia.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-julia.min'>;
}
declare module 'prismjs/components/prism-keyman.js' {
  declare module.exports: $Exports<'prismjs/components/prism-keyman'>;
}
declare module 'prismjs/components/prism-keyman.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-keyman.min'>;
}
declare module 'prismjs/components/prism-kotlin.js' {
  declare module.exports: $Exports<'prismjs/components/prism-kotlin'>;
}
declare module 'prismjs/components/prism-kotlin.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-kotlin.min'>;
}
declare module 'prismjs/components/prism-latex.js' {
  declare module.exports: $Exports<'prismjs/components/prism-latex'>;
}
declare module 'prismjs/components/prism-latex.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-latex.min'>;
}
declare module 'prismjs/components/prism-less.js' {
  declare module.exports: $Exports<'prismjs/components/prism-less'>;
}
declare module 'prismjs/components/prism-less.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-less.min'>;
}
declare module 'prismjs/components/prism-livescript.js' {
  declare module.exports: $Exports<'prismjs/components/prism-livescript'>;
}
declare module 'prismjs/components/prism-livescript.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-livescript.min'>;
}
declare module 'prismjs/components/prism-lolcode.js' {
  declare module.exports: $Exports<'prismjs/components/prism-lolcode'>;
}
declare module 'prismjs/components/prism-lolcode.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-lolcode.min'>;
}
declare module 'prismjs/components/prism-lua.js' {
  declare module.exports: $Exports<'prismjs/components/prism-lua'>;
}
declare module 'prismjs/components/prism-lua.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-lua.min'>;
}
declare module 'prismjs/components/prism-makefile.js' {
  declare module.exports: $Exports<'prismjs/components/prism-makefile'>;
}
declare module 'prismjs/components/prism-makefile.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-makefile.min'>;
}
declare module 'prismjs/components/prism-markdown.js' {
  declare module.exports: $Exports<'prismjs/components/prism-markdown'>;
}
declare module 'prismjs/components/prism-markdown.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-markdown.min'>;
}
declare module 'prismjs/components/prism-markup.js' {
  declare module.exports: $Exports<'prismjs/components/prism-markup'>;
}
declare module 'prismjs/components/prism-markup.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-markup.min'>;
}
declare module 'prismjs/components/prism-matlab.js' {
  declare module.exports: $Exports<'prismjs/components/prism-matlab'>;
}
declare module 'prismjs/components/prism-matlab.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-matlab.min'>;
}
declare module 'prismjs/components/prism-mel.js' {
  declare module.exports: $Exports<'prismjs/components/prism-mel'>;
}
declare module 'prismjs/components/prism-mel.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-mel.min'>;
}
declare module 'prismjs/components/prism-mizar.js' {
  declare module.exports: $Exports<'prismjs/components/prism-mizar'>;
}
declare module 'prismjs/components/prism-mizar.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-mizar.min'>;
}
declare module 'prismjs/components/prism-monkey.js' {
  declare module.exports: $Exports<'prismjs/components/prism-monkey'>;
}
declare module 'prismjs/components/prism-monkey.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-monkey.min'>;
}
declare module 'prismjs/components/prism-nasm.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nasm'>;
}
declare module 'prismjs/components/prism-nasm.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nasm.min'>;
}
declare module 'prismjs/components/prism-nginx.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nginx'>;
}
declare module 'prismjs/components/prism-nginx.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nginx.min'>;
}
declare module 'prismjs/components/prism-nim.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nim'>;
}
declare module 'prismjs/components/prism-nim.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nim.min'>;
}
declare module 'prismjs/components/prism-nix.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nix'>;
}
declare module 'prismjs/components/prism-nix.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nix.min'>;
}
declare module 'prismjs/components/prism-nsis.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nsis'>;
}
declare module 'prismjs/components/prism-nsis.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-nsis.min'>;
}
declare module 'prismjs/components/prism-objectivec.js' {
  declare module.exports: $Exports<'prismjs/components/prism-objectivec'>;
}
declare module 'prismjs/components/prism-objectivec.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-objectivec.min'>;
}
declare module 'prismjs/components/prism-ocaml.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ocaml'>;
}
declare module 'prismjs/components/prism-ocaml.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ocaml.min'>;
}
declare module 'prismjs/components/prism-oz.js' {
  declare module.exports: $Exports<'prismjs/components/prism-oz'>;
}
declare module 'prismjs/components/prism-oz.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-oz.min'>;
}
declare module 'prismjs/components/prism-parigp.js' {
  declare module.exports: $Exports<'prismjs/components/prism-parigp'>;
}
declare module 'prismjs/components/prism-parigp.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-parigp.min'>;
}
declare module 'prismjs/components/prism-parser.js' {
  declare module.exports: $Exports<'prismjs/components/prism-parser'>;
}
declare module 'prismjs/components/prism-parser.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-parser.min'>;
}
declare module 'prismjs/components/prism-pascal.js' {
  declare module.exports: $Exports<'prismjs/components/prism-pascal'>;
}
declare module 'prismjs/components/prism-pascal.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-pascal.min'>;
}
declare module 'prismjs/components/prism-perl.js' {
  declare module.exports: $Exports<'prismjs/components/prism-perl'>;
}
declare module 'prismjs/components/prism-perl.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-perl.min'>;
}
declare module 'prismjs/components/prism-php-extras.js' {
  declare module.exports: $Exports<'prismjs/components/prism-php-extras'>;
}
declare module 'prismjs/components/prism-php-extras.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-php-extras.min'>;
}
declare module 'prismjs/components/prism-php.js' {
  declare module.exports: $Exports<'prismjs/components/prism-php'>;
}
declare module 'prismjs/components/prism-php.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-php.min'>;
}
declare module 'prismjs/components/prism-powershell.js' {
  declare module.exports: $Exports<'prismjs/components/prism-powershell'>;
}
declare module 'prismjs/components/prism-powershell.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-powershell.min'>;
}
declare module 'prismjs/components/prism-processing.js' {
  declare module.exports: $Exports<'prismjs/components/prism-processing'>;
}
declare module 'prismjs/components/prism-processing.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-processing.min'>;
}
declare module 'prismjs/components/prism-prolog.js' {
  declare module.exports: $Exports<'prismjs/components/prism-prolog'>;
}
declare module 'prismjs/components/prism-prolog.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-prolog.min'>;
}
declare module 'prismjs/components/prism-properties.js' {
  declare module.exports: $Exports<'prismjs/components/prism-properties'>;
}
declare module 'prismjs/components/prism-properties.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-properties.min'>;
}
declare module 'prismjs/components/prism-protobuf.js' {
  declare module.exports: $Exports<'prismjs/components/prism-protobuf'>;
}
declare module 'prismjs/components/prism-protobuf.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-protobuf.min'>;
}
declare module 'prismjs/components/prism-puppet.js' {
  declare module.exports: $Exports<'prismjs/components/prism-puppet'>;
}
declare module 'prismjs/components/prism-puppet.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-puppet.min'>;
}
declare module 'prismjs/components/prism-pure.js' {
  declare module.exports: $Exports<'prismjs/components/prism-pure'>;
}
declare module 'prismjs/components/prism-pure.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-pure.min'>;
}
declare module 'prismjs/components/prism-python.js' {
  declare module.exports: $Exports<'prismjs/components/prism-python'>;
}
declare module 'prismjs/components/prism-python.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-python.min'>;
}
declare module 'prismjs/components/prism-q.js' {
  declare module.exports: $Exports<'prismjs/components/prism-q'>;
}
declare module 'prismjs/components/prism-q.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-q.min'>;
}
declare module 'prismjs/components/prism-qore.js' {
  declare module.exports: $Exports<'prismjs/components/prism-qore'>;
}
declare module 'prismjs/components/prism-qore.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-qore.min'>;
}
declare module 'prismjs/components/prism-r.js' {
  declare module.exports: $Exports<'prismjs/components/prism-r'>;
}
declare module 'prismjs/components/prism-r.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-r.min'>;
}
declare module 'prismjs/components/prism-reason.js' {
  declare module.exports: $Exports<'prismjs/components/prism-reason'>;
}
declare module 'prismjs/components/prism-reason.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-reason.min'>;
}
declare module 'prismjs/components/prism-rest.js' {
  declare module.exports: $Exports<'prismjs/components/prism-rest'>;
}
declare module 'prismjs/components/prism-rest.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-rest.min'>;
}
declare module 'prismjs/components/prism-rip.js' {
  declare module.exports: $Exports<'prismjs/components/prism-rip'>;
}
declare module 'prismjs/components/prism-rip.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-rip.min'>;
}
declare module 'prismjs/components/prism-roboconf.js' {
  declare module.exports: $Exports<'prismjs/components/prism-roboconf'>;
}
declare module 'prismjs/components/prism-roboconf.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-roboconf.min'>;
}
declare module 'prismjs/components/prism-ruby.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ruby'>;
}
declare module 'prismjs/components/prism-ruby.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-ruby.min'>;
}
declare module 'prismjs/components/prism-rust.js' {
  declare module.exports: $Exports<'prismjs/components/prism-rust'>;
}
declare module 'prismjs/components/prism-rust.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-rust.min'>;
}
declare module 'prismjs/components/prism-sas.js' {
  declare module.exports: $Exports<'prismjs/components/prism-sas'>;
}
declare module 'prismjs/components/prism-sas.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-sas.min'>;
}
declare module 'prismjs/components/prism-sass.js' {
  declare module.exports: $Exports<'prismjs/components/prism-sass'>;
}
declare module 'prismjs/components/prism-sass.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-sass.min'>;
}
declare module 'prismjs/components/prism-scala.js' {
  declare module.exports: $Exports<'prismjs/components/prism-scala'>;
}
declare module 'prismjs/components/prism-scala.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-scala.min'>;
}
declare module 'prismjs/components/prism-scheme.js' {
  declare module.exports: $Exports<'prismjs/components/prism-scheme'>;
}
declare module 'prismjs/components/prism-scheme.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-scheme.min'>;
}
declare module 'prismjs/components/prism-scss.js' {
  declare module.exports: $Exports<'prismjs/components/prism-scss'>;
}
declare module 'prismjs/components/prism-scss.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-scss.min'>;
}
declare module 'prismjs/components/prism-smalltalk.js' {
  declare module.exports: $Exports<'prismjs/components/prism-smalltalk'>;
}
declare module 'prismjs/components/prism-smalltalk.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-smalltalk.min'>;
}
declare module 'prismjs/components/prism-smarty.js' {
  declare module.exports: $Exports<'prismjs/components/prism-smarty'>;
}
declare module 'prismjs/components/prism-smarty.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-smarty.min'>;
}
declare module 'prismjs/components/prism-sql.js' {
  declare module.exports: $Exports<'prismjs/components/prism-sql'>;
}
declare module 'prismjs/components/prism-sql.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-sql.min'>;
}
declare module 'prismjs/components/prism-stylus.js' {
  declare module.exports: $Exports<'prismjs/components/prism-stylus'>;
}
declare module 'prismjs/components/prism-stylus.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-stylus.min'>;
}
declare module 'prismjs/components/prism-swift.js' {
  declare module.exports: $Exports<'prismjs/components/prism-swift'>;
}
declare module 'prismjs/components/prism-swift.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-swift.min'>;
}
declare module 'prismjs/components/prism-tcl.js' {
  declare module.exports: $Exports<'prismjs/components/prism-tcl'>;
}
declare module 'prismjs/components/prism-tcl.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-tcl.min'>;
}
declare module 'prismjs/components/prism-textile.js' {
  declare module.exports: $Exports<'prismjs/components/prism-textile'>;
}
declare module 'prismjs/components/prism-textile.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-textile.min'>;
}
declare module 'prismjs/components/prism-twig.js' {
  declare module.exports: $Exports<'prismjs/components/prism-twig'>;
}
declare module 'prismjs/components/prism-twig.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-twig.min'>;
}
declare module 'prismjs/components/prism-typescript.js' {
  declare module.exports: $Exports<'prismjs/components/prism-typescript'>;
}
declare module 'prismjs/components/prism-typescript.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-typescript.min'>;
}
declare module 'prismjs/components/prism-verilog.js' {
  declare module.exports: $Exports<'prismjs/components/prism-verilog'>;
}
declare module 'prismjs/components/prism-verilog.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-verilog.min'>;
}
declare module 'prismjs/components/prism-vhdl.js' {
  declare module.exports: $Exports<'prismjs/components/prism-vhdl'>;
}
declare module 'prismjs/components/prism-vhdl.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-vhdl.min'>;
}
declare module 'prismjs/components/prism-vim.js' {
  declare module.exports: $Exports<'prismjs/components/prism-vim'>;
}
declare module 'prismjs/components/prism-vim.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-vim.min'>;
}
declare module 'prismjs/components/prism-wiki.js' {
  declare module.exports: $Exports<'prismjs/components/prism-wiki'>;
}
declare module 'prismjs/components/prism-wiki.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-wiki.min'>;
}
declare module 'prismjs/components/prism-xojo.js' {
  declare module.exports: $Exports<'prismjs/components/prism-xojo'>;
}
declare module 'prismjs/components/prism-xojo.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-xojo.min'>;
}
declare module 'prismjs/components/prism-yaml.js' {
  declare module.exports: $Exports<'prismjs/components/prism-yaml'>;
}
declare module 'prismjs/components/prism-yaml.min.js' {
  declare module.exports: $Exports<'prismjs/components/prism-yaml.min'>;
}
declare module 'prismjs/examples.js' {
  declare module.exports: $Exports<'prismjs/examples'>;
}
declare module 'prismjs/gulpfile.js' {
  declare module.exports: $Exports<'prismjs/gulpfile'>;
}
declare module 'prismjs/plugins/autolinker/prism-autolinker.js' {
  declare module.exports: $Exports<'prismjs/plugins/autolinker/prism-autolinker'>;
}
declare module 'prismjs/plugins/autolinker/prism-autolinker.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/autolinker/prism-autolinker.min'>;
}
declare module 'prismjs/plugins/autoloader/prism-autoloader.js' {
  declare module.exports: $Exports<'prismjs/plugins/autoloader/prism-autoloader'>;
}
declare module 'prismjs/plugins/autoloader/prism-autoloader.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/autoloader/prism-autoloader.min'>;
}
declare module 'prismjs/plugins/command-line/prism-command-line.js' {
  declare module.exports: $Exports<'prismjs/plugins/command-line/prism-command-line'>;
}
declare module 'prismjs/plugins/command-line/prism-command-line.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/command-line/prism-command-line.min'>;
}
declare module 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.js' {
  declare module.exports: $Exports<'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard'>;
}
declare module 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.min'>;
}
declare module 'prismjs/plugins/custom-class/prism-custom-class.js' {
  declare module.exports: $Exports<'prismjs/plugins/custom-class/prism-custom-class'>;
}
declare module 'prismjs/plugins/custom-class/prism-custom-class.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/custom-class/prism-custom-class.min'>;
}
declare module 'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight.js' {
  declare module.exports: $Exports<'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight'>;
}
declare module 'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight.min'>;
}
declare module 'prismjs/plugins/file-highlight/prism-file-highlight.js' {
  declare module.exports: $Exports<'prismjs/plugins/file-highlight/prism-file-highlight'>;
}
declare module 'prismjs/plugins/file-highlight/prism-file-highlight.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/file-highlight/prism-file-highlight.min'>;
}
declare module 'prismjs/plugins/highlight-keywords/prism-highlight-keywords.js' {
  declare module.exports: $Exports<'prismjs/plugins/highlight-keywords/prism-highlight-keywords'>;
}
declare module 'prismjs/plugins/highlight-keywords/prism-highlight-keywords.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/highlight-keywords/prism-highlight-keywords.min'>;
}
declare module 'prismjs/plugins/ie8/prism-ie8.js' {
  declare module.exports: $Exports<'prismjs/plugins/ie8/prism-ie8'>;
}
declare module 'prismjs/plugins/ie8/prism-ie8.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/ie8/prism-ie8.min'>;
}
declare module 'prismjs/plugins/jsonp-highlight/prism-jsonp-highlight.js' {
  declare module.exports: $Exports<'prismjs/plugins/jsonp-highlight/prism-jsonp-highlight'>;
}
declare module 'prismjs/plugins/jsonp-highlight/prism-jsonp-highlight.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/jsonp-highlight/prism-jsonp-highlight.min'>;
}
declare module 'prismjs/plugins/keep-markup/prism-keep-markup.js' {
  declare module.exports: $Exports<'prismjs/plugins/keep-markup/prism-keep-markup'>;
}
declare module 'prismjs/plugins/keep-markup/prism-keep-markup.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/keep-markup/prism-keep-markup.min'>;
}
declare module 'prismjs/plugins/line-highlight/prism-line-highlight.js' {
  declare module.exports: $Exports<'prismjs/plugins/line-highlight/prism-line-highlight'>;
}
declare module 'prismjs/plugins/line-highlight/prism-line-highlight.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/line-highlight/prism-line-highlight.min'>;
}
declare module 'prismjs/plugins/line-numbers/prism-line-numbers.js' {
  declare module.exports: $Exports<'prismjs/plugins/line-numbers/prism-line-numbers'>;
}
declare module 'prismjs/plugins/line-numbers/prism-line-numbers.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/line-numbers/prism-line-numbers.min'>;
}
declare module 'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.js' {
  declare module.exports: $Exports<'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace'>;
}
declare module 'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.min'>;
}
declare module 'prismjs/plugins/previewer-angle/prism-previewer-angle.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-angle/prism-previewer-angle'>;
}
declare module 'prismjs/plugins/previewer-angle/prism-previewer-angle.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-angle/prism-previewer-angle.min'>;
}
declare module 'prismjs/plugins/previewer-base/prism-previewer-base.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-base/prism-previewer-base'>;
}
declare module 'prismjs/plugins/previewer-base/prism-previewer-base.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-base/prism-previewer-base.min'>;
}
declare module 'prismjs/plugins/previewer-color/prism-previewer-color.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-color/prism-previewer-color'>;
}
declare module 'prismjs/plugins/previewer-color/prism-previewer-color.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-color/prism-previewer-color.min'>;
}
declare module 'prismjs/plugins/previewer-easing/prism-previewer-easing.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-easing/prism-previewer-easing'>;
}
declare module 'prismjs/plugins/previewer-easing/prism-previewer-easing.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-easing/prism-previewer-easing.min'>;
}
declare module 'prismjs/plugins/previewer-gradient/prism-previewer-gradient.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-gradient/prism-previewer-gradient'>;
}
declare module 'prismjs/plugins/previewer-gradient/prism-previewer-gradient.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-gradient/prism-previewer-gradient.min'>;
}
declare module 'prismjs/plugins/previewer-time/prism-previewer-time.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-time/prism-previewer-time'>;
}
declare module 'prismjs/plugins/previewer-time/prism-previewer-time.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/previewer-time/prism-previewer-time.min'>;
}
declare module 'prismjs/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.js' {
  declare module.exports: $Exports<'prismjs/plugins/remove-initial-line-feed/prism-remove-initial-line-feed'>;
}
declare module 'prismjs/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min'>;
}
declare module 'prismjs/plugins/show-invisibles/prism-show-invisibles.js' {
  declare module.exports: $Exports<'prismjs/plugins/show-invisibles/prism-show-invisibles'>;
}
declare module 'prismjs/plugins/show-invisibles/prism-show-invisibles.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/show-invisibles/prism-show-invisibles.min'>;
}
declare module 'prismjs/plugins/show-language/prism-show-language.js' {
  declare module.exports: $Exports<'prismjs/plugins/show-language/prism-show-language'>;
}
declare module 'prismjs/plugins/show-language/prism-show-language.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/show-language/prism-show-language.min'>;
}
declare module 'prismjs/plugins/toolbar/prism-toolbar.js' {
  declare module.exports: $Exports<'prismjs/plugins/toolbar/prism-toolbar'>;
}
declare module 'prismjs/plugins/toolbar/prism-toolbar.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/toolbar/prism-toolbar.min'>;
}
declare module 'prismjs/plugins/unescaped-markup/prism-unescaped-markup.js' {
  declare module.exports: $Exports<'prismjs/plugins/unescaped-markup/prism-unescaped-markup'>;
}
declare module 'prismjs/plugins/unescaped-markup/prism-unescaped-markup.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/unescaped-markup/prism-unescaped-markup.min'>;
}
declare module 'prismjs/plugins/wpd/prism-wpd.js' {
  declare module.exports: $Exports<'prismjs/plugins/wpd/prism-wpd'>;
}
declare module 'prismjs/plugins/wpd/prism-wpd.min.js' {
  declare module.exports: $Exports<'prismjs/plugins/wpd/prism-wpd.min'>;
}
declare module 'prismjs/prism.js' {
  declare module.exports: $Exports<'prismjs/prism'>;
}
declare module 'prismjs/tests/helper/prism-loader.js' {
  declare module.exports: $Exports<'prismjs/tests/helper/prism-loader'>;
}
declare module 'prismjs/tests/helper/test-case.js' {
  declare module.exports: $Exports<'prismjs/tests/helper/test-case'>;
}
declare module 'prismjs/tests/helper/test-discovery.js' {
  declare module.exports: $Exports<'prismjs/tests/helper/test-discovery'>;
}
declare module 'prismjs/tests/helper/token-stream-transformer.js' {
  declare module.exports: $Exports<'prismjs/tests/helper/token-stream-transformer'>;
}
declare module 'prismjs/tests/languages/asciidoc/entity_feature.js' {
  declare module.exports: $Exports<'prismjs/tests/languages/asciidoc/entity_feature'>;
}
declare module 'prismjs/tests/languages/groovy/issue1049.js' {
  declare module.exports: $Exports<'prismjs/tests/languages/groovy/issue1049'>;
}
declare module 'prismjs/tests/languages/groovy/string-interpolation_feature.js' {
  declare module.exports: $Exports<'prismjs/tests/languages/groovy/string-interpolation_feature'>;
}
declare module 'prismjs/tests/languages/handlebars/handlebars_in_markup_feature.js' {
  declare module.exports: $Exports<'prismjs/tests/languages/handlebars/handlebars_in_markup_feature'>;
}
declare module 'prismjs/tests/languages/markup/entity_feature.js' {
  declare module.exports: $Exports<'prismjs/tests/languages/markup/entity_feature'>;
}
declare module 'prismjs/tests/languages/markup+php/php_in_markup_feature.js' {
  declare module.exports: $Exports<'prismjs/tests/languages/markup+php/php_in_markup_feature'>;
}
declare module 'prismjs/tests/languages/smarty/smarty_in_markup_feature.js' {
  declare module.exports: $Exports<'prismjs/tests/languages/smarty/smarty_in_markup_feature'>;
}
declare module 'prismjs/tests/run-child.js' {
  declare module.exports: $Exports<'prismjs/tests/run-child'>;
}
declare module 'prismjs/tests/run.js' {
  declare module.exports: $Exports<'prismjs/tests/run'>;
}
declare module 'prismjs/tests/testrunner-tests.js' {
  declare module.exports: $Exports<'prismjs/tests/testrunner-tests'>;
}
declare module 'prismjs/vendor/FileSaver.min.js' {
  declare module.exports: $Exports<'prismjs/vendor/FileSaver.min'>;
}
declare module 'prismjs/vendor/jszip.min.js' {
  declare module.exports: $Exports<'prismjs/vendor/jszip.min'>;
}
declare module 'prismjs/vendor/promise.js' {
  declare module.exports: $Exports<'prismjs/vendor/promise'>;
}
