// flow-typed signature: c28999e687d3c9f249892f622171513a
// flow-typed version: <<STUB>>/random-words_v0.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-words/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-words/index' {
  declare module.exports: $Exports<'random-words'>;
}
declare module 'random-words/index.js' {
  declare module.exports: $Exports<'random-words'>;
}
declare module 'random-words/tests/test.js' {
  declare module.exports: $Exports<'random-words/tests/test'>;
}
