// flow-typed signature: 053c279562c4091881b55b49b1db549a
// flow-typed version: <<STUB>>/react-scrollbar-size_v^2.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrollbar-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrollbar-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scrollbar-size/ScrollbarSize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scrollbar-size/index' {
  declare module.exports: $Exports<'react-scrollbar-size'>;
}
declare module 'react-scrollbar-size/index.js' {
  declare module.exports: $Exports<'react-scrollbar-size'>;
}
declare module 'react-scrollbar-size/ScrollbarSize.js' {
  declare module.exports: $Exports<'react-scrollbar-size/ScrollbarSize'>;
}
