// flow-typed signature: 16f23b7001eddf96277b48eb8709b97f
// flow-typed version: <<STUB>>/react-transition-group_v^2.2.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transition-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transition-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transition-group/CSSTransition' {
  declare module.exports: any;
}

declare module 'react-transition-group/dist/react-transition-group' {
  declare module.exports: any;
}

declare module 'react-transition-group/dist/react-transition-group.min' {
  declare module.exports: any;
}

declare module 'react-transition-group/Transition' {
  declare module.exports: any;
}

declare module 'react-transition-group/TransitionGroup' {
  declare module.exports: any;
}

declare module 'react-transition-group/utils/ChildMapping' {
  declare module.exports: any;
}

declare module 'react-transition-group/utils/PropTypes' {
  declare module.exports: any;
}

declare module 'react-transition-group/utils/SimpleSet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transition-group/CSSTransition.js' {
  declare module.exports: $Exports<'react-transition-group/CSSTransition'>;
}
declare module 'react-transition-group/dist/react-transition-group.js' {
  declare module.exports: $Exports<'react-transition-group/dist/react-transition-group'>;
}
declare module 'react-transition-group/dist/react-transition-group.min.js' {
  declare module.exports: $Exports<'react-transition-group/dist/react-transition-group.min'>;
}
declare module 'react-transition-group/index' {
  declare module.exports: $Exports<'react-transition-group'>;
}
declare module 'react-transition-group/index.js' {
  declare module.exports: $Exports<'react-transition-group'>;
}
declare module 'react-transition-group/Transition.js' {
  declare module.exports: $Exports<'react-transition-group/Transition'>;
}
declare module 'react-transition-group/TransitionGroup.js' {
  declare module.exports: $Exports<'react-transition-group/TransitionGroup'>;
}
declare module 'react-transition-group/utils/ChildMapping.js' {
  declare module.exports: $Exports<'react-transition-group/utils/ChildMapping'>;
}
declare module 'react-transition-group/utils/PropTypes.js' {
  declare module.exports: $Exports<'react-transition-group/utils/PropTypes'>;
}
declare module 'react-transition-group/utils/SimpleSet.js' {
  declare module.exports: $Exports<'react-transition-group/utils/SimpleSet'>;
}
