// flow-typed signature: 0af52f15deff9b9cd441640e13d1e410
// flow-typed version: <<STUB>>/react-test-renderer_v^15.5.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-test-renderer/lib/accumulate' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/accumulateInto' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/adler32' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/CallbackQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/canDefineProperty' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/checkReactTypeSpec' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/deprecated' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventConstants' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPluginHub' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPluginRegistry' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPropagators' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/flattenChildren' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/forEachAccumulated' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/getHostComponentFromComposite' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/getIteratorFn' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/instantiateReactComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/isTextInputElement' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/KeyEscapeUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/PluginModuleType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/PooledClass' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactChildFiber' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactChildReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactComponentEnvironment' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactCoroutine' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactDebugTool' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactDefaultBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactElementSymbol' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactErrorUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactEventEmitterMixin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFeatureFlags' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiber' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberBeginWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberCommitWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberCompleteWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberRoot' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberScheduler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactHostComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactHostOperationHistoryHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInstanceMap' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInstanceType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInstrumentation' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInvalidSetStateWarningHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactMultiChild' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactMultiChildUpdateTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactNodeTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactOwner' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPerf' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPriorityLevel' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/reactProdInvariant' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPropTypeLocationNames' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPropTypeLocations' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPropTypesSecret' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactRef' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactReifiedYield' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactShallowRenderer' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactSimpleEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactSyntheticEventType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestMount' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestRenderer' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestTextComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTypeOfWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactUpdates' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactVersion' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ResponderSyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ResponderTouchHistoryStore' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/accumulate' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/accumulateInto' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/adler32' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ARIADOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/AutoFocusUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/BeforeInputEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/CallbackQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/canDefineProperty' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ChangeEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/checkReactTypeSpec' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/createMicrosoftUnsafeLocalFunction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/CSSProperty' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/CSSPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/Danger' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/dangerousStyleValue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/DefaultEventPluginOrder' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/deprecated' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/DOMChildrenOperations' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/DOMLazyTree' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/DOMNamespaces' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/DOMProperty' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/DOMPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/EnterLeaveEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/escapeTextContentForBrowser' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/EventConstants' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/EventPluginHub' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/EventPluginRegistry' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/EventPropagators' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/FallbackCompositionState' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/findDOMNode' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/flattenChildren' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/forEachAccumulated' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getEventCharCode' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getEventKey' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getEventModifierState' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getEventTarget' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getHostComponentFromComposite' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getIteratorFn' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getNodeForCharacterOffset' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getTextContentAccessor' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/getVendorPrefixedEventName' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/HTMLDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/instantiateReactComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/isEventSupported' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/isTextInputElement' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/KeyEscapeUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/LinkedValueUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/PluginModuleType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/PooledClass' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/quoteAttributeValueForBrowser' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactBrowserEventEmitter' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactChildFiber' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactChildReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactComponentBrowserEnvironment' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactComponentEnvironment' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactCoroutine' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDebugTool' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDefaultBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDefaultInjection' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOM' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMComponentFlags' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMComponentTree' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMContainerInfo' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMFeatureFlags' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMFiber' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMIDOperations' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMInput' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMInvalidARIAHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMNullInputValuePropHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMOption' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMSelect' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMSelection' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMServer' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMTextarea' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMTextComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMTreeTraversal' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactDOMUnknownPropertyHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactElementSymbol' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactErrorUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactEventEmitterMixin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactEventListener' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFeatureFlags' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiber' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiberBeginWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiberCommitWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiberCompleteWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiberReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiberRoot' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiberScheduler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactFiberUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactHostComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactHostOperationHistoryHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactInjection' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactInputSelection' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactInstanceMap' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactInstanceType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactInstrumentation' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactInvalidSetStateWarningHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactMarkupChecksum' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactMount' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactMultiChild' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactMultiChildUpdateTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactNodeTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactOwner' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactPerf' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactPriorityLevel' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/reactProdInvariant' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactPropTypeLocationNames' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactPropTypeLocations' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactPropTypesSecret' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactRef' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactReifiedYield' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactServerBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactServerRendering' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactServerRenderingTransaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactServerUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactShallowRenderer' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactSimpleEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactSyntheticEventType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactTestEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactTestMount' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactTestReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactTestRenderer' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactTestTextComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactTypeOfWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactUpdates' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ReactVersion' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/renderSubtreeIntoContainer' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ResponderSyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ResponderTouchHistoryStore' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SelectEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/setInnerHTML' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/setTextContent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/shouldUpdateReactComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SimpleEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SVGDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticAnimationEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticClipboardEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticCompositionEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticDragEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticFocusEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticInputEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticKeyboardEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticMouseEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticTouchEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticTransitionEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticUIEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/SyntheticWheelEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/TapEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/TouchHistoryMath' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/Transaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/traverseAllChildren' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/validateDOMNesting' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shallow/ViewportMetrics' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shouldUpdateReactComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/SyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/TouchHistoryMath' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/Transaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/traverseAllChildren' {
  declare module.exports: any;
}

declare module 'react-test-renderer/shallow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-test-renderer/index' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
declare module 'react-test-renderer/index.js' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
declare module 'react-test-renderer/lib/accumulate.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/accumulate'>;
}
declare module 'react-test-renderer/lib/accumulateInto.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/accumulateInto'>;
}
declare module 'react-test-renderer/lib/adler32.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/adler32'>;
}
declare module 'react-test-renderer/lib/CallbackQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/CallbackQueue'>;
}
declare module 'react-test-renderer/lib/canDefineProperty.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/canDefineProperty'>;
}
declare module 'react-test-renderer/lib/checkReactTypeSpec.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/checkReactTypeSpec'>;
}
declare module 'react-test-renderer/lib/deprecated.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/deprecated'>;
}
declare module 'react-test-renderer/lib/EventConstants.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventConstants'>;
}
declare module 'react-test-renderer/lib/EventPluginHub.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPluginHub'>;
}
declare module 'react-test-renderer/lib/EventPluginRegistry.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPluginRegistry'>;
}
declare module 'react-test-renderer/lib/EventPluginUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPluginUtils'>;
}
declare module 'react-test-renderer/lib/EventPropagators.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPropagators'>;
}
declare module 'react-test-renderer/lib/flattenChildren.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/flattenChildren'>;
}
declare module 'react-test-renderer/lib/forEachAccumulated.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/forEachAccumulated'>;
}
declare module 'react-test-renderer/lib/getHostComponentFromComposite.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/getHostComponentFromComposite'>;
}
declare module 'react-test-renderer/lib/getIteratorFn.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/getIteratorFn'>;
}
declare module 'react-test-renderer/lib/instantiateReactComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/instantiateReactComponent'>;
}
declare module 'react-test-renderer/lib/isTextInputElement.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/isTextInputElement'>;
}
declare module 'react-test-renderer/lib/KeyEscapeUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/KeyEscapeUtils'>;
}
declare module 'react-test-renderer/lib/PluginModuleType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/PluginModuleType'>;
}
declare module 'react-test-renderer/lib/PooledClass.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/PooledClass'>;
}
declare module 'react-test-renderer/lib/ReactChildFiber.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactChildFiber'>;
}
declare module 'react-test-renderer/lib/ReactChildReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactChildReconciler'>;
}
declare module 'react-test-renderer/lib/ReactComponentEnvironment.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactComponentEnvironment'>;
}
declare module 'react-test-renderer/lib/ReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactCompositeComponent'>;
}
declare module 'react-test-renderer/lib/ReactCoroutine.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactCoroutine'>;
}
declare module 'react-test-renderer/lib/ReactDebugTool.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactDebugTool'>;
}
declare module 'react-test-renderer/lib/ReactDefaultBatchingStrategy.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactDefaultBatchingStrategy'>;
}
declare module 'react-test-renderer/lib/ReactElementSymbol.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactElementSymbol'>;
}
declare module 'react-test-renderer/lib/ReactEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactEmptyComponent'>;
}
declare module 'react-test-renderer/lib/ReactErrorUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactErrorUtils'>;
}
declare module 'react-test-renderer/lib/ReactEventEmitterMixin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactEventEmitterMixin'>;
}
declare module 'react-test-renderer/lib/ReactFeatureFlags.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFeatureFlags'>;
}
declare module 'react-test-renderer/lib/ReactFiber.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiber'>;
}
declare module 'react-test-renderer/lib/ReactFiberBeginWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberBeginWork'>;
}
declare module 'react-test-renderer/lib/ReactFiberCommitWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberCommitWork'>;
}
declare module 'react-test-renderer/lib/ReactFiberCompleteWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberCompleteWork'>;
}
declare module 'react-test-renderer/lib/ReactFiberReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberReconciler'>;
}
declare module 'react-test-renderer/lib/ReactFiberRoot.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberRoot'>;
}
declare module 'react-test-renderer/lib/ReactFiberScheduler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberScheduler'>;
}
declare module 'react-test-renderer/lib/ReactFiberUpdateQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberUpdateQueue'>;
}
declare module 'react-test-renderer/lib/ReactHostComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactHostComponent'>;
}
declare module 'react-test-renderer/lib/ReactHostOperationHistoryHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactHostOperationHistoryHook'>;
}
declare module 'react-test-renderer/lib/ReactInstanceMap.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInstanceMap'>;
}
declare module 'react-test-renderer/lib/ReactInstanceType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInstanceType'>;
}
declare module 'react-test-renderer/lib/ReactInstrumentation.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInstrumentation'>;
}
declare module 'react-test-renderer/lib/ReactInvalidSetStateWarningHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInvalidSetStateWarningHook'>;
}
declare module 'react-test-renderer/lib/ReactMultiChild.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactMultiChild'>;
}
declare module 'react-test-renderer/lib/ReactMultiChildUpdateTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactMultiChildUpdateTypes'>;
}
declare module 'react-test-renderer/lib/ReactNodeTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactNodeTypes'>;
}
declare module 'react-test-renderer/lib/ReactOwner.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactOwner'>;
}
declare module 'react-test-renderer/lib/ReactPerf.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPerf'>;
}
declare module 'react-test-renderer/lib/ReactPriorityLevel.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPriorityLevel'>;
}
declare module 'react-test-renderer/lib/reactProdInvariant.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/reactProdInvariant'>;
}
declare module 'react-test-renderer/lib/ReactPropTypeLocationNames.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPropTypeLocationNames'>;
}
declare module 'react-test-renderer/lib/ReactPropTypeLocations.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPropTypeLocations'>;
}
declare module 'react-test-renderer/lib/ReactPropTypesSecret.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPropTypesSecret'>;
}
declare module 'react-test-renderer/lib/ReactReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactReconciler'>;
}
declare module 'react-test-renderer/lib/ReactRef.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactRef'>;
}
declare module 'react-test-renderer/lib/ReactReifiedYield.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactReifiedYield'>;
}
declare module 'react-test-renderer/lib/ReactShallowRenderer.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactShallowRenderer'>;
}
declare module 'react-test-renderer/lib/ReactSimpleEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactSimpleEmptyComponent'>;
}
declare module 'react-test-renderer/lib/ReactSyntheticEventType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactSyntheticEventType'>;
}
declare module 'react-test-renderer/lib/ReactTestEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestEmptyComponent'>;
}
declare module 'react-test-renderer/lib/ReactTestMount.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestMount'>;
}
declare module 'react-test-renderer/lib/ReactTestReconcileTransaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestReconcileTransaction'>;
}
declare module 'react-test-renderer/lib/ReactTestRenderer.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestRenderer'>;
}
declare module 'react-test-renderer/lib/ReactTestTextComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestTextComponent'>;
}
declare module 'react-test-renderer/lib/ReactTypeOfWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTypeOfWork'>;
}
declare module 'react-test-renderer/lib/ReactTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTypes'>;
}
declare module 'react-test-renderer/lib/ReactUpdateQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactUpdateQueue'>;
}
declare module 'react-test-renderer/lib/ReactUpdates.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactUpdates'>;
}
declare module 'react-test-renderer/lib/ReactVersion.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactVersion'>;
}
declare module 'react-test-renderer/lib/ResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ResponderEventPlugin'>;
}
declare module 'react-test-renderer/lib/ResponderSyntheticEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ResponderSyntheticEvent'>;
}
declare module 'react-test-renderer/lib/ResponderTouchHistoryStore.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ResponderTouchHistoryStore'>;
}
declare module 'react-test-renderer/lib/shallow/accumulate.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/accumulate'>;
}
declare module 'react-test-renderer/lib/shallow/accumulateInto.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/accumulateInto'>;
}
declare module 'react-test-renderer/lib/shallow/adler32.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/adler32'>;
}
declare module 'react-test-renderer/lib/shallow/ARIADOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ARIADOMPropertyConfig'>;
}
declare module 'react-test-renderer/lib/shallow/AutoFocusUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/AutoFocusUtils'>;
}
declare module 'react-test-renderer/lib/shallow/BeforeInputEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/BeforeInputEventPlugin'>;
}
declare module 'react-test-renderer/lib/shallow/CallbackQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/CallbackQueue'>;
}
declare module 'react-test-renderer/lib/shallow/canDefineProperty.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/canDefineProperty'>;
}
declare module 'react-test-renderer/lib/shallow/ChangeEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ChangeEventPlugin'>;
}
declare module 'react-test-renderer/lib/shallow/checkReactTypeSpec.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/checkReactTypeSpec'>;
}
declare module 'react-test-renderer/lib/shallow/createMicrosoftUnsafeLocalFunction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/createMicrosoftUnsafeLocalFunction'>;
}
declare module 'react-test-renderer/lib/shallow/CSSProperty.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/CSSProperty'>;
}
declare module 'react-test-renderer/lib/shallow/CSSPropertyOperations.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/CSSPropertyOperations'>;
}
declare module 'react-test-renderer/lib/shallow/Danger.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/Danger'>;
}
declare module 'react-test-renderer/lib/shallow/dangerousStyleValue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/dangerousStyleValue'>;
}
declare module 'react-test-renderer/lib/shallow/DefaultEventPluginOrder.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/DefaultEventPluginOrder'>;
}
declare module 'react-test-renderer/lib/shallow/deprecated.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/deprecated'>;
}
declare module 'react-test-renderer/lib/shallow/DOMChildrenOperations.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/DOMChildrenOperations'>;
}
declare module 'react-test-renderer/lib/shallow/DOMLazyTree.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/DOMLazyTree'>;
}
declare module 'react-test-renderer/lib/shallow/DOMNamespaces.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/DOMNamespaces'>;
}
declare module 'react-test-renderer/lib/shallow/DOMProperty.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/DOMProperty'>;
}
declare module 'react-test-renderer/lib/shallow/DOMPropertyOperations.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/DOMPropertyOperations'>;
}
declare module 'react-test-renderer/lib/shallow/EnterLeaveEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/EnterLeaveEventPlugin'>;
}
declare module 'react-test-renderer/lib/shallow/escapeTextContentForBrowser.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/escapeTextContentForBrowser'>;
}
declare module 'react-test-renderer/lib/shallow/EventConstants.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/EventConstants'>;
}
declare module 'react-test-renderer/lib/shallow/EventPluginHub.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/EventPluginHub'>;
}
declare module 'react-test-renderer/lib/shallow/EventPluginRegistry.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/EventPluginRegistry'>;
}
declare module 'react-test-renderer/lib/shallow/EventPluginUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/EventPluginUtils'>;
}
declare module 'react-test-renderer/lib/shallow/EventPropagators.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/EventPropagators'>;
}
declare module 'react-test-renderer/lib/shallow/FallbackCompositionState.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/FallbackCompositionState'>;
}
declare module 'react-test-renderer/lib/shallow/findDOMNode.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/findDOMNode'>;
}
declare module 'react-test-renderer/lib/shallow/flattenChildren.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/flattenChildren'>;
}
declare module 'react-test-renderer/lib/shallow/forEachAccumulated.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/forEachAccumulated'>;
}
declare module 'react-test-renderer/lib/shallow/getEventCharCode.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getEventCharCode'>;
}
declare module 'react-test-renderer/lib/shallow/getEventKey.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getEventKey'>;
}
declare module 'react-test-renderer/lib/shallow/getEventModifierState.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getEventModifierState'>;
}
declare module 'react-test-renderer/lib/shallow/getEventTarget.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getEventTarget'>;
}
declare module 'react-test-renderer/lib/shallow/getHostComponentFromComposite.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getHostComponentFromComposite'>;
}
declare module 'react-test-renderer/lib/shallow/getIteratorFn.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getIteratorFn'>;
}
declare module 'react-test-renderer/lib/shallow/getNodeForCharacterOffset.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getNodeForCharacterOffset'>;
}
declare module 'react-test-renderer/lib/shallow/getTextContentAccessor.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getTextContentAccessor'>;
}
declare module 'react-test-renderer/lib/shallow/getVendorPrefixedEventName.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/getVendorPrefixedEventName'>;
}
declare module 'react-test-renderer/lib/shallow/HTMLDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/HTMLDOMPropertyConfig'>;
}
declare module 'react-test-renderer/lib/shallow/instantiateReactComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/instantiateReactComponent'>;
}
declare module 'react-test-renderer/lib/shallow/isEventSupported.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/isEventSupported'>;
}
declare module 'react-test-renderer/lib/shallow/isTextInputElement.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/isTextInputElement'>;
}
declare module 'react-test-renderer/lib/shallow/KeyEscapeUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/KeyEscapeUtils'>;
}
declare module 'react-test-renderer/lib/shallow/LinkedValueUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/LinkedValueUtils'>;
}
declare module 'react-test-renderer/lib/shallow/PluginModuleType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/PluginModuleType'>;
}
declare module 'react-test-renderer/lib/shallow/PooledClass.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/PooledClass'>;
}
declare module 'react-test-renderer/lib/shallow/quoteAttributeValueForBrowser.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/quoteAttributeValueForBrowser'>;
}
declare module 'react-test-renderer/lib/shallow/ReactBrowserEventEmitter.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactBrowserEventEmitter'>;
}
declare module 'react-test-renderer/lib/shallow/ReactChildFiber.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactChildFiber'>;
}
declare module 'react-test-renderer/lib/shallow/ReactChildReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactChildReconciler'>;
}
declare module 'react-test-renderer/lib/shallow/ReactComponentBrowserEnvironment.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactComponentBrowserEnvironment'>;
}
declare module 'react-test-renderer/lib/shallow/ReactComponentEnvironment.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactComponentEnvironment'>;
}
declare module 'react-test-renderer/lib/shallow/ReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactCompositeComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactCoroutine.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactCoroutine'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDebugTool.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDebugTool'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDefaultBatchingStrategy.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDefaultBatchingStrategy'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDefaultInjection.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDefaultInjection'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOM.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOM'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMComponentFlags.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMComponentFlags'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMComponentTree.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMComponentTree'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMContainerInfo.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMContainerInfo'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMEmptyComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMFeatureFlags.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMFeatureFlags'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMFiber.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMFiber'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMIDOperations.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMIDOperations'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMInput.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMInput'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMInvalidARIAHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMInvalidARIAHook'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMNullInputValuePropHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMNullInputValuePropHook'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMOption.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMOption'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMSelect.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMSelect'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMSelection.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMSelection'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMServer.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMServer'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMTextarea.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMTextarea'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMTextComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMTextComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMTreeTraversal.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMTreeTraversal'>;
}
declare module 'react-test-renderer/lib/shallow/ReactDOMUnknownPropertyHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactDOMUnknownPropertyHook'>;
}
declare module 'react-test-renderer/lib/shallow/ReactElementSymbol.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactElementSymbol'>;
}
declare module 'react-test-renderer/lib/shallow/ReactEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactEmptyComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactErrorUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactErrorUtils'>;
}
declare module 'react-test-renderer/lib/shallow/ReactEventEmitterMixin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactEventEmitterMixin'>;
}
declare module 'react-test-renderer/lib/shallow/ReactEventListener.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactEventListener'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFeatureFlags.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFeatureFlags'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiber.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiber'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiberBeginWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiberBeginWork'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiberCommitWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiberCommitWork'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiberCompleteWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiberCompleteWork'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiberReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiberReconciler'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiberRoot.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiberRoot'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiberScheduler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiberScheduler'>;
}
declare module 'react-test-renderer/lib/shallow/ReactFiberUpdateQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactFiberUpdateQueue'>;
}
declare module 'react-test-renderer/lib/shallow/ReactHostComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactHostComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactHostOperationHistoryHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactHostOperationHistoryHook'>;
}
declare module 'react-test-renderer/lib/shallow/ReactInjection.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactInjection'>;
}
declare module 'react-test-renderer/lib/shallow/ReactInputSelection.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactInputSelection'>;
}
declare module 'react-test-renderer/lib/shallow/ReactInstanceMap.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactInstanceMap'>;
}
declare module 'react-test-renderer/lib/shallow/ReactInstanceType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactInstanceType'>;
}
declare module 'react-test-renderer/lib/shallow/ReactInstrumentation.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactInstrumentation'>;
}
declare module 'react-test-renderer/lib/shallow/ReactInvalidSetStateWarningHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactInvalidSetStateWarningHook'>;
}
declare module 'react-test-renderer/lib/shallow/ReactMarkupChecksum.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactMarkupChecksum'>;
}
declare module 'react-test-renderer/lib/shallow/ReactMount.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactMount'>;
}
declare module 'react-test-renderer/lib/shallow/ReactMultiChild.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactMultiChild'>;
}
declare module 'react-test-renderer/lib/shallow/ReactMultiChildUpdateTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactMultiChildUpdateTypes'>;
}
declare module 'react-test-renderer/lib/shallow/ReactNodeTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactNodeTypes'>;
}
declare module 'react-test-renderer/lib/shallow/ReactOwner.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactOwner'>;
}
declare module 'react-test-renderer/lib/shallow/ReactPerf.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactPerf'>;
}
declare module 'react-test-renderer/lib/shallow/ReactPriorityLevel.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactPriorityLevel'>;
}
declare module 'react-test-renderer/lib/shallow/reactProdInvariant.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/reactProdInvariant'>;
}
declare module 'react-test-renderer/lib/shallow/ReactPropTypeLocationNames.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactPropTypeLocationNames'>;
}
declare module 'react-test-renderer/lib/shallow/ReactPropTypeLocations.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactPropTypeLocations'>;
}
declare module 'react-test-renderer/lib/shallow/ReactPropTypesSecret.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactPropTypesSecret'>;
}
declare module 'react-test-renderer/lib/shallow/ReactReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactReconciler'>;
}
declare module 'react-test-renderer/lib/shallow/ReactReconcileTransaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactReconcileTransaction'>;
}
declare module 'react-test-renderer/lib/shallow/ReactRef.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactRef'>;
}
declare module 'react-test-renderer/lib/shallow/ReactReifiedYield.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactReifiedYield'>;
}
declare module 'react-test-renderer/lib/shallow/ReactServerBatchingStrategy.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactServerBatchingStrategy'>;
}
declare module 'react-test-renderer/lib/shallow/ReactServerRendering.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactServerRendering'>;
}
declare module 'react-test-renderer/lib/shallow/ReactServerRenderingTransaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactServerRenderingTransaction'>;
}
declare module 'react-test-renderer/lib/shallow/ReactServerUpdateQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactServerUpdateQueue'>;
}
declare module 'react-test-renderer/lib/shallow/ReactShallowRenderer.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactShallowRenderer'>;
}
declare module 'react-test-renderer/lib/shallow/ReactSimpleEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactSimpleEmptyComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactSyntheticEventType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactSyntheticEventType'>;
}
declare module 'react-test-renderer/lib/shallow/ReactTestEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactTestEmptyComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactTestMount.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactTestMount'>;
}
declare module 'react-test-renderer/lib/shallow/ReactTestReconcileTransaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactTestReconcileTransaction'>;
}
declare module 'react-test-renderer/lib/shallow/ReactTestRenderer.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactTestRenderer'>;
}
declare module 'react-test-renderer/lib/shallow/ReactTestTextComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactTestTextComponent'>;
}
declare module 'react-test-renderer/lib/shallow/ReactTypeOfWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactTypeOfWork'>;
}
declare module 'react-test-renderer/lib/shallow/ReactTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactTypes'>;
}
declare module 'react-test-renderer/lib/shallow/ReactUpdateQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactUpdateQueue'>;
}
declare module 'react-test-renderer/lib/shallow/ReactUpdates.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactUpdates'>;
}
declare module 'react-test-renderer/lib/shallow/ReactVersion.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ReactVersion'>;
}
declare module 'react-test-renderer/lib/shallow/renderSubtreeIntoContainer.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/renderSubtreeIntoContainer'>;
}
declare module 'react-test-renderer/lib/shallow/ResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ResponderEventPlugin'>;
}
declare module 'react-test-renderer/lib/shallow/ResponderSyntheticEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ResponderSyntheticEvent'>;
}
declare module 'react-test-renderer/lib/shallow/ResponderTouchHistoryStore.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ResponderTouchHistoryStore'>;
}
declare module 'react-test-renderer/lib/shallow/SelectEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SelectEventPlugin'>;
}
declare module 'react-test-renderer/lib/shallow/setInnerHTML.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/setInnerHTML'>;
}
declare module 'react-test-renderer/lib/shallow/setTextContent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/setTextContent'>;
}
declare module 'react-test-renderer/lib/shallow/shouldUpdateReactComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/shouldUpdateReactComponent'>;
}
declare module 'react-test-renderer/lib/shallow/SimpleEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SimpleEventPlugin'>;
}
declare module 'react-test-renderer/lib/shallow/SVGDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SVGDOMPropertyConfig'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticAnimationEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticAnimationEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticClipboardEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticClipboardEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticCompositionEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticCompositionEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticDragEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticDragEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticFocusEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticFocusEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticInputEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticInputEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticKeyboardEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticKeyboardEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticMouseEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticMouseEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticTouchEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticTouchEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticTransitionEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticTransitionEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticUIEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticUIEvent'>;
}
declare module 'react-test-renderer/lib/shallow/SyntheticWheelEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/SyntheticWheelEvent'>;
}
declare module 'react-test-renderer/lib/shallow/TapEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/TapEventPlugin'>;
}
declare module 'react-test-renderer/lib/shallow/TouchHistoryMath.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/TouchHistoryMath'>;
}
declare module 'react-test-renderer/lib/shallow/Transaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/Transaction'>;
}
declare module 'react-test-renderer/lib/shallow/traverseAllChildren.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/traverseAllChildren'>;
}
declare module 'react-test-renderer/lib/shallow/validateDOMNesting.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/validateDOMNesting'>;
}
declare module 'react-test-renderer/lib/shallow/ViewportMetrics.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shallow/ViewportMetrics'>;
}
declare module 'react-test-renderer/lib/shouldUpdateReactComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shouldUpdateReactComponent'>;
}
declare module 'react-test-renderer/lib/SyntheticEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/SyntheticEvent'>;
}
declare module 'react-test-renderer/lib/TouchHistoryMath.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/TouchHistoryMath'>;
}
declare module 'react-test-renderer/lib/Transaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/Transaction'>;
}
declare module 'react-test-renderer/lib/traverseAllChildren.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/traverseAllChildren'>;
}
declare module 'react-test-renderer/shallow.js' {
  declare module.exports: $Exports<'react-test-renderer/shallow'>;
}
