// flow-typed signature: 3ef3fd8863ee9b61c24cd6e91a7c5af0
// flow-typed version: <<STUB>>/react-a11y_v^0.3.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-a11y/dist/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'react-a11y/dist/after' {
  declare module.exports: any;
}

declare module 'react-a11y/dist/assertions' {
  declare module.exports: any;
}

declare module 'react-a11y/dist/index' {
  declare module.exports: any;
}

declare module 'react-a11y/tests.webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-a11y/dist/__tests__/index-test.js' {
  declare module.exports: $Exports<'react-a11y/dist/__tests__/index-test'>;
}
declare module 'react-a11y/dist/after.js' {
  declare module.exports: $Exports<'react-a11y/dist/after'>;
}
declare module 'react-a11y/dist/assertions.js' {
  declare module.exports: $Exports<'react-a11y/dist/assertions'>;
}
declare module 'react-a11y/dist/index.js' {
  declare module.exports: $Exports<'react-a11y/dist/index'>;
}
declare module 'react-a11y/tests.webpack.js' {
  declare module.exports: $Exports<'react-a11y/tests.webpack'>;
}
