// flow-typed signature: 179462f66ae2b6d17e677d973f811e39
// flow-typed version: <<STUB>>/react-docgen_v^3.0.0-beta6/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-docgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-docgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-docgen/bin/react-docgen' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/babylon' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/Documentation' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/componentDocblockHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/componentMethodsHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/componentMethodsJsDocHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/defaultPropsHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/displayNameHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/flowTypeDocBlockHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/flowTypeHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/index' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/propDocBlockHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/propTypeCompositionHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/handlers/propTypeHandler' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/main' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/parse' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/resolver/findAllComponentDefinitions' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/resolver/findAllExportedComponentDefinitions' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/resolver/findExportedComponentDefinition' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/resolver/index' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/docblock' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/expressionTo' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getClassMemberValuePath' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getFlowType' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getFlowTypeFromReactComponent' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getMemberExpressionRoot' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getMemberExpressionValuePath' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getMembers' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getMemberValuePath' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getMethodDocumentation' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getNameOrValue' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getParameterName' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getPropertyName' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getPropertyValuePath' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getPropType' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/getTypeAnnotation' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/index' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isExportsOrModuleAssignment' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isReactChildrenElementCall' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isReactCloneElementCall' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isReactComponentClass' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isReactComponentMethod' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isReactCreateClassCall' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isReactCreateElementCall' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isReactModuleName' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isRequiredPropType' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isStatelessComponent' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/isUnreachableFlowType' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/match' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/normalizeClassDefinition' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/parseJsDoc' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/printValue' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/resolveExportDeclaration' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/resolveHOC' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/resolveToModule' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/resolveToValue' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/setPropDescription' {
  declare module.exports: any;
}

declare module 'react-docgen/dist/utils/traverse' {
  declare module.exports: any;
}

declare module 'react-docgen/example/components/Component' {
  declare module.exports: any;
}

declare module 'react-docgen/example/components/NoComponent' {
  declare module.exports: any;
}

declare module 'react-docgen/example/generateMarkdown' {
  declare module.exports: any;
}

declare module 'react-docgen/flow-typed/react-docgen' {
  declare module.exports: any;
}

declare module 'react-docgen/flow-typed/recast' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-docgen/bin/react-docgen.js' {
  declare module.exports: $Exports<'react-docgen/bin/react-docgen'>;
}
declare module 'react-docgen/dist/babylon.js' {
  declare module.exports: $Exports<'react-docgen/dist/babylon'>;
}
declare module 'react-docgen/dist/Documentation.js' {
  declare module.exports: $Exports<'react-docgen/dist/Documentation'>;
}
declare module 'react-docgen/dist/handlers/componentDocblockHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/componentDocblockHandler'>;
}
declare module 'react-docgen/dist/handlers/componentMethodsHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/componentMethodsHandler'>;
}
declare module 'react-docgen/dist/handlers/componentMethodsJsDocHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/componentMethodsJsDocHandler'>;
}
declare module 'react-docgen/dist/handlers/defaultPropsHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/defaultPropsHandler'>;
}
declare module 'react-docgen/dist/handlers/displayNameHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/displayNameHandler'>;
}
declare module 'react-docgen/dist/handlers/flowTypeDocBlockHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/flowTypeDocBlockHandler'>;
}
declare module 'react-docgen/dist/handlers/flowTypeHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/flowTypeHandler'>;
}
declare module 'react-docgen/dist/handlers/index.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/index'>;
}
declare module 'react-docgen/dist/handlers/propDocBlockHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/propDocBlockHandler'>;
}
declare module 'react-docgen/dist/handlers/propTypeCompositionHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/propTypeCompositionHandler'>;
}
declare module 'react-docgen/dist/handlers/propTypeHandler.js' {
  declare module.exports: $Exports<'react-docgen/dist/handlers/propTypeHandler'>;
}
declare module 'react-docgen/dist/main.js' {
  declare module.exports: $Exports<'react-docgen/dist/main'>;
}
declare module 'react-docgen/dist/parse.js' {
  declare module.exports: $Exports<'react-docgen/dist/parse'>;
}
declare module 'react-docgen/dist/resolver/findAllComponentDefinitions.js' {
  declare module.exports: $Exports<'react-docgen/dist/resolver/findAllComponentDefinitions'>;
}
declare module 'react-docgen/dist/resolver/findAllExportedComponentDefinitions.js' {
  declare module.exports: $Exports<'react-docgen/dist/resolver/findAllExportedComponentDefinitions'>;
}
declare module 'react-docgen/dist/resolver/findExportedComponentDefinition.js' {
  declare module.exports: $Exports<'react-docgen/dist/resolver/findExportedComponentDefinition'>;
}
declare module 'react-docgen/dist/resolver/index.js' {
  declare module.exports: $Exports<'react-docgen/dist/resolver/index'>;
}
declare module 'react-docgen/dist/utils/docblock.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/docblock'>;
}
declare module 'react-docgen/dist/utils/expressionTo.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/expressionTo'>;
}
declare module 'react-docgen/dist/utils/getClassMemberValuePath.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getClassMemberValuePath'>;
}
declare module 'react-docgen/dist/utils/getFlowType.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getFlowType'>;
}
declare module 'react-docgen/dist/utils/getFlowTypeFromReactComponent.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getFlowTypeFromReactComponent'>;
}
declare module 'react-docgen/dist/utils/getMemberExpressionRoot.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getMemberExpressionRoot'>;
}
declare module 'react-docgen/dist/utils/getMemberExpressionValuePath.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getMemberExpressionValuePath'>;
}
declare module 'react-docgen/dist/utils/getMembers.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getMembers'>;
}
declare module 'react-docgen/dist/utils/getMemberValuePath.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getMemberValuePath'>;
}
declare module 'react-docgen/dist/utils/getMethodDocumentation.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getMethodDocumentation'>;
}
declare module 'react-docgen/dist/utils/getNameOrValue.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getNameOrValue'>;
}
declare module 'react-docgen/dist/utils/getParameterName.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getParameterName'>;
}
declare module 'react-docgen/dist/utils/getPropertyName.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getPropertyName'>;
}
declare module 'react-docgen/dist/utils/getPropertyValuePath.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getPropertyValuePath'>;
}
declare module 'react-docgen/dist/utils/getPropType.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getPropType'>;
}
declare module 'react-docgen/dist/utils/getTypeAnnotation.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/getTypeAnnotation'>;
}
declare module 'react-docgen/dist/utils/index.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/index'>;
}
declare module 'react-docgen/dist/utils/isExportsOrModuleAssignment.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isExportsOrModuleAssignment'>;
}
declare module 'react-docgen/dist/utils/isReactChildrenElementCall.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isReactChildrenElementCall'>;
}
declare module 'react-docgen/dist/utils/isReactCloneElementCall.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isReactCloneElementCall'>;
}
declare module 'react-docgen/dist/utils/isReactComponentClass.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isReactComponentClass'>;
}
declare module 'react-docgen/dist/utils/isReactComponentMethod.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isReactComponentMethod'>;
}
declare module 'react-docgen/dist/utils/isReactCreateClassCall.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isReactCreateClassCall'>;
}
declare module 'react-docgen/dist/utils/isReactCreateElementCall.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isReactCreateElementCall'>;
}
declare module 'react-docgen/dist/utils/isReactModuleName.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isReactModuleName'>;
}
declare module 'react-docgen/dist/utils/isRequiredPropType.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isRequiredPropType'>;
}
declare module 'react-docgen/dist/utils/isStatelessComponent.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isStatelessComponent'>;
}
declare module 'react-docgen/dist/utils/isUnreachableFlowType.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/isUnreachableFlowType'>;
}
declare module 'react-docgen/dist/utils/match.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/match'>;
}
declare module 'react-docgen/dist/utils/normalizeClassDefinition.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/normalizeClassDefinition'>;
}
declare module 'react-docgen/dist/utils/parseJsDoc.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/parseJsDoc'>;
}
declare module 'react-docgen/dist/utils/printValue.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/printValue'>;
}
declare module 'react-docgen/dist/utils/resolveExportDeclaration.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/resolveExportDeclaration'>;
}
declare module 'react-docgen/dist/utils/resolveHOC.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/resolveHOC'>;
}
declare module 'react-docgen/dist/utils/resolveToModule.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/resolveToModule'>;
}
declare module 'react-docgen/dist/utils/resolveToValue.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/resolveToValue'>;
}
declare module 'react-docgen/dist/utils/setPropDescription.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/setPropDescription'>;
}
declare module 'react-docgen/dist/utils/traverse.js' {
  declare module.exports: $Exports<'react-docgen/dist/utils/traverse'>;
}
declare module 'react-docgen/example/components/Component.js' {
  declare module.exports: $Exports<'react-docgen/example/components/Component'>;
}
declare module 'react-docgen/example/components/NoComponent.js' {
  declare module.exports: $Exports<'react-docgen/example/components/NoComponent'>;
}
declare module 'react-docgen/example/generateMarkdown.js' {
  declare module.exports: $Exports<'react-docgen/example/generateMarkdown'>;
}
declare module 'react-docgen/flow-typed/react-docgen.js' {
  declare module.exports: $Exports<'react-docgen/flow-typed/react-docgen'>;
}
declare module 'react-docgen/flow-typed/recast.js' {
  declare module.exports: $Exports<'react-docgen/flow-typed/recast'>;
}
