// flow-typed signature: 12b7d5f38c2c274bd21a6cc5adfc5251
// flow-typed version: <<STUB>>/recompose_v^0.23.5/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recompose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recompose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recompose/baconObservableConfig' {
  declare module.exports: any;
}

declare module 'recompose/branch' {
  declare module.exports: any;
}

declare module 'recompose/build/Recompose' {
  declare module.exports: any;
}

declare module 'recompose/build/Recompose.min' {
  declare module.exports: any;
}

declare module 'recompose/cjs/Recompose' {
  declare module.exports: any;
}

declare module 'recompose/componentFromProp' {
  declare module.exports: any;
}

declare module 'recompose/componentFromStream' {
  declare module.exports: any;
}

declare module 'recompose/compose' {
  declare module.exports: any;
}

declare module 'recompose/createEagerElement' {
  declare module.exports: any;
}

declare module 'recompose/createEagerFactory' {
  declare module.exports: any;
}

declare module 'recompose/createEventHandler' {
  declare module.exports: any;
}

declare module 'recompose/createSink' {
  declare module.exports: any;
}

declare module 'recompose/defaultProps' {
  declare module.exports: any;
}

declare module 'recompose/es/Recompose' {
  declare module.exports: any;
}

declare module 'recompose/flattenProp' {
  declare module.exports: any;
}

declare module 'recompose/flydObservableConfig' {
  declare module.exports: any;
}

declare module 'recompose/getContext' {
  declare module.exports: any;
}

declare module 'recompose/getDisplayName' {
  declare module.exports: any;
}

declare module 'recompose/hoistStatics' {
  declare module.exports: any;
}

declare module 'recompose/isClassComponent' {
  declare module.exports: any;
}

declare module 'recompose/isReferentiallyTransparentFunctionComponent' {
  declare module.exports: any;
}

declare module 'recompose/kefirObservableConfig' {
  declare module.exports: any;
}

declare module 'recompose/lifecycle' {
  declare module.exports: any;
}

declare module 'recompose/mapProps' {
  declare module.exports: any;
}

declare module 'recompose/mapPropsStream' {
  declare module.exports: any;
}

declare module 'recompose/mostObservableConfig' {
  declare module.exports: any;
}

declare module 'recompose/nest' {
  declare module.exports: any;
}

declare module 'recompose/onlyUpdateForKeys' {
  declare module.exports: any;
}

declare module 'recompose/onlyUpdateForPropTypes' {
  declare module.exports: any;
}

declare module 'recompose/pure' {
  declare module.exports: any;
}

declare module 'recompose/renameProp' {
  declare module.exports: any;
}

declare module 'recompose/renameProps' {
  declare module.exports: any;
}

declare module 'recompose/renderComponent' {
  declare module.exports: any;
}

declare module 'recompose/renderNothing' {
  declare module.exports: any;
}

declare module 'recompose/rxjs4ObservableConfig' {
  declare module.exports: any;
}

declare module 'recompose/rxjsObservableConfig' {
  declare module.exports: any;
}

declare module 'recompose/setDisplayName' {
  declare module.exports: any;
}

declare module 'recompose/setObservableConfig' {
  declare module.exports: any;
}

declare module 'recompose/setPropTypes' {
  declare module.exports: any;
}

declare module 'recompose/setStatic' {
  declare module.exports: any;
}

declare module 'recompose/shallowEqual' {
  declare module.exports: any;
}

declare module 'recompose/shouldUpdate' {
  declare module.exports: any;
}

declare module 'recompose/toClass' {
  declare module.exports: any;
}

declare module 'recompose/utils/createEagerElementUtil' {
  declare module.exports: any;
}

declare module 'recompose/utils/omit' {
  declare module.exports: any;
}

declare module 'recompose/utils/pick' {
  declare module.exports: any;
}

declare module 'recompose/withContext' {
  declare module.exports: any;
}

declare module 'recompose/withHandlers' {
  declare module.exports: any;
}

declare module 'recompose/withProps' {
  declare module.exports: any;
}

declare module 'recompose/withPropsOnChange' {
  declare module.exports: any;
}

declare module 'recompose/withReducer' {
  declare module.exports: any;
}

declare module 'recompose/withState' {
  declare module.exports: any;
}

declare module 'recompose/wrapDisplayName' {
  declare module.exports: any;
}

declare module 'recompose/xstreamObservableConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recompose/baconObservableConfig.js' {
  declare module.exports: $Exports<'recompose/baconObservableConfig'>;
}
declare module 'recompose/branch.js' {
  declare module.exports: $Exports<'recompose/branch'>;
}
declare module 'recompose/build/Recompose.js' {
  declare module.exports: $Exports<'recompose/build/Recompose'>;
}
declare module 'recompose/build/Recompose.min.js' {
  declare module.exports: $Exports<'recompose/build/Recompose.min'>;
}
declare module 'recompose/cjs/Recompose.js' {
  declare module.exports: $Exports<'recompose/cjs/Recompose'>;
}
declare module 'recompose/componentFromProp.js' {
  declare module.exports: $Exports<'recompose/componentFromProp'>;
}
declare module 'recompose/componentFromStream.js' {
  declare module.exports: $Exports<'recompose/componentFromStream'>;
}
declare module 'recompose/compose.js' {
  declare module.exports: $Exports<'recompose/compose'>;
}
declare module 'recompose/createEagerElement.js' {
  declare module.exports: $Exports<'recompose/createEagerElement'>;
}
declare module 'recompose/createEagerFactory.js' {
  declare module.exports: $Exports<'recompose/createEagerFactory'>;
}
declare module 'recompose/createEventHandler.js' {
  declare module.exports: $Exports<'recompose/createEventHandler'>;
}
declare module 'recompose/createSink.js' {
  declare module.exports: $Exports<'recompose/createSink'>;
}
declare module 'recompose/defaultProps.js' {
  declare module.exports: $Exports<'recompose/defaultProps'>;
}
declare module 'recompose/es/Recompose.js' {
  declare module.exports: $Exports<'recompose/es/Recompose'>;
}
declare module 'recompose/flattenProp.js' {
  declare module.exports: $Exports<'recompose/flattenProp'>;
}
declare module 'recompose/flydObservableConfig.js' {
  declare module.exports: $Exports<'recompose/flydObservableConfig'>;
}
declare module 'recompose/getContext.js' {
  declare module.exports: $Exports<'recompose/getContext'>;
}
declare module 'recompose/getDisplayName.js' {
  declare module.exports: $Exports<'recompose/getDisplayName'>;
}
declare module 'recompose/hoistStatics.js' {
  declare module.exports: $Exports<'recompose/hoistStatics'>;
}
declare module 'recompose/index' {
  declare module.exports: $Exports<'recompose'>;
}
declare module 'recompose/index.js' {
  declare module.exports: $Exports<'recompose'>;
}
declare module 'recompose/isClassComponent.js' {
  declare module.exports: $Exports<'recompose/isClassComponent'>;
}
declare module 'recompose/isReferentiallyTransparentFunctionComponent.js' {
  declare module.exports: $Exports<'recompose/isReferentiallyTransparentFunctionComponent'>;
}
declare module 'recompose/kefirObservableConfig.js' {
  declare module.exports: $Exports<'recompose/kefirObservableConfig'>;
}
declare module 'recompose/lifecycle.js' {
  declare module.exports: $Exports<'recompose/lifecycle'>;
}
declare module 'recompose/mapProps.js' {
  declare module.exports: $Exports<'recompose/mapProps'>;
}
declare module 'recompose/mapPropsStream.js' {
  declare module.exports: $Exports<'recompose/mapPropsStream'>;
}
declare module 'recompose/mostObservableConfig.js' {
  declare module.exports: $Exports<'recompose/mostObservableConfig'>;
}
declare module 'recompose/nest.js' {
  declare module.exports: $Exports<'recompose/nest'>;
}
declare module 'recompose/onlyUpdateForKeys.js' {
  declare module.exports: $Exports<'recompose/onlyUpdateForKeys'>;
}
declare module 'recompose/onlyUpdateForPropTypes.js' {
  declare module.exports: $Exports<'recompose/onlyUpdateForPropTypes'>;
}
declare module 'recompose/pure.js' {
  declare module.exports: $Exports<'recompose/pure'>;
}
declare module 'recompose/renameProp.js' {
  declare module.exports: $Exports<'recompose/renameProp'>;
}
declare module 'recompose/renameProps.js' {
  declare module.exports: $Exports<'recompose/renameProps'>;
}
declare module 'recompose/renderComponent.js' {
  declare module.exports: $Exports<'recompose/renderComponent'>;
}
declare module 'recompose/renderNothing.js' {
  declare module.exports: $Exports<'recompose/renderNothing'>;
}
declare module 'recompose/rxjs4ObservableConfig.js' {
  declare module.exports: $Exports<'recompose/rxjs4ObservableConfig'>;
}
declare module 'recompose/rxjsObservableConfig.js' {
  declare module.exports: $Exports<'recompose/rxjsObservableConfig'>;
}
declare module 'recompose/setDisplayName.js' {
  declare module.exports: $Exports<'recompose/setDisplayName'>;
}
declare module 'recompose/setObservableConfig.js' {
  declare module.exports: $Exports<'recompose/setObservableConfig'>;
}
declare module 'recompose/setPropTypes.js' {
  declare module.exports: $Exports<'recompose/setPropTypes'>;
}
declare module 'recompose/setStatic.js' {
  declare module.exports: $Exports<'recompose/setStatic'>;
}
declare module 'recompose/shallowEqual.js' {
  declare module.exports: $Exports<'recompose/shallowEqual'>;
}
declare module 'recompose/shouldUpdate.js' {
  declare module.exports: $Exports<'recompose/shouldUpdate'>;
}
declare module 'recompose/toClass.js' {
  declare module.exports: $Exports<'recompose/toClass'>;
}
declare module 'recompose/utils/createEagerElementUtil.js' {
  declare module.exports: $Exports<'recompose/utils/createEagerElementUtil'>;
}
declare module 'recompose/utils/omit.js' {
  declare module.exports: $Exports<'recompose/utils/omit'>;
}
declare module 'recompose/utils/pick.js' {
  declare module.exports: $Exports<'recompose/utils/pick'>;
}
declare module 'recompose/withContext.js' {
  declare module.exports: $Exports<'recompose/withContext'>;
}
declare module 'recompose/withHandlers.js' {
  declare module.exports: $Exports<'recompose/withHandlers'>;
}
declare module 'recompose/withProps.js' {
  declare module.exports: $Exports<'recompose/withProps'>;
}
declare module 'recompose/withPropsOnChange.js' {
  declare module.exports: $Exports<'recompose/withPropsOnChange'>;
}
declare module 'recompose/withReducer.js' {
  declare module.exports: $Exports<'recompose/withReducer'>;
}
declare module 'recompose/withState.js' {
  declare module.exports: $Exports<'recompose/withState'>;
}
declare module 'recompose/wrapDisplayName.js' {
  declare module.exports: $Exports<'recompose/wrapDisplayName'>;
}
declare module 'recompose/xstreamObservableConfig.js' {
  declare module.exports: $Exports<'recompose/xstreamObservableConfig'>;
}
