// flow-typed signature: 39675a2bf0c4bafcf543eccb611cd857
// flow-typed version: <<STUB>>/recursive-readdir-sync_v^1.0.6/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recursive-readdir-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recursive-readdir-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recursive-readdir-sync/test/index' {
  declare module.exports: any;
}

declare module 'recursive-readdir-sync/test/nested/a/b/file2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recursive-readdir-sync/index' {
  declare module.exports: $Exports<'recursive-readdir-sync'>;
}
declare module 'recursive-readdir-sync/index.js' {
  declare module.exports: $Exports<'recursive-readdir-sync'>;
}
declare module 'recursive-readdir-sync/test/index.js' {
  declare module.exports: $Exports<'recursive-readdir-sync/test/index'>;
}
declare module 'recursive-readdir-sync/test/nested/a/b/file2.js' {
  declare module.exports: $Exports<'recursive-readdir-sync/test/nested/a/b/file2'>;
}
