// flow-typed signature: 5d2f4e4f1bc2c513c36c4fcc926fd9ac
// flow-typed version: <<STUB>>/size-limit_v^0.13.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'size-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'size-limit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'size-limit/cli' {
  declare module.exports: any;
}

declare module 'size-limit/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'size-limit/cli.js' {
  declare module.exports: $Exports<'size-limit/cli'>;
}
declare module 'size-limit/index' {
  declare module.exports: $Exports<'size-limit'>;
}
declare module 'size-limit/index.js' {
  declare module.exports: $Exports<'size-limit'>;
}
declare module 'size-limit/promisify.js' {
  declare module.exports: $Exports<'size-limit/promisify'>;
}
