// flow-typed signature: e5c0220981e02bf4f0cf058073ec4070
// flow-typed version: <<STUB>>/url-loader_v^0.5.9/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'url-loader/index' {
  declare module.exports: $Exports<'url-loader'>;
}
declare module 'url-loader/index.js' {
  declare module.exports: $Exports<'url-loader'>;
}
