export {
  CommonColors,
  ColorPartial,
  TypeText,
  TypeAction,
  TypeBackground,
  TypeDivider,
  PaletteColorOptions,
  PaletteColor,
  TypeObject,
  PaletteTonalOffset,
  light,
  dark,
  SimplePaletteColorOptions,
  PaletteAugmentColorOptions,
  Palette,
  Channels,
  PartialTypeObject,
  PaletteOptions,
  createPalette as default,
} from '@mui/md-theme';
