export {
  Variant,
  FontStyle,
  NormalCssProperties,
  Fontface,
  BaseCSSProperties,
  CSSProperties,
  FontStyleOptions,
  TypographyStyle,
  TypographyStyleOptions,
  TypographyUtils,
  Typography,
  TypographyOptions,
  createTypography as default,
} from '@mui/md-theme';
