import type { AlertProps } from '../Alert';
import type { AlertTitleProps } from '../AlertTitle';
import type { AppBarProps } from '../AppBar';
import type { AutocompleteProps } from '../Autocomplete';
import type { AvatarProps } from '../Avatar';
import type { AvatarGroupProps } from '../AvatarGroup';
import type { BackdropProps } from '../Backdrop';
import type { BadgeProps } from '../Badge';
import type { BottomNavigationActionProps } from '../BottomNavigationAction';
import type { BottomNavigationProps } from '../BottomNavigation';
import type { BreadcrumbsProps } from '../Breadcrumbs';
import type { ButtonBaseProps } from '../ButtonBase';
import type { ButtonGroupProps } from '../ButtonGroup';
import type { ButtonProps } from '../Button';
import type { CardActionAreaProps } from '../CardActionArea';
import type { CardActionsProps } from '../CardActions';
import type { CardContentProps } from '../CardContent';
import type { CardHeaderProps } from '../CardHeader';
import type { CardMediaProps } from '../CardMedia';
import type { CardProps } from '../Card';
import type { CheckboxProps } from '../Checkbox';
import type { ChipProps } from '../Chip';
import type { CircularProgressProps } from '../CircularProgress';
import type { CollapseProps } from '../Collapse';
import type { ContainerProps } from '../Container';
import type { CssBaselineProps } from '../CssBaseline';
import type { DialogActionsProps } from '../DialogActions';
import type { DialogContentProps } from '../DialogContent';
import type { DialogContentTextProps } from '../DialogContentText';
import type { DialogProps } from '../Dialog';
import type { DialogTitleProps } from '../DialogTitle';
import type { DividerProps } from '../Divider';
import type { DrawerProps } from '../Drawer';
import type { AccordionActionsProps } from '../AccordionActions';
import type { AccordionDetailsProps } from '../AccordionDetails';
import type { AccordionProps } from '../Accordion';
import type { AccordionSummaryProps } from '../AccordionSummary';
import type { FabProps } from '../Fab';
import type { FilledInputProps } from '../FilledInput';
import type { FormControlLabelProps } from '../FormControlLabel';
import type { FormControlProps } from '../FormControl';
import type { FormGroupProps } from '../FormGroup';
import type { FormHelperTextProps } from '../FormHelperText';
import type { FormLabelProps } from '../FormLabel';
import type { GridProps } from '../Grid';
import type { Grid2Props } from '../Grid2';
import type { IconButtonProps } from '../IconButton';
import type { IconProps } from '../Icon';
import type { ImageListProps } from '../ImageList';
import type { ImageListItemBarProps } from '../ImageListItemBar';
import type { ImageListItemProps } from '../ImageListItem';
import type { InputAdornmentProps } from '../InputAdornment';
import type { InputBaseProps } from '../InputBase';
import type { InputLabelProps } from '../InputLabel';
import type { InputProps } from '../Input';
import type { LinearProgressProps } from '../LinearProgress';
import type { LinkProps } from '../Link';
import type { ListItemAvatarProps } from '../ListItemAvatar';
import type { ListItemIconProps } from '../ListItemIcon';
import type { ListItemProps } from '../ListItem';
import type { ListItemButtonProps } from '../ListItemButton';
import type { ListItemSecondaryActionProps } from '../ListItemSecondaryAction';
import type { ListItemTextProps } from '../ListItemText';
import type { ListProps } from '../List';
import type { ListSubheaderProps } from '../ListSubheader';
import type { MenuItemProps } from '../MenuItem';
import type { MenuListProps } from '../MenuList';
import type { MenuProps } from '../Menu';
import type { MobileStepperProps } from '../MobileStepper';
import type { ModalProps } from '../Modal';
import type { NativeSelectProps } from '../NativeSelect';
import type { UseMediaQueryOptions } from '../useMediaQuery';
import type { OutlinedInputProps } from '../OutlinedInput';
import type { PaginationProps } from '../Pagination';
import type { PaginationItemProps } from '../PaginationItem';
import type { PaperProps } from '../Paper';
import type { PopoverProps } from '../Popover';
import type { RadioGroupProps } from '../RadioGroup';
import type { RadioProps } from '../Radio';
import type { RatingProps } from '../Rating';
import type { ScopedCssBaselineProps } from '../ScopedCssBaseline';
import type { SelectProps } from '../Select';
import type { SkeletonProps } from '../Skeleton';
import type { SliderProps } from '../Slider';
import type { SnackbarContentProps } from '../SnackbarContent';
import type { SnackbarProps } from '../Snackbar';
import type { SpeedDialProps } from '../SpeedDial';
import type { SpeedDialActionProps } from '../SpeedDialAction';
import type { SpeedDialIconProps } from '../SpeedDialIcon';
import type { StackProps } from '../Stack';
import type { StepButtonProps } from '../StepButton';
import type { StepConnectorProps } from '../StepConnector';
import type { StepContentProps } from '../StepContent';
import type { StepIconProps } from '../StepIcon';
import type { StepLabelProps } from '../StepLabel';
import type { StepperProps } from '../Stepper';
import type { StepProps } from '../Step';
import type { SvgIconProps } from '../SvgIcon';
import type { SwipeableDrawerProps } from '../SwipeableDrawer';
import type { SwitchProps } from '../Switch';
import type { TableBodyProps } from '../TableBody';
import type { TableCellProps } from '../TableCell';
import type { TableContainerProps } from '../TableContainer';
import type { TableHeadProps } from '../TableHead';
import type { TablePaginationProps } from '../TablePagination';
import type { TableProps } from '../Table';
import type { TableRowProps } from '../TableRow';
import type { TableSortLabelProps } from '../TableSortLabel';
import type { TableFooterProps } from '../TableFooter';
import type { TabProps } from '../Tab';
import type { TabsProps } from '../Tabs';
import type { TextFieldProps } from '../TextField';
import type { ToggleButtonProps } from '../ToggleButton';
import type { ToggleButtonGroupProps } from '../ToggleButtonGroup';
import type { ToolbarProps } from '../Toolbar';
import type { TooltipProps } from '../Tooltip';
import type { TouchRippleProps } from '../ButtonBase/TouchRipple';
import type { TypographyProps } from '../Typography';
import type { PopperProps } from '../Popper';

export type ComponentsProps = {
  [Name in keyof ComponentsPropsList]?: Partial<ComponentsPropsList[Name]>;
};

export interface ComponentsPropsList {
  MuiAlert: AlertProps;
  MuiAlertTitle: AlertTitleProps;
  MuiAppBar: AppBarProps;
  MuiAutocomplete: AutocompleteProps<any, any, any, any>;
  MuiAvatar: AvatarProps;
  MuiAvatarGroup: AvatarGroupProps;
  MuiBackdrop: BackdropProps;
  MuiBadge: BadgeProps;
  MuiBottomNavigation: BottomNavigationProps;
  MuiBottomNavigationAction: BottomNavigationActionProps;
  MuiBreadcrumbs: BreadcrumbsProps;
  MuiButton: ButtonProps;
  MuiButtonBase: ButtonBaseProps;
  MuiButtonGroup: ButtonGroupProps;
  MuiCard: CardProps;
  MuiCardActionArea: CardActionAreaProps;
  MuiCardActions: CardActionsProps;
  MuiCardContent: CardContentProps;
  MuiCardHeader: CardHeaderProps;
  MuiCardMedia: CardMediaProps;
  MuiCheckbox: CheckboxProps;
  MuiChip: ChipProps;
  MuiCircularProgress: CircularProgressProps;
  MuiCollapse: CollapseProps;
  MuiContainer: ContainerProps;
  MuiCssBaseline: CssBaselineProps;
  MuiDialog: DialogProps;
  MuiDialogActions: DialogActionsProps;
  MuiDialogContent: DialogContentProps;
  MuiDialogContentText: DialogContentTextProps;
  MuiDialogTitle: DialogTitleProps;
  MuiDivider: DividerProps;
  MuiDrawer: DrawerProps;
  MuiAccordion: AccordionProps;
  MuiAccordionActions: AccordionActionsProps;
  MuiAccordionDetails: AccordionDetailsProps;
  MuiAccordionSummary: AccordionSummaryProps;
  MuiFab: FabProps;
  MuiFilledInput: FilledInputProps;
  MuiFormControl: FormControlProps;
  MuiFormControlLabel: FormControlLabelProps;
  MuiFormGroup: FormGroupProps;
  MuiFormHelperText: FormHelperTextProps;
  MuiFormLabel: FormLabelProps;
  MuiGrid: GridProps;
  MuiGrid2: Grid2Props;
  MuiImageList: ImageListProps;
  MuiImageListItem: ImageListItemProps;
  MuiImageListItemBar: ImageListItemBarProps;
  MuiIcon: IconProps;
  MuiIconButton: IconButtonProps;
  MuiInput: InputProps;
  MuiInputAdornment: InputAdornmentProps;
  MuiInputBase: InputBaseProps;
  MuiInputLabel: InputLabelProps;
  MuiLinearProgress: LinearProgressProps;
  MuiLink: LinkProps;
  MuiList: ListProps;
  MuiListItem: ListItemProps;
  MuiListItemButton: ListItemButtonProps;
  MuiListItemAvatar: ListItemAvatarProps;
  MuiListItemIcon: ListItemIconProps;
  MuiListItemSecondaryAction: ListItemSecondaryActionProps;
  MuiListItemText: ListItemTextProps;
  MuiListSubheader: ListSubheaderProps;
  MuiMenu: MenuProps;
  MuiMenuItem: MenuItemProps;
  MuiMenuList: MenuListProps;
  MuiMobileStepper: MobileStepperProps;
  MuiModal: ModalProps;
  MuiNativeSelect: NativeSelectProps;
  MuiOutlinedInput: OutlinedInputProps;
  MuiPagination: PaginationProps;
  MuiPaginationItem: PaginationItemProps;
  MuiPaper: PaperProps;
  MuiPopper: PopperProps;
  MuiPopover: PopoverProps;
  MuiRadio: RadioProps;
  MuiRadioGroup: RadioGroupProps;
  MuiRating: RatingProps;
  MuiScopedCssBaseline: ScopedCssBaselineProps;
  MuiSelect: SelectProps;
  MuiSkeleton: SkeletonProps;
  MuiSlider: SliderProps;
  MuiSnackbar: SnackbarProps;
  MuiSnackbarContent: SnackbarContentProps;
  MuiSpeedDial: SpeedDialProps;
  MuiSpeedDialAction: SpeedDialActionProps;
  MuiSpeedDialIcon: SpeedDialIconProps;
  MuiStack: StackProps;
  MuiStep: StepProps;
  MuiStepButton: StepButtonProps;
  MuiStepConnector: StepConnectorProps;
  MuiStepContent: StepContentProps;
  MuiStepIcon: StepIconProps;
  MuiStepLabel: StepLabelProps;
  MuiStepper: StepperProps;
  MuiSvgIcon: SvgIconProps;
  MuiSwipeableDrawer: SwipeableDrawerProps;
  MuiSwitch: SwitchProps;
  MuiTab: TabProps;
  MuiTable: TableProps;
  MuiTableBody: TableBodyProps;
  MuiTableCell: TableCellProps;
  MuiTableContainer: TableContainerProps;
  MuiTableFooter: TableFooterProps;
  MuiTableHead: TableHeadProps;
  MuiTablePagination: TablePaginationProps;
  MuiTableRow: TableRowProps;
  MuiTableSortLabel: TableSortLabelProps;
  MuiTabs: TabsProps;
  MuiTextField: TextFieldProps;
  MuiToggleButton: ToggleButtonProps;
  MuiToggleButtonGroup: ToggleButtonGroupProps;
  MuiToolbar: ToolbarProps;
  MuiTooltip: TooltipProps;
  MuiTouchRipple: TouchRippleProps;
  MuiTypography: TypographyProps;
  MuiUseMediaQuery: UseMediaQueryOptions;
}
