import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { createTheme, generateThemeCss } from '@mui/material/styles';

const outFile = process.env.OUTFILE
  ? resolve(process.env.OUTFILE)
  : join(process.cwd(), 'test/noop-vite-sandbox/src/theme.css');
const customBreakpoints = {
  values: { xs: 0, sm: 720, md: 900, lg: 1200, xl: 1536 },
};

const themeOptions = [
  {
    name: 'blue',
    colorSchemes: { light: true, dark: true },
  },
  {
    name: 'green',
    colorSchemes: {
      light: { palette: { primary: { main: '#2e7d32' }, secondary: { main: '#e91e63' } } },
      dark: { palette: { primary: { main: '#66bb6a' }, secondary: { main: '#f48fb1' } } },
    },
  },
  {
    name: 'red',
    colorSchemes: {
      light: { palette: { primary: { main: '#c62828' }, secondary: { main: '#f57c00' } } },
      dark: { palette: { primary: { main: '#ef9a9a' }, secondary: { main: '#ffcc02' } } },
    },
  },
];

function createScopedTheme(rootSelector: string, colorSchemes: Record<string, any>) {
  return createTheme({
    breakpoints: customBreakpoints,
    cssVariables: {
      rootSelector,
      colorSchemeSelector: `${rootSelector}[data-mui-color-scheme="%s"]`,
    },
    colorSchemes,
  });
}

const rootThemeCss = themeOptions.map(({ name, colorSchemes }) => {
  const rootSelector = `.root-theme-${name}`;
  return generateThemeCss(createScopedTheme(rootSelector, colorSchemes));
});

const nestedThemeCss = themeOptions.map(({ name, colorSchemes }) => {
  const rootSelector = `.inner-theme-${name}`;
  return generateThemeCss(createScopedTheme(rootSelector, colorSchemes));
});

const css = [
  '/* Generated by test/noop-vite-sandbox/scripts/buildThemeCss.mts. */',
  ...rootThemeCss,
  ...nestedThemeCss,
].join('\n');

writeFileSync(outFile, css, 'utf8');
// eslint-disable-next-line no-console
console.log(`Written ${outFile}`);
