import * as React from 'react';
import { withStyles } from '@mui/styles';

import { grey, blue } from '@mui/material/colors';
import { grey as grey2 } from '@mui/material/colors';
import { blue as blue2 } from '@mui/material/colors';

import {
  ThemeProvider,
  createTheme,
  MenuItem,
  Tab,
  Tabs as MuiTabs,
  autoCompleteClasses,
  BottomNavigationAction,
  BottomNavigation,
  CardContent,
  CardActions,
  Card,
  CardMedia,
  CardHeader,
  Collapse as MuiCollapse,
  ListItemSecondaryAction,
  ListItemText,
  ListItemAvatar,
  ListItem,
  ListItemIcon,
  List,
  DialogTitle,
  Dialog,
  DialogContentText,
  DialogContent,
  DialogActions,
  Slide,
  RadioGroup,
  Radio,
  FormControlLabel,
  AccordionActions,
  AccordionDetails,
  AccordionSummary,
  Accordion,
  CircularProgress,
  LinearProgress as MuiLinearProgress,
  FormHelperText,
  FormGroup,
  FormControl,
  FormLabel,
  Fade,
  StepContent,
  StepButton,
  Step,
  Stepper,
  TableRow,
  TablePagination,
  TableCell,
  TableBody,
  Table,
  TableHead,
  tooltipClasses,
  InputLabel,
  Input,
  Grow,
  TableFooter,
  Zoom,
  ClickAwayListener,
  ListSubheader,
} from '@mui/material';

import { Delete, People as PeopleIcon } from '@mui/icons-material';
