name: Bug report 🐛
description: Create a bug report for Material UI, MUI System, or Joy UI.
labels: ['status: waiting for maintainer']
body:
  - type: markdown
    attributes:
      value: Thanks for contributing by creating an issue! ❤️ Please provide a searchable summary of the issue in the title above ⬆️.
  - type: input
    attributes:
      label: Search keywords
      description: |
        Your issue may have already been reported! First search for duplicates among the [existing issues](https://github.com/mui/material-ui/issues?q=is%3Aopen+is%3Aclosed).
        If your issue isn't a duplicate, great! Please list the keywords you used so people in the future can find this one more easily:
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        **⚠️ Issues that we can't reproduce can't be fixed.**

        Please provide a link to a live example and an unambiguous set of steps to reproduce this bug. See our [documentation](https://mui.com/material-ui/getting-started/support/#bug-reproductions) on how to build a reproduction case.
        You can use this StackBlitz template as a starting point: [material-ui-vite-ts](https://stackblitz.com/github/mui/material-ui/tree/master/examples/material-ui-vite-ts)
      value: |
        Steps:
        1. Open this link to live example: (required)
        2.
        3.
  - type: textarea
    attributes:
      label: Current behavior
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Context
      description: What are you trying to accomplish? Providing context helps us come up with a solution that is more useful in the real world.
  - type: textarea
    attributes:
      label: Your environment
      description: Run `npx @mui/envinfo` and post the results. If you encounter issues with TypeScript please include the used tsconfig.
      value: |
        <details>
          <summary><code>npx @mui/envinfo</code></summary>

        ```
          Don't forget to mention which browser you used.
          Output from `npx @mui/envinfo` goes here.
        ```
        </details>
  - type: markdown
    attributes:
      value: |
        ## :heart: Love Material UI?

        Consider donating $10 to sustain our open-source work: [https://opencollective.com/mui-org](https://opencollective.com/mui-org).
