import { chipClasses } from '@mui/material/Chip';

('&.MuiChip-clickableColorPrimary');
('&.MuiChip-clickableColorSecondary');
('&.MuiChip-deletableColorPrimary');
('&.MuiChip-deletableColorSecondary');
('&.MuiChip-outlinedPrimary');
('&.MuiChip-outlinedSecondary');
('&.MuiChip-filledPrimary');
('&.MuiChip-filledSecondary');
('& .MuiChip-avatarSmall');
('& .MuiChip-avatarMedium');
('& .MuiChip-avatarColorPrimary');
('& .MuiChip-avatarColorSecondary');
('& .MuiChip-iconSmall');
('& .MuiChip-iconMedium');
('& .MuiChip-iconColorPrimary');
('& .MuiChip-iconColorSecondary');
('& .MuiChip-labelSmall');
('& .MuiChip-labelMedium');
('& .MuiChip-deleteIconSmall');
('& .MuiChip-deleteIconMedium');
('& .MuiChip-deleteIconColorPrimary');
('& .MuiChip-deleteIconColorSecondary');
('& .MuiChip-deleteIconFilledColorPrimary');
('& .MuiChip-deleteIconFilledColorSecondary');
('& .MuiChip-deleteIconOutlinedColorPrimary');
('& .MuiChip-deleteIconOutlinedColorSecondary');
`&.${chipClasses.clickableColorPrimary}`;
`&.${chipClasses.clickableColorSecondary}`;
`&.${chipClasses.deletableColorPrimary}`;
`&.${chipClasses.deletableColorSecondary}`;
`&.${chipClasses.outlinedPrimary}`;
`&.${chipClasses.outlinedSecondary}`;
`&.${chipClasses.filledPrimary}`;
`&.${chipClasses.filledSecondary}`;
`& .${chipClasses.avatarSmall}`;
`& .${chipClasses.avatarMedium}`;
`& .${chipClasses.avatarColorPrimary}`;
`& .${chipClasses.avatarColorSecondary}`;
`& .${chipClasses.iconSmall}`;
`& .${chipClasses.iconMedium}`;
`& .${chipClasses.iconColorPrimary}`;
`& .${chipClasses.iconColorSecondary}`;
`& .${chipClasses.labelSmall}`;
`& .${chipClasses.labelMedium}`;
`& .${chipClasses.deleteIconSmall}`;
`& .${chipClasses.deleteIconMedium}`;
`& .${chipClasses.deleteIconColorPrimary}`;
`& .${chipClasses.deleteIconColorSecondary}`;
`& .${chipClasses.deleteIconFilledColorPrimary}`;
`& .${chipClasses.deleteIconFilledColorSecondary}`;
`& .${chipClasses.deleteIconOutlinedColorPrimary}`;
`& .${chipClasses.deleteIconOutlinedColorSecondary}`;
