import { chipClasses } from '@mui/material/Chip';

("&.MuiChip-clickable.MuiChip-colorPrimary");
("&.MuiChip-clickable.MuiChip-colorSecondary");
("&.MuiChip-deletable.MuiChip-colorPrimary");
("&.MuiChip-deletable.MuiChip-colorSecondary");
("&.MuiChip-outlined.MuiChip-colorPrimary");
("&.MuiChip-outlined.MuiChip-colorSecondary");
("&.MuiChip-filled.MuiChip-colorPrimary");
("&.MuiChip-filled.MuiChip-colorSecondary");
("&.MuiChip-sizeSmall > .MuiChip-avatar");
("&.MuiChip-sizeMedium > .MuiChip-avatar");
("&.MuiChip-colorPrimary > .MuiChip-avatar");
("&.MuiChip-colorSecondary > .MuiChip-avatar");
("&.MuiChip-sizeSmall > .MuiChip-icon");
("&.MuiChip-sizeMedium > .MuiChip-icon");
("&.MuiChip-colorPrimary > .MuiChip-icon");
("&.MuiChip-colorSecondary > .MuiChip-icon");
("&.MuiChip-sizeSmall > .MuiChip-label");
("&.MuiChip-sizeMedium > .MuiChip-label");
("&.MuiChip-sizeSmall > .MuiChip-deleteIcon");
("&.MuiChip-sizeMedium > .MuiChip-deleteIcon");
("&.MuiChip-colorPrimary > .MuiChip-deleteIcon");
("&.MuiChip-colorSecondary > .MuiChip-deleteIcon");
("&.MuiChip-filled.MuiChip-colorPrimary > .MuiChip-deleteIcon");
("&.MuiChip-filled.MuiChip-colorSecondary > .MuiChip-deleteIcon");
("&.MuiChip-outlined.MuiChip-colorPrimary > .MuiChip-deleteIcon");
("&.MuiChip-outlined.MuiChip-colorSecondary > .MuiChip-deleteIcon");
`&.${chipClasses.clickable}.${chipClasses.colorPrimary}`;
`&.${chipClasses.clickable}.${chipClasses.colorSecondary}`;
`&.${chipClasses.deletable}.${chipClasses.colorPrimary}`;
`&.${chipClasses.deletable}.${chipClasses.colorSecondary}`;
`&.${chipClasses.outlined}.${chipClasses.colorPrimary}`;
`&.${chipClasses.outlined}.${chipClasses.colorSecondary}`;
`&.${chipClasses.filled}.${chipClasses.colorPrimary}`;
`&.${chipClasses.filled}.${chipClasses.colorSecondary}`;
`&.${chipClasses.sizeSmall} > .${chipClasses.avatar}`;
`&.${chipClasses.sizeMedium} > .${chipClasses.avatar}`;
`&.${chipClasses.colorPrimary} > .${chipClasses.avatar}`;
`&.${chipClasses.colorSecondary} > .${chipClasses.avatar}`;
`&.${chipClasses.sizeSmall} > .${chipClasses.icon}`;
`&.${chipClasses.sizeMedium} > .${chipClasses.icon}`;
`&.${chipClasses.colorPrimary} > .${chipClasses.icon}`;
`&.${chipClasses.colorSecondary} > .${chipClasses.icon}`;
`&.${chipClasses.sizeSmall} > .${chipClasses.label}`;
`&.${chipClasses.sizeMedium} > .${chipClasses.label}`;
`&.${chipClasses.sizeSmall} > .${chipClasses.deleteIcon}`;
`&.${chipClasses.sizeMedium} > .${chipClasses.deleteIcon}`;
`&.${chipClasses.colorPrimary} > .${chipClasses.deleteIcon}`;
`&.${chipClasses.colorSecondary} > .${chipClasses.deleteIcon}`;
`&.${chipClasses.filled}.${chipClasses.colorPrimary} > .${chipClasses.deleteIcon}`;
`&.${chipClasses.filled}.${chipClasses.colorSecondary} > .${chipClasses.deleteIcon}`;
`&.${chipClasses.outlined}.${chipClasses.colorPrimary} > .${chipClasses.deleteIcon}`;
`&.${chipClasses.outlined}.${chipClasses.colorSecondary} > .${chipClasses.deleteIcon}`;
