/* eslint-disable no-console */
/**
 * Builds the accessibility conformance reports and the library-level scorecard.
 *
 * Each `packages/mui-material/src/<Component>/accessibility.json` rates the
 * component against WCAG 2.2 Level A and AA. It is the only source. From it,
 * this script writes:
 *
 * - `<Component>/accessibility.md`, the human-readable report
 * - the `Reports` table in `packages/mui-material/src/accessibility.md`
 * - `packages/mui-material/src/manual-testing.md`, the manual checklist
 * - the summary tables on the public conformance page
 * - `docs/data/material/getting-started/accessibility/scorecard.json`, the
 *   machine-readable rollup behind the tables.
 *
 * Run with `pnpm a11y:scorecard`. With `--check`, it writes nothing and exits
 * non-zero when an output is stale. Both modes fail when a data file is invalid.
 */
import fs from 'fs/promises';
import {
  checklistPath,
  docsPagePath,
  format,
  indexPath,
  packageJsonPath,
  readOptional,
  relative,
  replaceBlock,
  scorecardPath,
} from './files.mjs';
import readReports from './read.mjs';
import validateReport from './validate.mjs';
import {
  countCriteria,
  resolveCriteria,
  rollUpCriteria,
  summarize,
  summarizeRollup,
} from './rollup.mjs';
import {
  renderDocsAbout,
  renderDocsRollup,
  renderDocsTable,
  renderIndexTable,
  renderManualChecklist,
  renderReport,
} from './render.mjs';

async function run(argv) {
  const check = argv.includes('--check');
  const sources = await readReports();
  if (sources.length === 0) {
    throw new Error('No accessibility.json reports found under packages/mui-material/src');
  }

  const violations = (await Promise.all(sources.map(validateReport))).flat();
  if (violations.length > 0) {
    console.error('Accessibility report data is invalid:\n');
    violations.forEach((violation) => console.error(`  ${violation}`));
    process.exit(1);
  }

  const reports = sources.map((source) => {
    const criteria = resolveCriteria(source.data);
    return {
      ...source,
      criteria,
      counts: countCriteria(source.data, criteria),
      summary: summarize(criteria),
    };
  });
  const criteria = rollUpCriteria(reports);
  const totals = summarizeRollup(criteria);

  const scorecard = {
    // Regenerated by scripts/a11yScorecard — do not edit by hand.
    standard: 'WCAG 2.2 Level A and AA',
    componentCount: reports.length,
    totals,
    criteria,
    components: reports.map((report) => ({
      component: report.component,
      counts: report.counts,
      gaps: report.data.knownGaps.items,
      criteria: report.criteria.map(
        ({ number, name, level, conformance, responsibility, group, flagged }) => ({
          number,
          name,
          level,
          conformance,
          responsibility,
          group,
          flagged,
        }),
      ),
      summary: report.summary,
    })),
  };

  // Every output is committed, so it has to match what Prettier would produce.
  const outputs = [
    ...reports.map((report) => ({
      filepath: report.reportPath,
      render: () => renderReport(report),
    })),
    {
      filepath: indexPath,
      render: async () =>
        replaceBlock(await fs.readFile(indexPath, 'utf8'), renderIndexTable(reports), indexPath),
    },
    { filepath: scorecardPath, render: () => JSON.stringify(scorecard, null, 2) },
    { filepath: checklistPath, render: () => renderManualChecklist(reports) },
    {
      filepath: docsPagePath,
      render: async () => {
        const { version } = JSON.parse(await fs.readFile(packageJsonPath, 'utf8'));
        let page = await fs.readFile(docsPagePath, 'utf8');
        page = replaceBlock(page, renderDocsTable(reports), docsPagePath);
        page = replaceBlock(page, renderDocsAbout(version), docsPagePath, 'scorecard-about');
        page = replaceBlock(page, renderDocsRollup(totals), docsPagePath, 'scorecard-rollup');
        return page;
      },
    },
  ];

  const results = await Promise.all(
    outputs.map(async ({ filepath, render }) => ({
      filepath,
      current: await readOptional(filepath),
      next: await format(await render(), filepath),
    })),
  );
  const stale = results.filter(({ current, next }) => current !== next);

  if (check) {
    if (stale.length > 0) {
      console.error('Accessibility scorecard is out of date:\n');
      stale.forEach(({ filepath }) => console.error(`  ${relative(filepath)}`));
      console.error('\nRun `pnpm a11y:scorecard` and commit the result.');
      process.exit(1);
    }
    console.log(`Accessibility scorecard is up to date (${reports.length} components).`);
    return;
  }

  await Promise.all(stale.map(({ filepath, next }) => fs.writeFile(filepath, next)));

  console.log(
    `Scorecard updated for ${reports.length} components (${stale.length} files changed):`,
  );
  console.log(
    `  ${totals.rated} criteria rated: ✅ ${totals.supports}  ⚠️ ${totals.partiallySupports}  ❌ ${totals.doesNotSupport}  🚩 ${totals.flagged}`,
  );
}

run(process.argv.slice(2)).catch((error) => {
  console.error(error);
  process.exit(1);
});
