import { CONFORMANCE_SYMBOLS, GROUP_HEADINGS, RESPONSIBILITY_SYMBOLS } from './wcag.mjs';

const REPORT_BASE = 'https://github.com/mui/material-ui/blob/master/packages/mui-material/src';

const bullets = (items) => items.map((item) => `- ${item}`).join('\n');

/** `{ intro?: string[], items: string[] }` → paragraphs, then a bullet list. */
const listSection = ({ intro = [], items }) =>
  [...intro, ...(items.length > 0 ? [bullets(items)] : [])].join('\n\n');

/** The count table at the top of each component report. */
function renderCounts(counts, inheritedFrom) {
  const rows = [
    ['✅ Supports', counts.supports],
    ['⚠️ Partially Supports', counts.partiallySupports],
    ['❌ Does Not Support', counts.doesNotSupport],
    ['➖ Not Applicable', counts.notApplicable],
  ];
  if (counts.inherited !== undefined) {
    rows.push([`↗ Inherited (see ${inheritedFrom})`, counts.inherited]);
  }
  rows.push(['🚩 Flagged', `${counts.flagged}/${counts.rated}`]);

  return [
    '| Result | Count |',
    '| :----- | :---- |',
    ...rows.map(([label, value]) => `| ${label} | ${value} |`),
  ].join('\n');
}

function renderCriterion(criterion) {
  const status = [
    ...(criterion.flagged ? ['🚩'] : []),
    `${CONFORMANCE_SYMBOLS[criterion.conformance]} ${criterion.conformance}`,
    `${RESPONSIBILITY_SYMBOLS[criterion.responsibility]} ${criterion.responsibility}`,
  ]
    .map((token) => `\`${token}\``)
    .join(' · ');

  const parts = [
    `#### ${criterion.number} ${criterion.name} · ${criterion.level}`,
    status,
    bullets(criterion.notes),
  ];
  if (criterion.details) {
    parts.push(criterion.details);
  }
  if (criterion.steps) {
    parts.push(
      '**Manual testing steps**',
      criterion.steps.map((step, index) => `${index + 1}. ${step}`).join('\n'),
      `**Pass:** ${criterion.pass}`,
    );
  }
  return parts.join('\n\n');
}

/** Renders `<Component>/accessibility.md` from its data file. */
export function renderReport(report) {
  const { component, data, criteria, counts } = report;
  const parts = [
    `<!-- Generated by \`pnpm a11y:scorecard\` from ${component}/accessibility.json. Edit the JSON file, not this file. -->`,
    `# ${data.title ?? component} accessibility conformance`,
    'Rated against WCAG 2.2 Level A and AA. See the [reports legend](../accessibility.md).',
    ...(data.intro ?? []),
    renderCounts(counts, data.inherited?.from),
    ...(data.countsNote ?? []),
    '## Known gaps',
    listSection(data.knownGaps),
    '## Success criteria',
  ];

  for (const [group, heading] of Object.entries(GROUP_HEADINGS)) {
    const inGroup = criteria.filter((criterion) => criterion.group === group);
    if (inGroup.length > 0) {
      parts.push(`### ${heading}`, ...inGroup.map(renderCriterion));
    }
  }

  if (data.inherited) {
    parts.push(
      `## Inherited from ${data.inherited.from}`,
      listSection({
        intro: data.inherited.intro,
        items: data.inherited.items.map((item) => item.text),
      }),
    );
  }
  parts.push(
    '## Not applicable',
    bullets(data.notApplicable.map((item) => item.text)),
    '## Level AAA',
    listSection(data.levelAAA),
    '## Scope and test environment',
    listSection(data.scope),
  );

  return `${parts.join('\n\n')}\n`;
}

/**
 * The `Reports` table in `packages/mui-material/src/accessibility.md`.
 *
 * No totals row: every component rates the same WCAG criteria, so a sum across
 * components counts each criterion once per component. The per-criterion
 * rollup in `scorecard.json` is the library-level view.
 */
export function renderIndexTable(reports) {
  const header = [
    '| Component | ✅ Supports | ⚠️ Partially Supports | ❌ Does Not Support | ➖ Not Applicable | ↗ Inherited | 🚩 Flagged |',
    '| :-------- | :---------- | :-------------------- | :------------------ | :---------------- | :---------- | :--------- |',
  ];

  const rows = reports.map(({ component, counts }) => {
    const link = `[${component}](./${component}/accessibility.md)`;
    const cell = (key) => counts[key] ?? '—';
    return `| ${link} | ${cell('supports')} | ${cell('partiallySupports')} | ${cell('doesNotSupport')} | ${cell('notApplicable')} | ${cell('inherited')} | ${counts.flagged}/${counts.rated} |`;
  });

  return [...header, ...rows].join('\n');
}

/**
 * The report metadata on the public conformance page. A conformance report is
 * a statement about one release, so it names the package version. The version
 * comes from package.json, so `release:version` regenerates it on each bump.
 */
export function renderDocsAbout(version) {
  return [
    '| Field | Value |',
    '| :---- | :---- |',
    '| Product | Material\u00a0UI (`@mui/material`) |',
    '| Product type | React component library (software) |',
    `| Version assessed | \`@mui/material\` v${version} |`,
    '| Vendor | MUI |',
    '| Standards applied | WCAG 2.2 Level A and AA |',
    '| Report type | Self-assessment, published as source-controlled documentation |',
  ].join('\n');
}

/**
 * The library-level result on the public conformance page. It is generated so
 * that `--check` catches it when a report changes a rating.
 */
export function renderDocsRollup(totals) {
  const headline =
    totals.doesNotSupport === 0
      ? '**No component records a ❌ Does Not Support rating for any Level A or AA criterion.**'
      : `**${totals.doesNotSupport} criteria record a ❌ Does Not Support rating in at least one component.**`;
  return [
    headline,
    '',
    `Rolled up to the library level, where each criterion takes the worst rating any assessed component receives, ${totals.rated} success criteria are exercised: **${totals.supports} Supports, ${totals.partiallySupports} Partially Supports, ${totals.doesNotSupport} Does Not Support.**`,
  ].join('\n');
}

/**
 * The summary table on the public conformance page. Detail lives in the
 * per-component reports, so this stays to counts plus a link.
 */
export function renderDocsTable(reports) {
  const header = [
    '| Component | Level A | Level AA | Rated | ✅ Supports | ⚠️ Partially Supports | Verified | Automated |',
    '| :-------- | ------: | -------: | ----: | ----------: | --------------------: | -------: | --------: |',
  ];

  const rows = reports.map(({ component, summary }) => {
    const link = `[${component}](${REPORT_BASE}/${component}/accessibility.md)`;
    return `| ${link} | ${summary.levelA} | ${summary.levelAA} | ${summary.rated} | ${summary.supports} | ${summary.partiallySupports} | ${summary.verified}/${summary.rated} | ${summary.automated} |`;
  });

  return [...header, ...rows].join('\n');
}

/**
 * Which kind of change puts a criterion at risk. The manual checklist is
 * grouped by this so a styling change does not send you through keyboard checks.
 */
const TRIGGERS = [
  ['Styling, theme, or palette', /^1\.4\./],
  ['DOM structure, roles, or ARIA', /^(1\.1\.|1\.3\.|4\.1\.)/],
  ['Keyboard, focus, or pointer handling', /^(2\.1\.|2\.4\.|2\.5\.|3\.2\.)/],
  ['Labels, errors, or validation', /^3\.3\./],
  ['Motion or timing', /^2\.2\./],
];

const triggerFor = (number) => TRIGGERS.find(([, pattern]) => pattern.test(number))?.[0] ?? 'Other';

/**
 * A criterion still needs a person when no deterministic test proves it, and
 * when it is the component's responsibility rather than the application's.
 */
const needsHuman = (criterion) =>
  criterion.group !== 'Automated' && criterion.responsibility !== 'Author';

/**
 * The pre-change checklist: every criterion a person still has to judge, using
 * the pass condition already written in the component report.
 */
export function renderManualChecklist(reports) {
  const lines = [
    '# Manual accessibility checks',
    '',
    'Generated by `pnpm a11y:scorecard`. Edit the `<Component>/accessibility.json` files, not this file.',
    '',
    'The accessibility checks a person still has to make by eye when changing a component.',
    'Anything not listed here is covered by a test — see [How it works](./accessibility.md#how-it-works).',
    '',
    'Two things are deliberately left out: criteria a deterministic test already proves',
    '(⚙️ Automated in the reports), and criteria that depend on the application rather than',
    'the component (○ Author).',
    '',
    '| Marker | Meaning |',
    '| :----- | :------ |',
    '| 🔍 | No automation. Check it by hand. |',
    '| 🔁 | Automation catches regressions; confirm the judgment still holds. |',
    '',
    '## What to re-check, by kind of change',
    '',
    'Run the rows matching what you touched, for the component you touched.',
    '',
    '| If your change touches… | Re-check |',
    '| :---------------------- | :------- |',
  ];

  const byTrigger = new Map([...TRIGGERS.map(([name]) => [name, new Set()]), ['Other', new Set()]]);
  for (const report of reports) {
    for (const criterion of report.criteria.filter(needsHuman)) {
      byTrigger.get(triggerFor(criterion.number)).add(`${criterion.number} ${criterion.name}`);
    }
  }
  for (const [name, criteria] of byTrigger) {
    const sorted = [...criteria].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
    if (sorted.length > 0) {
      lines.push(`| ${name} | ${sorted.join('; ')} |`);
    }
  }
  lines.push('');

  for (const report of reports) {
    const checks = report.criteria.filter(needsHuman);
    if (checks.length === 0) {
      continue;
    }
    lines.push(
      `## ${report.component}`,
      '',
      `${checks.length} check${checks.length === 1 ? '' : 's'} · full procedures in [\`${report.component}/accessibility.md\`](./${report.component}/accessibility.md)`,
      '',
    );
    for (const criterion of checks) {
      const marker = criterion.group === 'Manual' ? '🔍' : '🔁';
      const pass = criterion.pass ? ` — ${criterion.pass}` : '';
      lines.push(`- [ ] ${marker} **${criterion.number} ${criterion.name}**${pass}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
