Component.propTypes = {
  nullableComponent: PropTypes.elementType,
  nullableConstructor: PropTypes.elementType,
  nullableElement: PropTypes.element,
  nullableElementType: PropTypes.elementType,
  optionalComponent: PropTypes.elementType,
  optionalConstructor: PropTypes.elementType,
  optionalElement: PropTypes.element,
  optionalElementType: PropTypes.elementType,
  requiredComponent: PropTypes.elementType.isRequired,
  requiredConstructor: PropTypes.elementType.isRequired,
  requiredElement: PropTypes.element.isRequired,
  requiredElementType: PropTypes.elementType.isRequired,
  slots: PropTypes.shape({
    component: PropTypes.elementType,
    constructor: PropTypes.elementType,
    element: PropTypes.element,
    elementType: PropTypes.elementType,
  }),
  undefinedComponent: PropTypes.elementType,
  undefinedConstructor: PropTypes.elementType,
  undefinedElement: PropTypes.element,
  undefinedElementType: PropTypes.elementType,
};
