import type { Metadata } from 'next';
import { styled } from '@mui/zero-runtime';
import { Inter } from 'next/font/google';
import '@mui/zero-runtime/styles.css';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Html = styled.html({
  color: 'red',
});

const Body = styled.body({
  color: 'rgb(var(--foreground-rgb))',
  background: `linear-gradient(to bottom, transparent, rgb(var(--background-end-rgb))) rgb(var(--background-start-rgb))`,
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Html lang="en">
      <Body className={inter.className}>{children}</Body>
    </Html>
  );
}
