import React, { ComponentPropsWithRef, CSSProperties, ElementType } from 'react';
import PropTypes from 'prop-types';
import clsx from 'clsx';
import useSwitch, { UseSwitchProps } from './useSwitch';
import classes from './switchUnstyledClasses';
import ButtonUnstyled from '../ButtonUnstyled/ButtonUnstyled';

export interface SwitchUnstyledProps<
  TRoot extends ElementType,
  TThumb extends ElementType,
  TInput extends ElementType,
> extends UseSwitchProps {
  components?: {
    Root?: TRoot;
    Thumb?: TThumb;
    Input?: TInput;
  };

  componentsProps?: {
    root?: ComponentPropsWithRef<TRoot>;
    thumb?: ComponentPropsWithRef<TThumb>;
    input?: ComponentPropsWithRef<TInput>;
  };
}

const minimalRootStyles: CSSProperties = {
  position: 'relative',
};

const minimalInputStyles: CSSProperties = {
  position: 'absolute',
  width: '100%',
  height: '100%',
  top: 0,
  left: 0,
  opacity: 0,
  zIndex: 1,
  margin: 0,
};

const SwitchUnstyled = function SwitchUnstyled<
  TRoot extends ElementType = 'span',
  TThumb extends ElementType = 'span',
  TInput extends ElementType = 'input',
>(props: SwitchUnstyledProps<TRoot, TThumb, TInput>) {
  const { components = {}, componentsProps = {}, ...otherProps } = props;
  const Root = components.Root ?? 'span';
  const rootProps = componentsProps.root ?? ({} as React.ComponentPropsWithRef<TRoot>);
  const Thumb = components.Thumb ?? 'span';
  const thumbProps = componentsProps.thumb ?? ({} as React.ComponentPropsWithRef<TThumb>);
  const Input = components.Input ?? 'input';
  const inputProps = componentsProps.input ?? ({} as React.ComponentPropsWithRef<TInput>);

  const { getInputProps, isChecked, isDisabled } = useSwitch(otherProps);

  const computedClasses = {
    [classes.checked]: isChecked,
    [classes.disabled]: isDisabled,
  };

  return (
    <Root style={minimalRootStyles} {...rootProps} className={clsx(classes.root, computedClasses)}>
      <ButtonUnstyled
        components={{ Root: 'span' }}
        componentsProps={{ root: { role: undefined } }}
        tabIndex={-1}
        disabled={isDisabled}
        className={classes.button}
      >
        <Thumb {...thumbProps} className={classes.thumb} />
        <Input
          type="checkbox"
          style={minimalInputStyles}
          {...getInputProps(inputProps)}
          className={classes.input}
        />
      </ButtonUnstyled>
    </Root>
  );
};

SwitchUnstyled.propTypes /* remove-proptypes */ = {
  // ----------------------------- Warning --------------------------------
  // | These PropTypes are generated from the TypeScript type definitions |
  // |     To update them edit TypeScript types and run "yarn proptypes"  |
  // ----------------------------------------------------------------------
  /**
   * @ignore
   */
  components: PropTypes.shape({
    Input: PropTypes.oneOfType([
      PropTypes.oneOf([
        'a',
        'abbr',
        'address',
        'animate',
        'animateMotion',
        'animateTransform',
        'area',
        'article',
        'aside',
        'audio',
        'b',
        'base',
        'bdi',
        'bdo',
        'big',
        'blockquote',
        'body',
        'br',
        'button',
        'canvas',
        'caption',
        'circle',
        'cite',
        'clipPath',
        'code',
        'col',
        'colgroup',
        'data',
        'datalist',
        'dd',
        'defs',
        'del',
        'desc',
        'details',
        'dfn',
        'dialog',
        'div',
        'dl',
        'dt',
        'ellipse',
        'em',
        'embed',
        'feBlend',
        'feColorMatrix',
        'feComponentTransfer',
        'feComposite',
        'feConvolveMatrix',
        'feDiffuseLighting',
        'feDisplacementMap',
        'feDistantLight',
        'feDropShadow',
        'feFlood',
        'feFuncA',
        'feFuncB',
        'feFuncG',
        'feFuncR',
        'feGaussianBlur',
        'feImage',
        'feMerge',
        'feMergeNode',
        'feMorphology',
        'feOffset',
        'fePointLight',
        'feSpecularLighting',
        'feSpotLight',
        'feTile',
        'feTurbulence',
        'fieldset',
        'figcaption',
        'figure',
        'filter',
        'footer',
        'foreignObject',
        'form',
        'g',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'head',
        'header',
        'hgroup',
        'hr',
        'html',
        'i',
        'iframe',
        'image',
        'img',
        'input',
        'ins',
        'kbd',
        'keygen',
        'label',
        'legend',
        'li',
        'line',
        'linearGradient',
        'link',
        'main',
        'map',
        'mark',
        'marker',
        'mask',
        'menu',
        'menuitem',
        'meta',
        'metadata',
        'meter',
        'mpath',
        'nav',
        'noindex',
        'noscript',
        'object',
        'ol',
        'optgroup',
        'option',
        'output',
        'p',
        'param',
        'path',
        'pattern',
        'picture',
        'polygon',
        'polyline',
        'pre',
        'progress',
        'q',
        'radialGradient',
        'rect',
        'rp',
        'rt',
        'ruby',
        's',
        'samp',
        'script',
        'section',
        'select',
        'slot',
        'small',
        'source',
        'span',
        'stop',
        'strong',
        'style',
        'sub',
        'summary',
        'sup',
        'svg',
        'switch',
        'symbol',
        'table',
        'tbody',
        'td',
        'template',
        'text',
        'textarea',
        'textPath',
        'tfoot',
        'th',
        'thead',
        'time',
        'title',
        'tr',
        'track',
        'tspan',
        'u',
        'ul',
        'use',
        'var',
        'video',
        'view',
        'wbr',
        'webview',
      ]),
      PropTypes.func,
    ]),
    Root: PropTypes.oneOfType([
      PropTypes.oneOf([
        'a',
        'abbr',
        'address',
        'animate',
        'animateMotion',
        'animateTransform',
        'area',
        'article',
        'aside',
        'audio',
        'b',
        'base',
        'bdi',
        'bdo',
        'big',
        'blockquote',
        'body',
        'br',
        'button',
        'canvas',
        'caption',
        'circle',
        'cite',
        'clipPath',
        'code',
        'col',
        'colgroup',
        'data',
        'datalist',
        'dd',
        'defs',
        'del',
        'desc',
        'details',
        'dfn',
        'dialog',
        'div',
        'dl',
        'dt',
        'ellipse',
        'em',
        'embed',
        'feBlend',
        'feColorMatrix',
        'feComponentTransfer',
        'feComposite',
        'feConvolveMatrix',
        'feDiffuseLighting',
        'feDisplacementMap',
        'feDistantLight',
        'feDropShadow',
        'feFlood',
        'feFuncA',
        'feFuncB',
        'feFuncG',
        'feFuncR',
        'feGaussianBlur',
        'feImage',
        'feMerge',
        'feMergeNode',
        'feMorphology',
        'feOffset',
        'fePointLight',
        'feSpecularLighting',
        'feSpotLight',
        'feTile',
        'feTurbulence',
        'fieldset',
        'figcaption',
        'figure',
        'filter',
        'footer',
        'foreignObject',
        'form',
        'g',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'head',
        'header',
        'hgroup',
        'hr',
        'html',
        'i',
        'iframe',
        'image',
        'img',
        'input',
        'ins',
        'kbd',
        'keygen',
        'label',
        'legend',
        'li',
        'line',
        'linearGradient',
        'link',
        'main',
        'map',
        'mark',
        'marker',
        'mask',
        'menu',
        'menuitem',
        'meta',
        'metadata',
        'meter',
        'mpath',
        'nav',
        'noindex',
        'noscript',
        'object',
        'ol',
        'optgroup',
        'option',
        'output',
        'p',
        'param',
        'path',
        'pattern',
        'picture',
        'polygon',
        'polyline',
        'pre',
        'progress',
        'q',
        'radialGradient',
        'rect',
        'rp',
        'rt',
        'ruby',
        's',
        'samp',
        'script',
        'section',
        'select',
        'slot',
        'small',
        'source',
        'span',
        'stop',
        'strong',
        'style',
        'sub',
        'summary',
        'sup',
        'svg',
        'switch',
        'symbol',
        'table',
        'tbody',
        'td',
        'template',
        'text',
        'textarea',
        'textPath',
        'tfoot',
        'th',
        'thead',
        'time',
        'title',
        'tr',
        'track',
        'tspan',
        'u',
        'ul',
        'use',
        'var',
        'video',
        'view',
        'wbr',
        'webview',
      ]),
      PropTypes.func,
    ]),
    Thumb: PropTypes.oneOfType([
      PropTypes.oneOf([
        'a',
        'abbr',
        'address',
        'animate',
        'animateMotion',
        'animateTransform',
        'area',
        'article',
        'aside',
        'audio',
        'b',
        'base',
        'bdi',
        'bdo',
        'big',
        'blockquote',
        'body',
        'br',
        'button',
        'canvas',
        'caption',
        'circle',
        'cite',
        'clipPath',
        'code',
        'col',
        'colgroup',
        'data',
        'datalist',
        'dd',
        'defs',
        'del',
        'desc',
        'details',
        'dfn',
        'dialog',
        'div',
        'dl',
        'dt',
        'ellipse',
        'em',
        'embed',
        'feBlend',
        'feColorMatrix',
        'feComponentTransfer',
        'feComposite',
        'feConvolveMatrix',
        'feDiffuseLighting',
        'feDisplacementMap',
        'feDistantLight',
        'feDropShadow',
        'feFlood',
        'feFuncA',
        'feFuncB',
        'feFuncG',
        'feFuncR',
        'feGaussianBlur',
        'feImage',
        'feMerge',
        'feMergeNode',
        'feMorphology',
        'feOffset',
        'fePointLight',
        'feSpecularLighting',
        'feSpotLight',
        'feTile',
        'feTurbulence',
        'fieldset',
        'figcaption',
        'figure',
        'filter',
        'footer',
        'foreignObject',
        'form',
        'g',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'head',
        'header',
        'hgroup',
        'hr',
        'html',
        'i',
        'iframe',
        'image',
        'img',
        'input',
        'ins',
        'kbd',
        'keygen',
        'label',
        'legend',
        'li',
        'line',
        'linearGradient',
        'link',
        'main',
        'map',
        'mark',
        'marker',
        'mask',
        'menu',
        'menuitem',
        'meta',
        'metadata',
        'meter',
        'mpath',
        'nav',
        'noindex',
        'noscript',
        'object',
        'ol',
        'optgroup',
        'option',
        'output',
        'p',
        'param',
        'path',
        'pattern',
        'picture',
        'polygon',
        'polyline',
        'pre',
        'progress',
        'q',
        'radialGradient',
        'rect',
        'rp',
        'rt',
        'ruby',
        's',
        'samp',
        'script',
        'section',
        'select',
        'slot',
        'small',
        'source',
        'span',
        'stop',
        'strong',
        'style',
        'sub',
        'summary',
        'sup',
        'svg',
        'switch',
        'symbol',
        'table',
        'tbody',
        'td',
        'template',
        'text',
        'textarea',
        'textPath',
        'tfoot',
        'th',
        'thead',
        'time',
        'title',
        'tr',
        'track',
        'tspan',
        'u',
        'ul',
        'use',
        'var',
        'video',
        'view',
        'wbr',
        'webview',
      ]),
      PropTypes.func,
    ]),
  }),
  /**
   * @ignore
   */
  componentsProps: PropTypes.object,
} as any;

export default SwitchUnstyled;
