# https://dependabot.com/docs/config-file/
# validate with https://dependabot.com/docs/config-file/validator/
version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    version_requirement_updates: 'auto'
    default_labels:
      - 'dependencies'
      - 'worktree'
    ignored_updates:
      - match:
          # These should be grouped. Maintainer advise: Watch https://github.com/babel/babel
          # for new releases and file a PR if you got time.
          dependency_name: '@babel/*'
      - match:
          # Can't upgrade while using `@material-ui/pickers@3.x`
          dependency_name: '@date-io/core'
      - match:
          # Can't upgrade while using `@material-ui/pickers@3.x`
          dependency_name: '@date-io/date-fns'
      - match:
          # as of 3.x prevaled code is no longer transpiled
          dependency_name: 'babel-plugin-preval'
          version_requirement: '>= 3.0'
      - match:
          # https://github.com/mui-org/material-ui/pull/17604#issuecomment-536262291
          dependency_name: 'core-js'
      - match:
          # These should be grouped once a PR for `jss` is opened
          dependency_name: 'jss-*'
      - match:
          # 2.0 started using ES modules instead of CommonJS modules
          dependency_name: 'raw-loader'
      # not ignoring `react`. We'll hijack those PRs and also upgrade the other
      # packages in the facebook/react repository
      - match:
          # should be grouped with `react`
          dependency_name: 'react-dom'
      - match:
          # should be grouped with `react`
          dependency_name: 'react-is'
      - match:
          # should be grouped with `react`
          dependency_name: 'react-test-renderer'
      - match:
          # breaks `yarn size:why`
          dependency_name: 'size-limit'
      - match:
          # https://github.com/mui-org/material-ui/pull/17168#issuecomment-524861427
          dependency_name: 'tslint'
          version_requirement: '5.x'
      - match:
          # as of 3.x requires node@10. We can upgrade once we do as well
          dependency_name: 'url-loader'
          version_requirement: '>= 3.0'
