export default {
  '@mui/material': [
    'Accordion',
    'AccordionActions',
    'AccordionDetails',
    'AccordionSummary',
    'Alert',
    'AlertTitle',
    'AppBar',
    'Autocomplete',
    'Avatar',
    'Backdrop',
    'Badge',
    'BottomNavigation',
    'BottomNavigationAction',
    'Box',
    'Breadcrumbs',
    'Button',
    'ButtonBase',
    'ButtonGroup',
    'Card',
    'CardActionArea',
    'CardActions',
    'CardContent',
    'CardHeader',
    'CardMedia',
    'Checkbox',
    'Chip',
    'CircularProgress',
    'ClickAwayListener',
    'Collapse',
    'colors',
    'Container',
    'CssBaseline',
    'Dialog',
    'DialogActions',
    'DialogContent',
    'DialogContentText',
    'DialogTitle',
    'Divider',
    'Drawer',
    'Fab',
    'Fade',
    'FilledInput',
    'FormControl',
    'FormControlLabel',
    'FormGroup',
    'FormHelperText',
    'FormLabel',
    'Grid',
    'Grow',
    'Icon',
    'IconButton',
    'ImageList',
    'ImageListItem',
    'ImageListItemBar',
    'Input',
    'InputAdornment',
    'InputBase',
    'InputLabel',
    'LinearProgress',
    'Link',
    'List',
    'ListItem',
    'ListItemAvatar',
    'ListItemIcon',
    'ListItemSecondaryAction',
    'ListItemText',
    'ListSubheader',
    'Menu',
    'MenuItem',
    'MenuList',
    'MobileStepper',
    'Modal',
    'NativeSelect',
    'NoSsr',
    'OutlinedInput',
    'Pagination',
    'PaginationItem',
    'Paper',
    'Popover',
    'Popper',
    'Portal',
    'Radio',
    'RadioGroup',
    'Rating',
    'ScopedCssBaseline',
    'Select',
    'Skeleton',
    'Slide',
    'Slider',
    'Snackbar',
    'SnackbarContent',
    'SpeedDial',
    'SpeedDialAction',
    'SpeedDialIcon',
    'Step',
    'StepButton',
    'StepConnector',
    'StepContent',
    'StepIcon',
    'StepLabel',
    'Stepper',
    'styles',
    'SvgIcon',
    'SwipeableDrawer',
    'Switch',
    'Tab',
    'Table',
    'TableBody',
    'TableCell',
    'TableContainer',
    'TableFooter',
    'TableHead',
    'TablePagination',
    'TableRow',
    'TableSortLabel',
    'Tabs',
    'TabScrollButton',
    'TextareaAutosize',
    'TextField',
    'ToggleButton',
    'ToggleButtonGroup',
    'Toolbar',
    'Tooltip',
    'Typography',
    'Unstable_TrapFocus',
    'useAutocomplete',
    'useMediaQuery',
    'usePagination',
    'useScrollTrigger',
    'utils',
    'Zoom',
  ],
  '@mui/icons-material': [
    // Icons are generated.
    // So the behavior of a single item should be equivalent to all icons.
    'Accessibility',
  ],
  '@mui/lab': [
    'Alert',
    'AlertTitle',
    'Autocomplete',
    'AvatarGroup',
    'LoadingButton',
    'Pagination',
    'PaginationItem',
    'Rating',
    'Skeleton',
    'SpeedDial',
    'SpeedDialAction',
    'SpeedDialIcon',
    'TabContext',
    'TabList',
    'TabPanel',
    // types only
    // 'themeAugmentation',
    'Timeline',
    'TimelineConnector',
    'TimelineContent',
    'TimelineDot',
    'TimelineItem',
    'TimelineOppositeContent',
    'TimelineSeparator',
    'ToggleButton',
    'ToggleButtonGroup',
    'TreeItem',
    'TreeView',
    'useAutocomplete',
  ],
  '@mui/styles': [
    'createGenerateClassName',
    'createStyles',
    // Types only
    // 'defaultTheme',
    // private
    // 'getStylesCreator',
    'getThemeProps',
    'jssPreset',
    'makeStyles',
    'mergeClasses',
    'propsToClassKey',
    'ServerStyleSheets',
    'styled',
    'StylesProvider',
    'ThemeProvider',
    'useTheme',
    'useThemeVariants',
    'withStyles',
    'withTheme',
  ],
  '@mui/system': [
    'borders',
    'breakpoints',
    'compose',
    'display',
    'flexbox',
    'grid',
    // private
    // 'memoize',
    // 'merge',
    'palette',
    'positions',
    // private
    // 'responsivePropType',
    'shadows',
    'sizing',
    'spacing',
    'style',
    // private
    // 'styleFunctionSx',
    'typography',
  ],
  '@mui/utils': [
    'chainPropTypes',
    'deepmerge',
    'elementAcceptingRef',
    'elementTypeAcceptingRef',
    'exactProp',
    'formatMuiErrorMessage',
    'getDisplayName',
    'HTMLElementType',
    'ponyfillGlobal',
    'refType',
  ],
};
