import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@mui/material-pigment-css/styles.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Material UI x Pigment CSS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ "--font-family": roboto.style.fontFamily } as any}>
        {children}
      </body>
    </html>
  );
}
