const componentAreas = {
  inputs: [
    'Autocomplete',
    'Button',
    'ButtonBase',
    'ButtonGroup',
    'Checkbox',
    'Fab',
    'FilledInput',
    'FormControl',
    'FormControlLabel',
    'FormGroup',
    'FormHelperText',
    'FormLabel',
    'IconButton',
    'Input',
    'InputAdornment',
    'InputBase',
    'InputLabel',
    'NativeSelect',
    'OutlinedInput',
    'Radio',
    'RadioGroup',
    'Rating',
    'Select',
    'Slider',
    'Switch',
    'TextField',
    'ToggleButton',
    'ToggleButtonGroup',
    'useTouchRipple',
  ],
  dataDisplay: [
    'Avatar',
    'AvatarGroup',
    'Badge',
    'Chip',
    'Divider',
    'Icon',
    'List',
    'ListItem',
    'ListItemAvatar',
    'ListItemButton',
    'ListItemIcon',
    'ListItemSecondaryAction',
    'ListItemText',
    'ListSubheader',
    'SvgIcon',
    'Table',
    'TableBody',
    'TableCell',
    'TableContainer',
    'TableFooter',
    'TableHead',
    'TablePagination',
    'TableRow',
    'TableSortLabel',
    'Tooltip',
    'Typography',
  ],
  feedback: [
    'Alert',
    'AlertTitle',
    'Backdrop',
    'CircularProgress',
    'Dialog',
    'DialogActions',
    'DialogContent',
    'DialogContentText',
    'DialogTitle',
    'LinearProgress',
    'Snackbar',
    'SnackbarContent',
    'Skeleton',
  ],
  surfaces: [
    'Accordion',
    'AccordionActions',
    'AccordionDetails',
    'AccordionSummary',
    'AppBar',
    'Card',
    'CardActionArea',
    'CardActions',
    'CardContent',
    'CardHeader',
    'CardMedia',
    'Paper',
    'Toolbar',
    'useScrollTrigger',
  ],
  navigation: [
    'BottomNavigation',
    'BottomNavigation',
    'Breadcrumbs',
    'Drawer',
    'Link',
    'Menu',
    'MenuItem',
    'MenuList',
    'MobileStepper',
    'Pagination',
    'PaginationItem',
    'SpeedDial',
    'SpeedDialAction',
    'SpeedDialIcon',
    'Step',
    'StepButton',
    'StepConnector',
    'StepContent',
    'StepIcon',
    'StepLabel',
    'Stepper',
    'SwipeableDrawer',
    'Tab',
    'Tabs',
    'TabScrollButton',
  ],
  layout: [
    'Box',
    'Container',
    'Grid',
    'Hidden',
    'ImageList',
    'ImageListItem',
    'ImageListItemBar',
    'Stack',
    'Unstable_Grid2',
  ],
  utils: [
    'ClickAwayListener',
    'Collapse',
    'CssBaseline',
    'Fade',
    'GlobalStyles',
    'Grow',
    'Modal',
    'NoSsr',
    'Popover',
    'Popper',
    'Portal',
    'ScopedCssBaseline',
    'Slide',
    'TextareaAutosize',
    'transitions',
    'TrapFocus',
    'Unstable_TrapFocus',
    'useMediaQuery',
    'Zoom',
  ],
};

const areaMaintainers = {
  inputs: ['michaldudak', 'mnajdova'],
  dataDisplay: ['siriwatknp', 'michaldudak'],
  feedback: ['siriwatknp', 'hbjORbj'],
  surfaces: ['siriwatknp', 'hbjORbj'],
  navigation: ['mnajdova', 'michaldudak'],
  layout: ['siriwatknp', 'hbjORbj'],
  utils: ['mnajdova', 'michaldudak'],
};

const packageMaintainers = {};
