/**
 * Generates `default-theme.css` — a static CSS file containing all MUI CSS
 * custom properties for the default light and dark color schemes.
 *
 * Usage:
 *   pnpm -F @mui/material build:theme-css
 *
 * The output file is meant to be imported by applications that want to consume
 * MUI components via pre-built CSS files (no Emotion / styled-components) and
 * do not need runtime theme injection. Color-scheme switching is handled by
 * toggling `data-mui-color-scheme="dark"` on `document.documentElement`.
 *
 * Run with tsx so TypeScript source can be imported directly without a prior
 * build step:
 *   node_modules/.bin/tsx packages/mui-material/scripts/buildDefaultThemeCss.mts
 */
import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import createTheme from '../src/styles/createTheme.js';
import styleSheetsToString from '@mui/system/cssVars/styleSheetsToString.js';

// When bundled with esbuild the file runs from /tmp; use process.env.OUTFILE or
// resolve relative to the current working directory (repo root) instead.
const outFile = process.env.OUTFILE
  ? resolve(process.env.OUTFILE)
  : join(process.cwd(), 'packages/mui-material/default-theme.css');

// Build the default MUI theme with CSS variables enabled.
// `colorSchemeSelector: 'data-mui-color-scheme'` makes the dark-scheme
// variables live under `[data-mui-color-scheme="dark"]`, which is the
// convention used by both MUI's own toggle helpers and the Tailwind
// `dark:` variant defined in docs/pages/global.css.
const theme = createTheme({
  cssVariables: { colorSchemeSelector: 'data-mui-color-scheme' },
  colorSchemes: { light: true, dark: true },
});

const themeWithVars = theme as typeof theme & {
  generateStyleSheets?: () => Record<string, any>[];
};

if (typeof themeWithVars.generateStyleSheets !== 'function') {
  throw new Error(
    'theme.generateStyleSheets is not a function. ' +
      'Make sure the theme is created with `cssVariables: true`.',
  );
}

const css = styleSheetsToString(themeWithVars.generateStyleSheets());

const header = [
  '/*',
  ' * MUI default theme — generated by scripts/buildDefaultThemeCss.mts',
  ' * DO NOT EDIT MANUALLY.',
  ' *',
  ' * Import this file once at the root of your application:',
  ' *   import "@mui/material/default-theme.css";',
  ' *',
  ' * Then toggle dark mode by setting:',
  ' *   document.documentElement.setAttribute("data-mui-color-scheme", "dark");',
  ' */',
  '',
].join('\n');

writeFileSync(outFile, header + css, 'utf8');
// eslint-disable-next-line no-console
console.log(`✔  Written ${outFile}`);
