<div>
  <Dialog
    onEnter={onEnter}
    onEntered={onEntered}
    onEntering={onEntering}
    onExit={onExit}
    onExited={onExited}
    onExiting={myOnExiting}
  />
  <Menu
    onEnter={onEnter}
    onEntered={onEntered}
    onEntering={onEntering}
    onExit={onExit}
    onExited={onExited}
    onExiting={myOnExiting}
  />
  <Popover
    onEnter={onEnter}
    onEntered={onEntered}
    onEntering={onEntering}
    onExit={onExit}
    onExited={onExited}
    onExiting={myOnExiting}
  />
  <Snackbar
    onEnter={onEnter}
    onEntered={onEntered}
    onEntering={onEntering}
    onExit={onExit}
    onExited={onExited}
    onExiting={myOnExiting}
  />
</div>
