import { buttonClasses } from '@mui/material/Button';

('&.MuiButton-textInherit');
('&.MuiButton-textPrimary');
('&.MuiButton-textSecondary');
('&.MuiButton-textSuccess');
('&.MuiButton-textError');
('&.MuiButton-textInfo');
('&.MuiButton-textWarning');
('&.MuiButton-outlinedInherit');
('&.MuiButton-outlinedPrimary');
('&.MuiButton-outlinedSecondary');
('&.MuiButton-outlinedSuccess');
('&.MuiButton-outlinedError');
('&.MuiButton-outlinedInfo');
('&.MuiButton-outlinedWarning');
('&.MuiButton-containedInherit');
('&.MuiButton-containedPrimary');
('&.MuiButton-containedSecondary');
('&.MuiButton-containedSuccess');
('&.MuiButton-containedError');
('&.MuiButton-containedInfo');
('&.MuiButton-containedWarning');
('&.MuiButton-textSizeSmall');
('&.MuiButton-textSizeMedium');
('&.MuiButton-textSizeLarge');
('&.MuiButton-outlinedSizeSmall');
('&.MuiButton-outlinedSizeMedium');
('&.MuiButton-outlinedSizeLarge');
('&.MuiButton-containedSizeSmall');
('&.MuiButton-containedSizeMedium');
('&.MuiButton-containedSizeLarge');
('& .MuiButton-iconSizeSmall');
('& .MuiButton-iconSizeMedium');
('& .MuiButton-iconSizeLarge');
`&.${buttonClasses.textInherit}`;
`&.${buttonClasses.textPrimary}`;
`&.${buttonClasses.textSecondary}`;
`&.${buttonClasses.textSuccess}`;
`&.${buttonClasses.textError}`;
`&.${buttonClasses.textInfo}`;
`&.${buttonClasses.textWarning}`;
`&.${buttonClasses.outlinedInherit}`;
`&.${buttonClasses.outlinedPrimary}`;
`&.${buttonClasses.outlinedSecondary}`;
`&.${buttonClasses.outlinedSuccess}`;
`&.${buttonClasses.outlinedError}`;
`&.${buttonClasses.outlinedInfo}`;
`&.${buttonClasses.outlinedWarning}`;
`&.${buttonClasses.containedInherit}`;
`&.${buttonClasses.containedPrimary}`;
`&.${buttonClasses.containedSecondary}`;
`&.${buttonClasses.containedSuccess}`;
`&.${buttonClasses.containedError}`;
`&.${buttonClasses.containedInfo}`;
`&.${buttonClasses.containedWarning}`;
`&.${buttonClasses.textSizeSmall}`;
`&.${buttonClasses.textSizeMedium}`;
`&.${buttonClasses.textSizeLarge}`;
`&.${buttonClasses.outlinedSizeSmall}`;
`&.${buttonClasses.outlinedSizeMedium}`;
`&.${buttonClasses.outlinedSizeLarge}`;
`&.${buttonClasses.containedSizeSmall}`;
`&.${buttonClasses.containedSizeMedium}`;
`&.${buttonClasses.containedSizeLarge}`;
`& .${buttonClasses.iconSizeSmall}`;
`& .${buttonClasses.iconSizeMedium}`;
`& .${buttonClasses.iconSizeLarge}`;
