import { buttonClasses } from '@mui/material/Button';

("&.MuiButton-text.MuiButton-colorInherit");
("&.MuiButton-text.MuiButton-colorPrimary");
("&.MuiButton-text.MuiButton-colorSecondary");
("&.MuiButton-text.MuiButton-colorSuccess");
("&.MuiButton-text.MuiButton-colorError");
("&.MuiButton-text.MuiButton-colorInfo");
("&.MuiButton-text.MuiButton-colorWarning");
("&.MuiButton-outlined.MuiButton-colorInherit");
("&.MuiButton-outlined.MuiButton-colorPrimary");
("&.MuiButton-outlined.MuiButton-colorSecondary");
("&.MuiButton-outlined.MuiButton-colorSuccess");
("&.MuiButton-outlined.MuiButton-colorError");
("&.MuiButton-outlined.MuiButton-colorInfo");
("&.MuiButton-outlined.MuiButton-colorWarning");
("&.MuiButton-contained.MuiButton-colorInherit");
("&.MuiButton-contained.MuiButton-colorPrimary");
("&.MuiButton-contained.MuiButton-colorSecondary");
("&.MuiButton-contained.MuiButton-colorSuccess");
("&.MuiButton-contained.MuiButton-colorError");
("&.MuiButton-contained.MuiButton-colorInfo");
("&.MuiButton-contained.MuiButton-colorWarning");
("&.MuiButton-text.MuiButton-sizeSmall");
("&.MuiButton-text.MuiButton-sizeMedium");
("&.MuiButton-text.MuiButton-sizeLarge");
("&.MuiButton-outlined.MuiButton-sizeSmall");
("&.MuiButton-outlined.MuiButton-sizeMedium");
("&.MuiButton-outlined.MuiButton-sizeLarge");
("&.MuiButton-contained.MuiButton-sizeSmall");
("&.MuiButton-contained.MuiButton-sizeMedium");
("&.MuiButton-contained.MuiButton-sizeLarge");
("&.MuiButton-sizeSmall > .MuiButton-icon");
("&.MuiButton-sizeMedium > .MuiButton-icon");
("&.MuiButton-sizeLarge > .MuiButton-icon");
`&.${buttonClasses.text}.${buttonClasses.colorInherit}`;
`&.${buttonClasses.text}.${buttonClasses.colorPrimary}`;
`&.${buttonClasses.text}.${buttonClasses.colorSecondary}`;
`&.${buttonClasses.text}.${buttonClasses.colorSuccess}`;
`&.${buttonClasses.text}.${buttonClasses.colorError}`;
`&.${buttonClasses.text}.${buttonClasses.colorInfo}`;
`&.${buttonClasses.text}.${buttonClasses.colorWarning}`;
`&.${buttonClasses.outlined}.${buttonClasses.colorInherit}`;
`&.${buttonClasses.outlined}.${buttonClasses.colorPrimary}`;
`&.${buttonClasses.outlined}.${buttonClasses.colorSecondary}`;
`&.${buttonClasses.outlined}.${buttonClasses.colorSuccess}`;
`&.${buttonClasses.outlined}.${buttonClasses.colorError}`;
`&.${buttonClasses.outlined}.${buttonClasses.colorInfo}`;
`&.${buttonClasses.outlined}.${buttonClasses.colorWarning}`;
`&.${buttonClasses.contained}.${buttonClasses.colorInherit}`;
`&.${buttonClasses.contained}.${buttonClasses.colorPrimary}`;
`&.${buttonClasses.contained}.${buttonClasses.colorSecondary}`;
`&.${buttonClasses.contained}.${buttonClasses.colorSuccess}`;
`&.${buttonClasses.contained}.${buttonClasses.colorError}`;
`&.${buttonClasses.contained}.${buttonClasses.colorInfo}`;
`&.${buttonClasses.contained}.${buttonClasses.colorWarning}`;
`&.${buttonClasses.text}.${buttonClasses.sizeSmall}`;
`&.${buttonClasses.text}.${buttonClasses.sizeMedium}`;
`&.${buttonClasses.text}.${buttonClasses.sizeLarge}`;
`&.${buttonClasses.outlined}.${buttonClasses.sizeSmall}`;
`&.${buttonClasses.outlined}.${buttonClasses.sizeMedium}`;
`&.${buttonClasses.outlined}.${buttonClasses.sizeLarge}`;
`&.${buttonClasses.contained}.${buttonClasses.sizeSmall}`;
`&.${buttonClasses.contained}.${buttonClasses.sizeMedium}`;
`&.${buttonClasses.contained}.${buttonClasses.sizeLarge}`;
`&.${buttonClasses.sizeSmall} > .${buttonClasses.icon}`;
`&.${buttonClasses.sizeMedium} > .${buttonClasses.icon}`;
`&.${buttonClasses.sizeLarge} > .${buttonClasses.icon}`;
