module.exports = {
  AppBar: require('./js/app-bar.jsx'),
  AppCanvas: require('./js/app-canvas.jsx'),
  Checkbox: require('./js/checkbox.jsx'),
  DatePicker: require('./js/date-picker/date-picker.jsx'),
  Dialog: require('./js/dialog.jsx'),
  DialogWindow: require('./js/dialog-window.jsx'),
  DropDownIcon: require('./js/drop-down-icon.jsx'),
  DropDownMenu: require('./js/drop-down-menu.jsx'),
  EnhancedButton: require('./js/enhanced-button.jsx'),
  FlatButton: require('./js/flat-button.jsx'),
  FloatingActionButton: require('./js/floating-action-button.jsx'),
  IconButton: require('./js/icon-button.jsx'),
  Icon: require('./js/icon.jsx'),
  Input: require('./js/input.jsx'),
  LeftNav: require('./js/left-nav.jsx'),
  MenuItem: require('./js/menu-item.jsx'),
  Menu: require('./js/menu.jsx'),
  Mixins: {
    Classable: require('./js/mixins/classable.js'),
    ClickAwayable: require('./js/mixins/click-awayable.js'),
    WindowListenable: require('./js/mixins/window-listenable.js'),
  },
  Paper: require('./js/paper.jsx'),
  RadioButton: require('./js/radio-button.jsx'),
  RaisedButton: require('./js/raised-button.jsx'),
  Slider: require('./js/slider.jsx'),
  Toggle: require('./js/toggle.jsx'),
  Snackbar: require('./js/snackbar.jsx'),
  Toolbar: require('./js/toolbar.jsx'),
  ToolbarGroup: require('./js/toolbar-group.jsx'),
  Tooltip: require('./js/tooltip.jsx'),
  Utils: {
    CssEvent: require('./js/utils/css-event.js'),
    Dom: require('./js/utils/dom.js'),
    Events: require('./js/utils/events.js'),
    KeyCode: require('./js/utils/key-code.js'),
    KeyLine: require('./js/utils/key-line.js')
  }
};
