import * as React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CssBaseline from "@mui/material/CssBaseline";
import MUIThemeProvider from "../MUIThemeProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Nextjs 14 + Material UI + Tailwind CSS",
  description: "Generated by create next app with tailwind and MUI",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppRouterCacheProvider options={{ enableCssLayer: true}}>
        <MUIThemeProvider>
          <React.Fragment>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. (tailwind preflight is false)  */}
            <CssBaseline />
            {children}
          </React.Fragment>
        </MUIThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
