name: Add closing message to issue

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    name: Add closing message
    if: github.event.issue.state_reason == 'completed'
    uses: mui/mui-public/.github/workflows/issues_add-closing-message.yml@c13d72d8221b544497ea5dc8cbf44eb9782bd558 # master
    permissions:
      contents: read
      issues: write
