name: Add closing message to issue

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    name: Add closing message
    if: github.event.issue.state_reason == 'completed'
    uses: mui/mui-public/.github/workflows/issues_add-closing-message.yml@73b01ccc61d2096ec1bac12c735482f8d056c917 # master
    permissions:
      contents: read
      issues: write
