name: Add closing message to issue

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    name: Add closing message
    if: github.event.issue.state_reason == 'completed'
    uses: mui/mui-public/.github/workflows/issues_add-closing-message.yml@3aff78882d5ed7d5d6a22d13ffa91a75f1374ab1 # master
    permissions:
      contents: read
      issues: write
