import * as React from 'react';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import '@mui/material-pigment-css/styles.css';
import { ThemeProvider } from '../components/ThemeProvider';
import App from '../components/App';

export const metadata: Metadata = {
  title: 'Material UI x Pigment CSS',
  description: 'Generated by create next app',
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const { value: theme = 'dark' } = cookieStore.get('theme') ?? {};
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <App>{children}</App>
      </ThemeProvider>
    </html>
  );
}
