import MenuItem from '@material-ui/core/MenuItem';
import red from '@material-ui/core/colors/red';
import useTheme from '@material-ui/core/styles/useTheme';
import Tab from '@material-ui/core/Tab';
import { green as greenColor } from '@material-ui/core/colors';
import MuiTabs from '@material-ui/core/Tabs';
import createTheme from '@material-ui/core/styles/createTheme';
import yellow from '@material-ui/core/colors/yellow';
import TableContext from '@material-ui/core/Table/TableContext';
import SwitchBase from '@material-ui/core/internal/SwitchBase';
import Ripple from '@material-ui/core/ButtonBase/Ripple';
