import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { generateTailwindThemeCss } from '@mui/material-css-tools';
import { createTheme, generateThemeCss } from '@mui/material/styles';

const outFile = process.env.OUTFILE
  ? resolve(process.env.OUTFILE)
  : join(process.cwd(), 'test/noop-default-css-vite-sandbox/src/theme.css');
const outDir = process.env.OUTDIR
  ? resolve(process.env.OUTDIR)
  : join(process.cwd(), 'test/noop-default-css-vite-sandbox/src');
const theme = createTheme();

const themeOptions = [
  {
    name: 'blue',
    colorSchemes: { light: true, dark: true },
  },
  {
    name: 'green',
    colorSchemes: {
      light: { palette: { primary: { main: '#2e7d32' }, secondary: { main: '#e91e63' } } },
      dark: { palette: { primary: { main: '#66bb6a' }, secondary: { main: '#f48fb1' } } },
    },
  },
  {
    name: 'red',
    colorSchemes: {
      light: { palette: { primary: { main: '#c62828' }, secondary: { main: '#f57c00' } } },
      dark: { palette: { primary: { main: '#ef9a9a' }, secondary: { main: '#ffcc02' } } },
    },
  },
];

function createScopedTheme(rootSelector: string, colorSchemes: Record<string, any>) {
  return createTheme({
    cssVariables: {
      rootSelector,
      colorSchemeSelector: `${rootSelector}[data-mui-color-scheme="%s"]`,
    },
    colorSchemes,
  });
}

const rootThemeCss = themeOptions.map(({ name, colorSchemes }) => {
  return generateThemeCss(createScopedTheme(`.root-theme-${name}`, colorSchemes));
});

const nestedThemeCss = themeOptions.map(({ name, colorSchemes }) => {
  return generateThemeCss(createScopedTheme(`.inner-theme-${name}`, colorSchemes));
});

writeFileSync(
  outFile,
  [
    '/* Generated by test/noop-default-css-vite-sandbox/scripts/buildThemeCss.mts. */',
    ...rootThemeCss,
    ...nestedThemeCss,
  ].join('\n'),
  'utf8',
);

writeFileSync(
  join(outDir, 'tailwind.css'),
  [
    '/* Generated by test/noop-default-css-vite-sandbox/scripts/buildThemeCss.mts. */',
    '@layer theme, base, mui, components, utilities;',
    '',
    "@import 'tailwindcss/theme.css' layer(theme);",
    "@import 'tailwindcss/utilities.css' layer(utilities);",
    "@import './tailwind-theme.css';",
    '',
  ].join('\n'),
  'utf8',
);

writeFileSync(
  join(outDir, 'tailwind-theme.css'),
  [
    '/* Generated by test/noop-default-css-vite-sandbox/scripts/buildThemeCss.mts. */',
    generateTailwindThemeCss(theme),
    '',
  ].join('\n\n'),
  'utf8',
);
